export const WORDSDICT: {[key:string]:string } = {
   'skovox': 'The Skovox Blitzer is the monster in The Caretaker.',
   'wiles': 'John Wiles was the second producer of Doctor Who.',
   'tosin': 'Tosin Cole played companion Ryan Sinclair.',
   'nation': 'Terry Nation invented the Daleks.',
   'melkur': 'The Melkur is a disguise for the Master\'s Tardis in The Keeper of Traken.',
   'philip': 'Philip Hinchcliffe was a Doctor Who producer.',
   'duggan': 'Duggan is a detective, somewhat prone to smashing things, in City of Death.',
   'pepper': 'Lindy Pepper-Bean is the protagonist in Dot and Bubble.',
   'strax': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'silver': 'Silver Nemesis and Nightmare in Silver are both Doctor Who stories.',
   'gundan': 'The Gundan robots were designed to travel the time winds and destory the brutes who rule in Warriors\' Gate.',
   'venice': 'The Vampires of Venice is an eleventh Doctor story.',
   'sleep': 'Sleep No More is a Twelfth Doctor story.',
   'tigus': 'A volcanic planet visited in The Daleks\' Masterplan.',
   'whale': 'A Star Whale is carrying Starship UK in the Beast Below.',
   'orcini': 'Orcini is an ageing mercenary in Revelation of the Daleks.',
   'patrol': 'The Happiness Patrol is a seventh Doctor story.',
   'donna': 'Donna Noble was a companion of the Tenth Doctor.',
   'hazran': 'Hazran is a Mondasian who takes a liking to Nardole in The Doctor Falls.',
   'sylvia': 'Sylvia Noble is Donna\'s mother.',
   'auvers': 'Vincent van Gogh\'s painting The Church at Auvers depicts the Krafayis in Vincent and the Doctor.',
   'sladen': 'Elizabeth Sladen played companion Sarah Jane Smith.',
   'satan': 'The Satan Pit is a Tenth Doctor story.',
   'briggs': 'Nick Briggs voices the Daleks in the modern Doctor Who series.',
   'abbey': 'The famous Abbey Road zebra crossing appears in The Devil\'s Chord.',
   'savage': 'Becka Savage, landowner, magistrate and prosecutor of witch trials, is taken over by the Morax in The Witchfinders.',
   'aliens': 'Aliens of London is a ninth Doctor story.',
   'wills': 'Anneke Wills played Polly, companion to the First and Second Doctors.',
   'asgard': 'The Doctor and River Song had a picnic at Asgard.',
   'people': 'The Almost People is an eleventh Doctor story.',
   'mickey': 'Mickey Smith is Rose\'s boyfriend and briefly a companion of the Doctor.',
   'gadget': 'Gadget the Robot appears in The Waters of Mars.',
   'breath': 'Deep Breath is a twelfth Doctor story.',
   'polly': 'Polly was a companion of the first and second Doctors.',
   'doctor': 'Doctor Who?',
   'family': 'The Family of Blood is a tenth Doctor story.',
   'bishop': 'John Bishop played companion Dan.',
   'ursula': 'Ursula Blake is Elton Pope\'s love interest in Love and Monsters.',
   'cryons': 'The Cryons lived on Telos before the Cybermen came.',
   'oberon': 'Orcini is a Knight of Oberon in Revelation of the Daleks.',
   'nimon': 'The Nimon are minotaur like creatures from The Horns of Nimon.',
   'louise': 'Louise Jameson played companion Leela.',
   'bride': 'The Runaway Bride is a Tenth Doctor story.',
   'mentor': 'The Mentors, including Sil and Kiv, control Thoros Beta in Mindwarp.',
   'detsen': 'The Detsen Monastery is where the Doctor first meets the Yeti in The Abominable Snowmen.',
   'cooper': 'Gwen Cooper appears in the Stolen Earth and Journey\'s End as well as being one of the main characters in Torchwood.',
   'germs': 'Spider Germs menace the characters in Kill the Moon.',
   'wotan': 'WOTAN was an evil computer that appeared in The War Machines.',
   'necros': 'Revelation of the Daleks is set on the planet Necros in the funeral home Tranquil Repose.',
   'grace': 'Grace Holloway was the Doctor\'s companion in the TV Movie.',
   'ghosts': 'Army of Ghosts is a tenth Doctor story.',
   'school': 'School Reunion is a tenth Doctor story.',
   'frazer': 'Frazer Hines played companion Jamie.',
   'delta': 'Delta and the Bannermen is a Seventh Doctor story.',
   'heist': 'Time Heist is a Twelfth Doctor story.',
   'stotz': 'Stotz leads the mercenaries in The Caves of Androzani.',
   'zucker': 'Mels Zucker is a friend of Amy and Rory who turns out to be an early incarnation of River Song.',
   'smile': 'Smile is a Twelfth Doctor story.',
   'styles': 'Day of Daleks involves time travellers attempting to assassinate diplomat Sir Reginald Styles.',
   'above': 'He who to Rassilon\'s Tower would go must choose above, between, below.',
   'staal': 'General Staal is a Sontaran in The Sontaran Stratagem.',
   'dicks': 'Terrance Dicks was a Doctor Who writer, script editor and prolific noveliser of Doctor Who stories.',
   'crime': 'Partners in Crime is a Tenth Doctor story.',
   'covent': 'WOTAN builds War Machines in a Warehouse near Covent Garden in The War Machines.  The travellers land at the tube station in The Web of Fear.',
   'raven': 'Face the Raven is a Twelfth Doctor story.',
   'vlinx': 'The Vlinx works for UNIT.',
   'freema': 'Freema Agyeman played companion Martha Jones.',
   'avery': 'Pirate Henry Avery appears in The Curse of the Black Spot and is mentioned in The Smugglers.',
   'kahler': 'The Aliens in A Town called Mercy are both Kahler.',
   'rescue': 'The Rescue is a first Doctor story.',
   'logic': 'According to the Second Doctor logic merely allows one to be wrong with authority.',
   'hilio': 'Hilio was a Menoptera, played by Martin Jarvis, in The Web Planet.',
   'demnos': 'The Cult of Demnos were used by the Mandragora Helix in The Masque of Mandragora.',
   'tremas': 'Tremas is Nyssa\'s father in The Keeper of Traken.  His body is taken over by the Master.',
   'helen': 'Helen A was the villain in The Happiness Patrol.',
   'scroll': 'The Black Scrolls of Rassilon reveal the secrets of the Death Zone  on Gallifrey.',
   'selby': 'Tony Selby played Glitz in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'horns': 'The Horns of Nimon is a Fourth Doctor story.',
   'moroks': 'The Moroks are the rulers of Xeros in the Space Museum.',
   'janis': 'Leela is initially very keen on killing people with Janis Thorns.',
   'steel': 'The Age of Steel is a Tenth Doctor story.',
   'danny': 'Danny Pink is Clara Oswald\'s boyfriend.',
   'eighth': 'Paul McGann played the Eighth Doctor.',
   'karen': 'Karen Gillan played Amy Pond, companion.',
   'idiot': 'The Idiot\'s Lantern is a Tenth Doctor story.',
   'rodan': 'Rodan was a female Gallifreyan Traffic Controller who helps the Doctor and Leela in the Invasion of Time.',
   'horror': 'Horror of Fang Rock and The Crimson Horror are both Doctor Who stories.',
   'iraxxa': 'Iraxxa is the Empress of the Ice Warriors.',
   'logie': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'restac': 'Restac is a Silurian Warrior Leader in Cold Blood.',
   'space': 'Doctor Who adventures in Time and Space.',
   'nikola': 'Nikola Tesla\'s Night of Terror is a thirteenth Doctor story.',
   'morlox': 'The Molox lizards appear in Timelash.',
   'autons': 'The Autons are monsters appearing in Spearhead from Space, Terror of the Autons and Rose.',
   'jarvis': 'Jarvis Bennet is controller of the Wheel in Space.',
   'knock': 'Knock Knock is a Twelfth Doctor story.',
   'arwell': 'The Doctor, the Widow and the Wardrobe centres around the Arwell family.',
   'empty': 'The Empty Child is a Ninth Doctor story.',
   'talbot': 'Ann Talbot is Nyssa\'s double in The Black Orchid.',
   'jamie': 'Jamie McCrimmon was a companion of the Second Doctor.',
   'planet': 'Planet of Giants, The Web Planet, The Tenth Planet, Planet of the Daleks, Planet of the Spiders, Planet of Evil, The Pirate Planet, Planet of Fire, The Mysterious Planet, The Impossible Planet, Planet of the Ood, and Planet of the Dead are all Doctor Who stories.',
   'lytton': 'Lytton is a Space Mercenary who appears in Resurrection of the Daleks and Attack of the Cybermen.',
   'beetle': 'A Time Beetle appears in Turn Left.',
   'triad': 'Susan Twist playse Susan Triad in The Legend of Ruby Sunday and The Empire of Death.',
   'scorby': 'Scorby is Harrison Chase\'s henchman in The Seeds of Doom.',
   'decay': 'State of Decay is a Fourth Doctor story.',
   'verney': 'Andrew Verney is Tegan\'s grandfather.',
   'alfava': 'The Time of Angels and Flesh and Stone take place on the planet Alfava.',
   'varada': 'Varada Sethu will play a new companion in the 2025 season.',
   'stenck': 'Commander Stenck leads the Sontarans in The Vanquishers.',
   'keeper': 'The Keeper of Traken is a fourth Doctor story.',
   'amelia': 'Amy Pond is called Amelia in her childhood.',
   'lazar': 'Nyssa catches Lazar disease in Terminus and remains behind to help find a cure.',
   'millie': 'Millie Gibson played companion Ruby Sunday.',
   'azaxyr': 'Azaxyr is an Ice Lord in Monster of Peladon',
   'saucer': 'The Dalek Saucer appears in The Dalek Invasion of Earth.',
   'legion': 'In The Eaters of Light the remains of the Roman Ninth Legion help hold back the Eater inside a pictish cairn.',
   'devils': 'The Sea Devils and Legend of the Sea Devils are both Doctor Who stories.',
   'altos': 'Altos is an agent of Arbitan in the Keys of Marinus.',
   'gurney': 'Smallbeer, Ringwood, Gurney - names on gravestones - are the clue to the location of Avery\'s treasure in The Smugglers.',
   'nathan': 'John Nathan-Turner was a Doctor Who producer.',
   'cryon': 'The Cryons were a race in Attack of the Cybermen.',
   'penny': 'Susan Twist plays Penny Pepper-Bean in Dot and Bubble.',
   'dibber': 'Dibber is Glitz\'s partner in The Mysterious Planet.',
   'gravis': 'Gravis is the leader of the Tractators in Frontios.',
   'kaftan': 'Kaftan is one of the villains in Tomb of the Cybermen.',
   'cruel': 'In various forms the words \'Never cruel or cowardly\' have been used in Doctor Who.',
   'traken': 'The Keeper of Traken is a fourth Doctor story.',
   'eaters': 'The Eaters of Light is a twelfth Doctor story.',
   'editor': 'The Editor runs Satellite 5 for the Jagrafess in The Long Game.',
   'billie': 'Billie Piper played companion Rose Tyler.',
   'things': 'The Journal of Impossible Things was a dream diary kept by the Tenth Doctor\'s human persona, John Smith, in The Family of Blood.',
   'swamp': 'When Mistfall comes the Marshmen leave the Swamp in Full Circle.',
   'yasmin': 'Yasmin Khan was a companion of the thirteenth Doctor.',
   'kronos': 'Kronos the Chronovore appears in The Time Monster.',
   'rebel': 'The Rebel Flesh is an Eleventh Doctor story.',
   'wales': 'The modern Doctor Who series was bought back by BBC Wales and is made in Cardiff.',
   'azmael': 'Azmael is an old friend of the Doctor\'s forced to help the evil giant Gastropods in The Twin Dilemma.',
   'hamish': 'The Brigadier\'s grandfather is Archibald Hamish Lethbridge-Stewart.',
   'clams': 'Giant clams lurk in the sewers of the Kaled City in Genesis of the Daleks.  One of them attacks Harry.',
   'police': 'The Tardis is disguised as a Police Public Call Box.',
   'deadly': 'The Deadly Assassin is a fourth Doctor story.',
   'random': 'In Extremis the simulation\'s inhabitants work out they are simulations because they all pick the same random number.',
   'daniel': 'Daniel Barton, played by Lenny Henry is the antagonist in Spyfall.',
   'steven': 'Steven Taylor was a companion to the first Doctor.',
   'young': 'Mal Young was an executive producer of Doctor Who.',
   'adeola': 'Martha\'s cousin Adeola appears in Army of Ghosts, also played by Freema Agyeman.',
   'wirrn': 'The Wirrn were monsters that appeared in The Ark in Space.',
   'lumic': 'John Lumic is the villain in Rise of the Cybermen and The Age of Steel.',
   'saloon': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'nikki': 'Nikki Wilson was executive producer of Doctor Who.',
   'chase': 'The Chase is a First Doctor story.',
   'matron': 'Matron Casp is the villain in New Earth and Matron Cofelia is the villain in Partners in Crime.',
   'fenric': 'The Curse of Fenric is a seventh Doctor story.',
   'delia': 'Delia Derbyshire composed the theme tune.',
   'trion': 'Home planet of the Doctor\'s companion Turlough.',
   'alien': 'The Earth is frequently invaded by aliens in Doctor Who.',
   'robin': 'Robin Hood appears in Robot of Sherwood.',
   'great': 'The Great Intelligence is a recurring enemy of the Doctor.',
   'wyatt': 'Wyatt Earp appears in the Doctor Who story The Gunfighters.',
   'nunton': 'The Nunton Experimental Complex is the setting for much of The Hand of Fear.',
   'jelly': 'The Fourth Doctor often offered people Jelly Babies.',
   'kemel': 'Kemel is a servant of the Maxfields in The Evil of the Daleks and helps Jamie rescue Victroia.',
   'listen': 'Listen is a twelfth Doctor story.',
   'chief': 'The War Chief was one of the villains in The War Games',
   'zeiton': 'Zeiton-7 ore is vital for realigning the power systems of time machines.',
   'zygons': 'Terror of the Zygons is a fourth Doctor story.',
   'stairs': 'Not as often a problem for Daleks as some people think.',
   'anneke': 'Anneke Wills played companion Polly.',
   'gerry': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'lynda': 'Lynda (with a Y) is almost a companion in Bad Wolf and the Parting of the Ways.',
   'taylor': 'Steven Taylor was a companion to the first Doctor.',
   'wells': 'H. G. Wells appears in the story Timelash.',
   'mestor': 'Mestor is the leader of the Giant Gastropods in The Twin Dilemma.',
   'tracer': 'The Tracer is used to detect segments of the Key to Time.',
   'kinda': 'Kinda is a Fifth Doctor story.',
   'andrew': 'Andrew Cartmel script-edited Doctor Who.',
   'storm': 'Robots of Death takes place on a Storm Mine.',
   'heart': 'The Doctor has two hearts.',
   'maaga': 'Maaga was the villainous leader of the Drahvin in Galaxy Four.',
   'stone': 'Flesh and Stone is an Eleventh Doctor episode.',
   'vivien': 'Vivien Fay is the identity assumed by Cessair of Diplos in The Stones of Blood.',
   'pting': 'The Pting is the monster in The Tsuranga Conundrum.',
   'davies': 'Russell T Davies was the showrunner who brought back Doctor Who.',
   'kelner': 'Castellan Kelner serves the invaders of Gallifrey in The Invasion of Time.',
   'bubble': 'Dot and Bubble is a Fifteenth Doctor story.',
   'towers': 'Paradise Towers is a seventh Doctor story.',
   'visian': 'The Visians are the invisible inhabitants of the planet Mira in the Daleks\' Masterplan.',
   'spider': 'Giant Spiders are the monsters in Planet of the Spiders',
   'astra': 'Princess Astra of Atrios is the sixth segment of the Key to Time.  Romana chooses to look like her when she regenerates.',
   'styre': 'Styre is the Sontaran in The Sontaran Experiment.',
   'macra': 'The Macra are giant crab like monsters that appeared in both The Macra Terror and Gridlock.',
   'aneth': 'Aneth is a planet in The Horns of Nimon.',
   'battle': 'The Battle of Ranskoor Av Kolos is a thirteenth Doctor story.',
   'razor': 'The Master disguises himself as Razor in World Enough and Time.',
   'first': 'William Hartnell played the First Doctor.',
   'azure': 'Azure is one of the villains in Flux.',
   'kragar': 'Kragar is a Sontaran Psychic Surveryor in The Vanquishers.',
   'poppy': 'Poppy is captain of the Space Babies.',
   'chiang': 'The Talons of Weng-Chiang is a fourth Doctor story.',
   'twice': 'Twice Upon a Time is a Twelfth Doctor story.',
   'kandy': 'The Kandy Man is a deadly robot in The Happiness Patrol.',
   'varos': 'Varos is the planet in Vengeance on Varos.',
   'nicola': 'Nicola Bryant played companion Peri Brown.',
   'artron': 'Artron Energy is a form of mental energy utilised by the Time Lords.',
   'tryst': 'Professor Tryst was the villian in The Nightmare of Eden.',
   'centre': 'Journey to the Centre of the TARDIS is an elevent Doctor story.',
   'lords': 'Last of the Time Lords is a Tenth Doctor story.',
   'human': 'Human Nature is a Tenth Doctor story.',
   'chalk': 'In Battlefield, Ace and Shou Yuing hold off the Destroyer with a chalk circle.',
   'davina': 'Davina McCall appears as herself in The Church on Ruby Road.',
   'tyburn': 'Sam Swift is to be hung at Tyburn before being saved by the Doctor and Me in The Woman Who Lived.',
   'snake': 'The Mara takes the form of a giant snake.',
   'carrot': 'Mel makes the Doctor drink carrot juice.',
   'santa': 'Robot Santas threaten the Doctor in the Christmas Invasion and the Runaway Bride.',
   'widow': 'The Doctor, the Widow and the Wardrobe is an Eleventh Doctor story.',
   'drahva': 'Drahva is the home of the Drahvins.',
   'oswin': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'robots': 'The Robots of Death is a fourth Doctor story.',
   'goodge': 'The army base in The Web of Fear is under Goodge Street tube station.',
   'daemon': 'Azal is a Daemon.',
   'white': 'The White Guardian is the anthropomorphic personification of order and good.',
   'fourth': 'The Fourth Doctor was played by Tom Baker.',
   'vortis': 'Vortis is the planet of the Zarbi and the Menoptera in The Web Planet.',
   'quarks': 'The Quarks are the robot servants of the Dominators.',
   'helmic': 'The Helmic Regulator controls the accuracy of flight through the vortex.',
   'segun': 'Segun Akinola currently composes the music for Doctor Who.',
   'roman': 'The Romans is a First Doctor story.',
   'dregs': 'The Dregs are the remains of humanity in Orphan 55',
   'flynn': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'megara': 'The Megara are Justice Machines in The Stones of Blood.',
   'engin': 'Co-ordinator Engin is in charge of the Matrix in The Deadly Assassin.',
   'noble': 'Donna Noble was a companion of the Tenth Doctor.',
   'mummy': 'Mummy on the Orient Express is a Twelfth Doctor story.',
   'sarah': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'ogros': 'Planet of the Ogri from the Stones of Blood.',
   'henrik': 'At the start of the modern series, Rose works in Henrik\'s department store.',
   'merlin': 'In Battlefied it is revealed that a future Doctor is Merlin.',
   'hines': 'Frazer Hines played Jamie, companion to the Second Doctor.',
   'cosmic': 'The Second Doctor was envisioned as a Cosmic Hobo.',
   'cyril': 'Cyril is an evil school boy in The Celestial Toryroom.',
   'utopia': 'Utopia is a tenth Doctor story.',
   'image': 'Image of the Fendahl is a Fourth Doctor story.',
   'sontar': 'Sontar is the home world of the Sontarans.',
   'lindy': 'Lindy Pepper-Bean is the protagonist in Dot and Bubble.',
   'grant': 'Jo Grant was a companion of the Third Doctor.',
   'asylum': 'Asylum of the Daleks is an eleventh Doctor story.',
   'canton': 'Canton Everett helps the Doctor in The Impossible Planet and Day of the Moon.',
   'roger': 'Roger Delgado was the first actor to play The Master.',
   'aztec': 'The Aztecs is a First Doctor story.',
   'queen': 'The milk of the Queen Bat is a cure for Spectrox Toxaemia in Tge Caves of Androzani.  The Doctor also married Queen Elizabeth I and was exiled by Queen Victoria.',
   'saward': 'Eric Saward script-edited Doctor Who.',
   'eater': 'The Eater of Light is the monster in The Eaters of Light.',
   'vasor': 'Vasor is an antagonist in the frozen wastes in The Keys of Marinus.',
   'pearl': 'Pearl Mackie played companion Bill Potts.',
   'varga': 'Varga plants are deadly, but slow-moving, mobile plants from the planet Kembel.  It is also the name of an Ice Warrior.',
   'cotton': 'Stubbs and Cotton are two sympathetic guards in The Mutants.',
   'borad': 'The Borad is the villain in Timelash.',
   'rusty': 'Rusty is a "good" Dalek.',
   'lupari': 'Karvanista in Flux is a member of the Lupari race.',
   'celery': 'The Fifth Doctor wore a stick of celery on his lapel.',
   'church': 'The Church on Ruby Road is a Fifteenth Doctor story.',
   'benton': 'Sergeant Benton was a recurring UNIT character.',
   'judoon': 'Fugitive of the Judoon is a thirteenth Doctor story.',
   'skorr': 'Commander Skorr is a Sontaran in The Sontaran Stratagem.',
   'chang': 'Chang Lee was the Doctor (or the Master)\'s companion in the TV Movie.',
   'pirate': 'The Pirate Planet is a fourth Doctor story.',
   'waited': 'The Girl Who Waited is an eleventh Doctor story.',
   'segal': 'Philip Segal was Executive Producer for the TV Movie.',
   'flavia': 'Chancellor Flavia was appointed acting President of the Time Lords by the Doctor in The Five Doctors.',
   'world': 'The Enemy of the World, The End of the World, World War Three, The Pyramid at the End of the World and World Enough and Time are all Doctor Who stories.',
   'moths': 'Flesh Moths inhabit the space between universes in It Takes You Away.',
   'klieg': 'Eric Klieg is one of the villains in Tomb of the Cybermen.',
   'stooky': 'Stooky Bill is the puppet used by John Logie Baird that starts the Giggle.',
   'izlyr': 'Izlyr is an Ice Warrior who appears in The Curse of Peladon',
   'legend': 'Legend of the Sea Devils and the Legend of Ruby Sunday are both Doctor Who stories.',
   'banks': 'David Banks played many Cyber Leaders in the 1980s.',
   'tyler': 'Rose Tyler was a companion of the Ninth and Tenth Doctors.',
   'signet': 'The first Doctor wore a Signet Ring - also worn by the twelfth Doctor.',
   'drums': 'The Sound of Drums is a Tenth Doctor story.',
   'brain': 'The Brain of Morbius is Fourth Doctor story.',
   'telos': 'Telos is a Cyberman planet that featured in both Tomb of the Cybermen and Attack of the Cybermen.',
   'dennis': 'Dennis Spooner script-edited Doctor Who.',
   'venus': 'Presumably where the Doctor learned Venusian Aikido.',
   'dulkis': 'Dulkis is the planet invaded by the Dominators.',
   'venom': 'Venom Grubs are one of the races on the Web Planet, Vortis.',
   'stolen': 'The Stolen Earth is a tenth Doctor story.',
   'brian': 'There have been several Brians associated with Doctor Who included Brian Hayles who created the Ice Warriors and executive producer Brian Minchin.',
   'masque': 'The Masque of Mandragora is a fourth Doctor story.',
   'morton': 'Peter Purves appears as annoying tourist Morton Dill in The Chase before reappearing as new companion Steven Taylor later in the same story.',
   'trees': 'The Trees save the day in Into the Forest of the Night and the Androzani Trees are endangered in The Doctor, The Widow and the Wardrobe.',
   'leeson': 'John Leeson voiced K9.',
   'globe': 'Much of The Shakespeare Code is set at the Globe Theatre in London.',
   'sigma': 'Theta Sigma was the Doctor\'s nickname at the Time Lord academy.  In the Happiness Patrol all aliens are designated Sigma.  Later Ood Sigma is instramental in freeing the Ood.',
   'xoanon': 'Xoanon is a crazed computer in The Face of Evil.',
   'scarf': 'The Fourth Doctor was famous for his long scarf.',
   'frock': 'The First Doctor wore an Edwardian frock coat.',
   'carole': 'Carole Ann Ford played Susan, the Doctor\'s granddaughter.',
   'zygon': 'The Zygons appeared in Terror of the Zygons, The Day of the Doctor, The Zygon Invasion and The Zygon Inversion.',
   'water': 'Dark Water is a Twelfth Doctor story.',
   'pharos': 'The Fourth Doctor regenerates when he falls from the antenna of the Pharos Project.',
   'halpen': 'Mr Halpen is the president of Ood Industries in Planet of the Ood.  The Ood turn him into an Ood.',
   'xeros': 'The Tardis visits the planet Xeros in The Space Museum.',
   'hedin': 'Councillor Hedin is a villain in Arc of Infinity.',
   'jenna': 'Jenna Coleman played companion Clara Oswald.',
   'pilot': 'The Pilot is a Twelfth Doctor story.',
   'aztecs': 'The Aztecs was a first Doctor story.',
   'estram': 'In the King\'s Demons, the Master disguises himself as Sir Gilles Estram.',
   'sophie': 'Sophie Aldred played companion Ace.',
   'zodin': 'The Terrible Zodin was mentioned but never seen.',
   'ribos': 'The planet Ribos appears in the Ribos Operation.',
   'chord': 'The Devil\'s Chord is a Fifteenth Doctor story.',
   'shura': 'Shura is a rebel time traveller from the Daleks in Day of the Daleks who nearly creates a bootstrap paradox.',
   'tasha': 'Tasha Lem leads the Church of the Papal Mainframe in Time of the Doctor.',
   'alpha': 'Alpha Centauri is a diplomat who appears in The Curse of Peladon',
   'shirna': 'Vorg and Shirna bring a miniscope to Inter Minor in Carnival of Monsters.',
   'scoop': 'The Time Scoop was created during the Dark Time on Gallifrey.',
   'reign': 'The Reign of Terror is a First Doctor story.',
   'chris': 'Chris Chibnall is the current Doctor Who showrunner.  Christopher Eccleston played the Ninth Doctor.',
   'schism': 'The Master was driven mad when he gazed into the Untempered Schism as a child.',
   'lance': 'Lance Bennet is Donna Noble\'s fiance in The Runaway Bride.',
   'london': 'Aliens of London is a ninth Doctor story.',
   'kublai': 'The Doctor meets Kublai Khan in Marco Polo.',
   'nerva': 'The Nerva Space Station features in both The Ark in Space and Revenge of the Cybermen.',
   'krasko': 'Krasko is the antagonist in Rosa.',
   'tobias': 'Tobias Vaughn is the villian in The Invasion.',
   'flood': 'Mrs Flood is a mysterious neighbour of the Sundays.',
   'ricky': 'Ricky September is Lindy Pepper-Bean\'s love interest in Dot and Bubble before she kills him.',
   'gibbis': 'Gibbis is a Cowardly Tivolian in The God Complex.',
   'condo': 'Condo was Solon\'s Henchman in The Brain of Morbius.',
   'papal': 'The Papal Mainframe is the headquarters of the militarised Church.',
   'mondas': 'Mondas is the home of the Cybermen.',
   'before': 'Before the Flood is a twelfth Doctor story.',
   'blood': 'The Stones of Blood, The Family of Blood, and Cold Blood are all Doctor Who stories.',
   'fungus': 'In the Seeds of Death the Ice Warriors release a fungus to remove the Oxygen from the Earth.',
   'gracht': 'Count Grendal of Gracht is the villain in The Androids of Tara.',
   'marco': 'Marco Polo was the show\'s fourth story.',
   'ssorg': 'Ssorg is an Ice Warrior who appears in the Curse of Peladon',
   'gonds': 'The Gonds live on the Planet of the Gonds in The Krotons.',
   'zolfa': 'Zolfa Thura is the home planet of Meglos.',
   'isolus': 'Chloe Webber is possessed by an Isolus in Fear Her.',
   'acteon': 'Metebelis 3 is the famous blue planet in the Acteon Galaxy.',
   'newton': 'Isaac Newton appears (briefly) in Wild Blue Yonder.',
   'bunker': 'The Bunker is the location for all scientific research on Skaro at the time of the creation of the Daleks.',
   'clara': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'ogrons': 'Ogrons are the servants of the Daleks.',
   'hungry': 'The Hungry Earth is an eleventh Doctor story.',
   'panda': 'Steven Taylor brings his toy panda with him into the Tardis.  Panda is also Iris Wildthyme\'s companion in Paul Mags\' stories.',
   'osgood': 'Corporal Osgood is a UNIT Technical Officer in The Daemons.  Petronella Osgood who may (or may not) be related, is UNIT\'s Scientific Advisor under Kate Stewart.',
   'hadron': 'The Master uses Hadron Energy to bind Adric in Castrovalva.',
   'lupton': 'Lupton is the villain in Planet of the Spiders',
   'terra': 'Terra Alpha is the planet in The Happiness Patrol.',
   'remus': 'Romulus and Remus were the twins in The Twin Dilemma.',
   'hearts': 'The Knave, King and Queen of Hearts appear in The Celestial Toymaker.',
   'gerald': 'Gerald Flood voiced Kamelion.',
   'glitz': 'Glitz is a character in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'jemma': 'Jemma Redgave played Kate Stewart, the head of UNIT.',
   'oswald': 'Clara Oswald was a companion to the eleventh and twelfth Doctors.',
   'poison': 'The Poison Sky is a tenth Doctor story.',
   'factor': 'The Armageddon Factor is a fourth Doctor story.',
   'gatwa': 'Ncuti Gatwa plays the Fifteenth Doctor.',
   'george':  'A Tenza child becomes the terrified George in Night Terrors.',
   'guard': 'Gel Guards are the servants of Omega in The Three Doctors.',
   'romans': 'The Romans is a first Doctor story.',
   'vislor': 'Vislor Turlough was a companion to the fifth Doctor.',
   'ashad': 'Ashad is the lone Cyberman.',
   'ching': 'Madam Ching, the famous pirate, appeared in Legend of the Sea Devils.',
   'exile': 'The Third Doctor is exiled to Earth.',
   'hobson': 'Hobson is the base commander in The Moonbase.',
   'sweet': 'Mr Sweet is a villain in The Crimson Horror.',
   'wenley': 'Wenley Moor Nuclear Research Facility appears in The Silurians.',
   'peter': 'There are lots of Peters associated with Doctor Who including, Peter Purves who played companion Steven Taylor, Peter Bryant producer, Peter Davison who played the Fifth Doctor and Peter Capaldi who played the Twelfth Doctor.',
   'pluto': 'The Sun Makers is set on Pluto.',
   'bessie': 'The Third Doctor\'s Edwardian Roadster is called Bessie.',
   'tower': 'Rassilon\'s Tomb lies in a Tower in the Death Zone on Gallifrey.',
   'benny': 'In the novels, Bernice Summerfield (known as Benny) was a companin to the Seventh Doctor.',
   'hoothi': 'In The Brain of Morbius the Sisterhood of Karn claim to be able to detect the silent gas dirigibles of the Hoothi.',
   'malone': 'In later life Amy writes Melody Malone mysteries.',
   'bellal': 'The Exxilon Bellal helps the Doctor in Death to the Daleks.',
   'palmer': 'Professor Alec Palmer is conducting pyschic experiments in Hide.',
   'green': 'The Green Death is a Third Doctor story.',
   'clent': 'Leader Clent runs the Britanicus Base in the Ice Warriors.',
   'linda': 'The London Investigation \'n\' Detective Agency (LINDA) seeks to learn more about the Doctor in Love & Monsters.',
   'capel': 'Taren Capel is the villain in The Robots of Death',
   'panama': 'The fifth Doctor wore a Panama Hat.',
   'holmes': 'Robert Holmes script-edited Doctor Who.',
   'greel': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'omega': 'Omega was a legendary Time Lord who created the supernova that powers Time Lord civilisation',
   'ainley': 'Anthony Ainley played the Master in the 1980s.',
   'kroton': 'The Krotons are the monsters in The Krotons.',
   'vogans': 'The Vogans appear in Revenge of the Cybermen.',
   'davros': 'Davros is the creater of the Daleks.',
   'cheng': 'Suki Cheng was the villain in Praxeus.',
   'elton': 'Elton is the viewpoint character in Love & Monsters.',
   'nyder': 'Nyder is Davros\' Henchman in Genesis of the Daleks.',
   'yetaxa': 'In the Aztecs, Barbara is mistaken for a reincarnation of the high priest Yetaxa.',
   'diplos': 'Vivien Fay is the identity assumed by Cessair of Diplos in The Stones of Blood.',
   'david': 'There are lots of Davids associated with Doctor Who including David Whitaker the show\'s first story editor, David Brierly who voiced K9 and David Tennant who played the Tenth Doctor.',
   'nixon': 'President Richard Nixon appears in The Impossible Astronaut and Day of the Moon.',
   'state': 'State of Decay is a Fourth Doctor story.',
   'verity': 'Verity Lambert was the first producer of Doctor Who.',
   'paddy': 'Paddy Russell was the first female director to work on Doctor Who.',
   'adric': 'Adric was a companion of the Fourth and Fifth Doctors.',
   'thames': 'The Racnoss Empress is hidden under the Thames Barrier.',
   'astrid': 'Kylie Minogue plays Astrid Peth in Voyage of the Damned.',
   'susan': 'Susan was is the Doctor\'s Grandaughter.',
   'return': 'The Return of Doctor Mysterio is a twelfth Doctor story.',
   'orphan': 'Orphan 55 is a thirteenth Doctor story.',
   'morris': 'Morris Gibbons is the UNIT scientific advisor in The Legend of Ruby Sunday and Empire of Death.',
   'rakaya': 'Zellin and Rakaya are the immortal villains in Can You Hear Me?',
   'solos': 'Solos is an Earth Colony in The Mutants',
   'wendy': 'Wendy Padbury played Zoe, companion to the Second Doctor.',
   'effect': 'The Blinovitch Limitation Effect regulates time travel.',
   'blink': 'Blink is a Tenth Doctor episode.',
   'newman': 'Doctor Who was the brain child of Syndney Newman.',
   'swarm': 'Swarm is one of the villains in Flux.',
   'tekker': 'Tekker is the ambitious leader of Karfel in Timelash.',
   'lloyd': 'Innes Lloyd was a Doctor Who producer.',
   'shakri': 'Shakri cubes appear all over the Earth in the Power of Three.',
   'varsh': 'Varsh was Adric\'s brother in Full Circle.',
   'morgus': 'Morgus is the villain in The Caves of Androzani.',
   'zellin': 'Zellin and Rakaya are the immortal villains in Can You Hear Me?',
   'atrios': 'Atrios and Zeos are two planets at war in The Armageddon Factor.',
   'morok': 'The Moroks are the villains in The Space Museum.',
   'taran': 'The Taran Wood Beast is a creature in the Androids of Tara.',
   'barry': 'Barry Letts was a producer and director of Doctor Who.',
   'paper': 'The Doctor often uses Psychic Paper to get past officials.',
   'dyall': 'Valentine Dyall played the Black Guardian.',
   'cameca': 'The Doctor accidentally becomes engaged to Cameca in The Aztecs.',
   'erato': 'Erato was the Creature from the Pit.',
   'farisi': 'Rosita Farisi is Jackson Lake\'s companion in the Next Doctor.',
   'ringo': 'Johnny Ringo appears in the Doctor Who story The Gunfighters and Ringo Star appears in The Devil\'s Chord.',
   'auton': 'The Autons are plastic creatures controlled by the Nestene Consciousness.',
   'below': 'The Beast Below was an Eleventh Doctor episode.',
   'thals': 'The Thals are the enemy of the Daleks... And I promised Prof. Dresner I would include them.',
   'corral': 'The events of The Gunfighters lead up to the gunfight at the O.K. Corral.',
   'earpod': 'The Cybermen use EarPods to take control of people in Rise of the Cybermen.',
   'rounds': 'The Brigadier famously said \'chap with wings, five rounds rapid.\'.',
   'quark': 'The Quarks are the robot servants of the Dominators',
   'colin': 'The Sixth Doctor was played by Colin Baker.',
   'letts': 'Barry Letts was a producer and director of Doctor Who.',
   'vaughn': 'Tobias Vaughn is the villian in The Invasion.',
   'vulcan': 'Vulcan is the planet in Power of the Daleks.',
   'vigil': 'The Vigil were one of the races of the Rings of Akhaten.',
   'silent': 'The Silent are the individual members of The Silence.',
   'skasis': 'The Skasis Paradigm is the mathematical equation behind the way the universe works.',
   'raston': 'The Raston Warrior Robot appears in the Five Doctors.',
   'chips': 'Chips coated in Krillitane Oil were served to the children in School Reunion.',
   'cromer': 'The Brigadier mistakes Omega\'s realm for Cromer in The Three Doctors.',
   'retcon': 'Retcon is a substance used to make people forget.  It was used a lot in Torchwood and also in Face the Raven.',
   'dream': 'The Dream Lord is a manifestation of the Doctor\'s subconscious.  Dream Crabs attack the characters in Last Christmas.',
   'huffle': 'In The Return of Doctor Mysterio, Lucy interogates the Doctor by squeezing a Mr. Huffle toy.',
   'slaar': 'Slaar is an Ice Warrior who appears in The Seeds of Death.',
   'garron': 'Garron and Unstoffe are a criminal duo in The Ribos Operation.',
   'victor': 'Victor Pemberton script-edited Doctor Who.',
   'tetrap': 'The Tetraps serve the Rani in Time and the Rani.',
   'waters': 'The Waters of Mars is a tenth Doctor story.',
   'sutton': 'Sarah Sutton played companion Nyssa.',
   'dryads': 'The Dryads are beetle creatures that live in the house in Knock Knock.',
   'janet': 'Janet Fielding played Tegan Jovanka, companion to the Fourth and Fifth Doctors.',
   'master': 'The Master is the Doctor\'s Arch enemy.',
   'kazran': 'Kazran is the antagonist in A Christmas Carol.',
   'vault': 'In his final series, the Twelfth Doctor keeps Missy locked in a vault.',
   'marsh': 'Jean Marsh played several roles in Doctor Who, including companion Sara Kingdom.',
   'colony': 'Colony in Space is a third Doctor story.',
   'woman': 'The Woman who Lived and the Woman who Fell to Earth are both Doctor Who stories.',
   'maren': 'Maren is leader of the Sisterhood of Karn in The Brain of Morbius.',
   'voyage': 'Voyage of the Damned is a tenth Doctor story.',
   'cybus': 'Cybus Industries creates the Cybermen in Rise of the Cybermen and The Age of Steel.',
   'munro': 'Rona Munro wrote Survival the final story in the original run of Doctor Who.  She is the only writer to have written for both the classic and the new series.',
   'zhukov': 'Captain Zhukov commands the submarine in Cold War.',
   'timey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'vardy': 'The Nano-bot Vardy are the monsters in Smile.',
   'sonic': 'The Doctor often uses the Sonic Screwdriver to get out of scrapes.',
   'arthur': 'Arthur Darvill played companion Rory Williams.',
   'stien': 'Stien betrays the Doctor in Resurrection of the Daleks.',
   'malus': 'The Malus is the evil beneath the Church in The Awakening.',
   'wrack': 'Captain Wrack is the villain in Enlightnement.',
   'gebek': 'Gebek leads the miners in The Monster of Peladon.',
   'solar': 'The villainous Mavic Chen is Guardian of the Solar System.',
   'vater': 'Vater is a title in the Anglican Army that appears in Boom.',
   'wright': 'Barbara Wright was a companion to the first Doctor.',
   'wenger': 'Piers Wenger was an executive producer of Doctor Who.',
   'wrarth': 'The Wrath Warriors are monsters in The Star Beast.',
   'gibson': 'Millie Gibson played companion Ruby Sunday.',
   'gilles': 'In the King\'s Demons, the Master disguises himself as Sir Gilles Estram.',
   'novice': 'Novice Hame is a Cat Nun who appears in New Earth and Gridlock.',
   'solow': 'Ingrid Pitt plays the villainous Doctor Solow in Warriors of the Deep.',
   'kroll': 'Kroll is a giant squid from The Power of Kroll.',
   'guitar': 'The Twelfth Doctor often played a guitar.',
   'keller': 'The Keller machine holds the Mind of Evil.',
   'ganger': 'The Gangers are human controlled Doppelgangers created from the Flesh.',
   'circle': 'Full Circle is a fourth Doctor story.',
   'damned': 'Voyage of the Damned is a tenth Doctor story.',
   'saint': 'The Bells of Saint John is an Eleventh Doctor story.',
   'levene': 'Jon Levene played UNIT sergeant Benton.',
   'saxon': 'Harold Saxon is the alias adopted by the Master in the Tenth Doctor\'s second series.',
   'devil': 'The Sea Devils are relatives of the Silurians.',
   'teller': 'In Time Heist the Doctor and his friends rescue The Teller.',
   'lived': 'The Woman who Lived is a Twelfth Doctor story.',
   'jenny': 'Jenny is the Doctor\'s Daughter.',
   'lurman': 'Vorg and Shirna in Carnival of Monsters are Lurmans.',
   'rorvik': 'Rorvik is the villain in Warriors\' Gate.',
   'carol': 'A Christmas Carol is an Eleventh Doctor story.',
   'souza': 'Lady Christina de Souza acts as the companion in Planet of the Dead.',
   'eocene': 'A period of Earth\'s history from which the Silurians probably didn\'t originate and so they shouldn\'t be called Eocenes either.',
   'sixth': 'The Sixth Doctor was played by Colin Baker.',
   'finch': 'Mr Finch is the villain in School Reunion.',
   'derek': 'There have been lots of Dereks associated with Doctor Who, including Derek Ware who founded the stunt team HAVOC and Derek Jacobi who played the Master',
   'idris': 'Idris is a personification of the Tardis in The Doctor\'s Wife.',
   'nyssa': 'Nyssa was a companion of the Fourth and Fifth Doctors.',
   'sally': 'Sally Sparrow is the protagonist of Blink.',
   'quill': 'Mr Quill is a servant of the seaweed in Fury from the Deep.',
   'eldrad': 'Eldrad is the villain in The Hand of Fear.',
   'pangol': 'Pangol is the villain in The Leisure Hive.',
   'terry': 'Terry Nation created the Daleks.',
   'meglos': 'Meglos is a fourth Doctor story.',
   'zarbi': 'The Zarbi were monters appearing in the The Web Planet.',
   'golden': 'Operation Golden Age are trying to turn back time in Invasion of the Dinosaurs.',
   'diane': 'Diane is Dan Lewis\' girlfriend.',
   'games': 'The War Games is a Third Doctor story.',
   'fisher': 'The Fisher King is the monster in Before the Flood.',
   'robson': 'Robson is in charge of the gas refinery in Fury from the Deep.',
   'madge': 'Madge Arwell is the Widow in the Doctor, the Widow and the Wardrobe.',
   'stones': 'The Stones of Blood is a fourth Doctor story.',
   'sense': 'The Sense Sphere is home to the Sensorites.',
   'isaac': 'Isaac Newton appears (briefly) in Wild Blue Yonder.',
   'attack': 'Attack of the Cybermen is a sixth Doctor story.',
   'museum': 'The Space Museum is a first Doctor story.',
   'marius': 'Professor Marius created K9',
   'power': 'The Power of the Daleks, The Power of Kroll and The Power of Three are all Doctor Who stories.',
   'lalla': 'Lalla Ward played Romana, companion to the Fourth Doctor.',
   'rings': 'The Rings of Akhaten is an Eleventh Doctor story.',
   'baker': 'Tom Baker played the Fourth Doctor and Colin Baker played the Sixth Doctor.',
   'vworp': 'Allegedly the Tardis goes Vworp Vworp when it materialises.',
   'goblin': 'Goblins are the enemy in The Church on Ruby Road.',
   'dragon': 'Dragonfire, the Key to the Iceworld space ship, is protected inside the Dragon\'s head.',
   'claus': 'Santa Claus appears in Last Christmas.',
   'alaya': 'Alaya is a Silurian in the The Hungry Earth and Cold Blood.',
   'sutekh': 'Sutekh the Destroyer is the villain in Pyramids of Mars.',
   'finney': 'Yasmin Finney will play Rose in the Doctor Who specials in 2023.',
   'giggle': 'The Giggle is a Fourteenth Doctor story.',
   'tissue': 'The Master\'s signature weapon is the Tissue Compression Eliminator.',
   'ergon': 'The Ergon is a monster that appears in Arc of Infinity.',
   'yartek': 'Yartek is leader of the alien Voord.',
   'choice': 'Amy\'s Choice is an eleventh Doctor story.',
   'behind': 'Doctor Who is traditionally watched from Behind the Sofa.',
   'mccoy': 'Sylvester McCoy played the Seventh Doctor.',
   'monoid': 'The Monoids are the monsters in The Ark.',
   'edison': 'Thomas Edison appears as an antagonist in Nikola Tesla\'s Night of Terror.',
   'thura': 'Zolfa Thura is the home planet of Meglos.',
   'borusa': 'Borusa is a high ranking Time Lord, former tutor of the Doctor and ultimately the villain in the Five Doctors.',
   'cherub': 'Cherub versions of the Weeping Angelas appear in The Angels Take Manhattan.',
   'viking': 'The Meddling Monk tries to alter history in the Time Meddlar by defeating the Viking invasion by Harald Hardrada using a missile.',
   'cusick': 'Ray Cusick was responsible for the iconic Dalek design.',
   'sethu': 'Varada Sethu will play a new companion in the 2025 season.',
   'source': 'The Source is a terraforming device in The Doctor\'s Daughter.',
   'caves': 'The Caves of Androzani is a Fifth Doctor story.',
   'morax': 'The Morax are the villains in The Witchfinders.',
   'poosh': 'The Lost Moon of Poosh, mentioned in Midnight is one of the stolen planets in The Stolen Earth.',
   'robert': 'Robert Holmes script-edited Doctor Who.',
   'puddle': 'Bill\'s girlfriend Heather is taken over by puddle of sentient engine oil.',
   'james': 'King James I of England and VI of Scotland appears in The Witchfinders.',
   'havoc': 'HAVOC was a team of stuntmen that provided action scenes for many Third Doctor episodes.',
   'moment': 'The Doctor contemplates using the Moment to end the Time War.',
   'orient': 'Mummy on the Orient Express is a twelfth Doctor story.',
   'tomtit': 'TOMTIT is a device for manipulating time in The Time Monster.',
   'mcgann': 'Paul McGann played the Eighth Doctor.',
   'tesla': 'Nikola Tesla\'s Night of Terror is a Thirteenth Doctor story.',
   'blitz': 'The Empty Child and the Doctor Dances take place during the London Blitz.',
   'myrka': 'The Myrka is a beast controlled by the Silurians and Sea Devils in Warriors of the Deep.',
   'manish': 'Manish is the antagonist in Demons of the Punjab.',
   'daleks': 'The Daleks are the Doctor\'s arch enemies and first appear in The Daleks.',
   'prison': 'The Doctor spends a long time in Prison, most notably between The Timeless Children and Revolution of the Daleks.',
   'marter': 'Ian Marter played companion Harry Sullivan.',
   'smith': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.  Matt Smith played the Eleventh Doctor.',
   'theta': 'The Doctor\'s nickname at the Time Lord academy was Theta Sigma.',
   'father': 'Father\'s Day is a ninth Doctor story.',
   'smiler': 'The Winders were the police force of Starship UK.  They were half-human half-Smiler cyborgs.',
   'ncuti': 'Ncuti Gatwa plays the Fifteenth Doctor.',
   'sphere': 'The Sense Sphere (from the Sensorites) and the Ood Sphere (from Planet of the Ood) are both planets.',
   'binro': 'Binro is a heretic on Ribos because of his belief in life in the stars.',
   'black': 'Black Orchid and The Curse of the Black Spot are both Doctor Who stories.',
   'forced': 'In Power of the Doctor the Master uses a forced regeneration to steal the Doctor\'s body.',
   'vinder': 'Vinder was a recurring character in Flux.',
   'skagra': 'Skagra is the villain in the untransmitted story Shada.',
   'hitler': 'Let\'s Kill Hitler is an eleventh Doctor story.',
   'thoros': 'Mindwarp takes place on Thoros Beta.',
   'undead': 'Mawdryn Undead is a fifth Doctor story.',
   'cicero': 'Eve Cicero is a renowned general who dies to save the Tsuranga in The Tsuranga Conundrum.',
   'innes': 'Innes Lloyd was a Doctor Who producer.',
   'aukon': 'Aukon is one of the Three Who Rule, villains in State of Decay.',
   'shadow': 'The Shadow Proclamation are a universal police force.',
   'enemy': 'The Enemy of the World and The Invisible Enemy are both Doctor Who stories.',
   'karkus': 'The Karkus was a fictional superhero from Zoe\'s time who appears as a character in The Mind Robber.',
   'byron': 'Lord Byron appears in the Haunting of Villa Diodati.',
   'ohila': 'Ohila is the leader of the Sisterhood of Karn in Night of the Doctor, The Magician\'s Apprentice and Hell Bent.',
   'reaper': 'The Reapers appear where paradoxes arise.',
   'murray': 'Murray Gold composed Doctor Who\'s incidental music from the start of the ninth Doctor\'s episodes to the end of the twelfth.',
   'three': 'The Three Doctors, World War Three and the Power of Three are all Doctor Who stories.',
   'third': 'Jon Pertwee played the Third Doctor.',
   'davis': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'mundy': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'beacon': 'The Nerva Beacon space station features in several stories in Tom Baker\'s first season.',
   'mackie': 'Pearl Mackie played companion Bill Potts.',
   'giant': 'The Doctor has faced Giant Rats, Giant Crabs and Giant Robots among other menaces.',
   'titan': 'Titan Base is taken over by a sentient virus in The Invisible Enemy',
   'lucas': 'Matt Lucas played companion Nardole.',
   'dorium': 'Dorium Maldovar was a somewhat unwilling ally of the eleventh Doctor.',
   'broton': 'Broton is the leader of the Zygons in Terror of the Zygons.',
   'agatha': 'The Doctor meets Agatha Christie in the Unicorn and the Wasp.',
   'rutans': 'The Rutans are the enemies of the Sontarans.',
   'rigsy': 'Rigsy appears in Flatline and Face the Raven.',
   'puzano': 'Belle leaves a message for Vinder on Puzano in Village of the Angels.',
   'yonder': 'Wild Blue Yonder is a Fourteenth Doctor Story.',
   'sugar': 'In The Moonbase, the Cybermen poison the sugar.',
   'hulke': 'Malcolm Hulke wrote many episodes of Doctor Who and co-write The Making of Doctor Who with Terrance Dicks.',
   'fires': 'The Fires of Pompei is a Tenth Doctor story.',
   'ffinch': 'Polly kidnaps Lt. Algernon Ffinch in The Highlanders.',
   'dukkha': 'Dukkha is a representation of the Mara in Kinda.',
   'ianto': 'Ianto Jones was a series regular in the Torchwood Doctor Who spin-off and also appeared in The Stolen Earth and Journey\'s End.',
   'maxil': 'Commander Maxil is a Time Lord played by future Doctor, Colin Baker.',
   'wimey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'ohica': 'Ohica is a member of the Sisterhood of Karn in The Brain of Morbius.',
   'zanak': 'Zanak is the Pirate Planet.',
   'missy': 'Missy is the Doctor\'s arch enemy.',
   'night': 'Night Terrors, In the Forest of the Night and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'madame': 'The Girl in the Fireplace is about Madame de Pompadour.',
   'kaled': 'The Daleks are mutated Kaleds.',
   'flesh': 'Flesh and Stone and The Rebel Flesh are both Eleventh Doctor stories.',
   'terror': 'The Reign of Terror, The Macra Terror, Terror of the Autons, Terror of the Zygons, Terror of the Vervoids, and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'orchid': 'Black Orchid is a fifth Doctor story.',
   'siren': 'The malfunctioning medical system in The Curse of the Black Spot was considered a Siren by the pirates.',
   'nature': 'Human Nature is a tenth Doctor story.',
   'xerons': 'The Xerons appear the The Space Museum.',
   'taren': 'Taren Capel is the villain in The Robots of Death',
   'atmos': 'ATMOS, short for Atmospheric Omission System, was a device created by the Sontarans to convert the Earth into a Sontaran Hatchery.',
   'flight': 'Time-Flight is a fifth Doctor story.',
   'thalia': 'Chancellor Thalia is a Time Lord in Arc of Infinity.',
   'tegana': 'Tegana is the villain in Marco Polo.',
   'optera': 'The Optera are caterpillar-like relatives of the Menoptera in the Web Planet.',
   'crack': 'The Eleventh Doctor\'s first series is plagued by cracks in time and space.',
   'estate': 'Tooth and Claw takes place on the Torchwood Estate.',
   'medusa': 'The Daleks move 27 planets to the Medusa Cascade in The Stolen Earth.',
   'cilla': 'Cilla Black appears in The Devil\'s Chord.',
   'bells': 'The Bells of Saint John is an Eleventh Doctor story.',
   'xeron': 'The Tardis visits the planet Xeros in The Space Museum and helps the Xerons gain freedom from the oppressive Moroks.',
   'axons': 'The Axons are the monsters in The Claws of Axos.',
   'adams': 'Douglas Adams was a script editor on Doctor Who.',
   'harold': 'Harold Saxon is the Master in disguise.',
   'vicki': 'Vicki was a companion of the first Doctor.',
   'zargo': 'Zargo is one of the Three Who Rule, villains in State of Decay.',
   'biasco': 'Professor Hobbes and his student Dee Dee Biasco are two of the shuttle passengers in Midnight.',
   'rutan': 'The Rutans are the deadly enemies of the Sontarans.',
   'vacuum': 'Travel between E-Space and N-Space is possible through Charged Vaccuum Emboitments.',
   'monks': 'The Meddling Monk, the Headless Monks and the Monks have all opposed the Doctor.',
   'gillan': 'Karen Gillan played companion Amy Pond.',
   'rosita': 'Rosita Farisi is Jackson Lake\'s companion in the Next Doctor.',
   'seeds': 'The Seeds of Death and the Seeds of Doom are both Doctor Who stories.',
   'yates': 'Captain Mike Yates was a regular character during the UNIT years.',
   'ogron': 'The Ogrons appeared as servants to the Daleks in Day of the Daleks and Frontier in Space.',
   'qurunx': 'The Qurunx is an energy being enslaved by the Master in The Power of the Doctor.',
   'kembel': 'Kembel is the planet where the Daleks assemble their alliance in the Daleks\' Masterplan.',
   'obrien': 'Graham O\'Brien was a companion to the thirteenth Doctor.',
   'alaska': 'Oswin, one of the fragments of Clara, thought she was a survivor of the crash of the Alaska into the Dalek prison planet.',
   'jungle': 'The Tardis crew find one of the keys to the Conscience of Marinus in the Screaming Jungle.',
   'allons': 'The Tenth Doctor often said Allons-y.',
   'hydrax': 'The Tower of the Lords in State of Decay is actually the spaceship Hydrax.',
   'bland': 'Terrance Dicks used the pseudonum Robin Bland for The Brain of Morbius because he disliked the changes made to his script by the production team.',
   'tharil': 'The Tharils are time sensitives in Warriors\' Gate.',
   'magnus': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'tegan': 'Tegan Jovanka was a companion of the Fourth and Fifth Doctors.',
   'gejelh': 'Merry Gejelh is the child chosen to sing to the Old God of Akhaten in the Rings of Akhaten.',
   'under': 'Under the Lake is a Twelfth Doctor story.',
   'kaldor': 'Kaldor is a desert planet in The Robots of Death.',
   'tahira': 'Tahira helps the Doctor in Can You Hear Me?',
   'giants': 'Planet of Giants was a first Doctor story.',
   'stubbs': 'Stubbs and Cotton are two sympathetic guards in The Mutants.',
   'ramone': 'Ramone is one of River Song\'s husbands in the Husbands of River Song.',
   'helix': 'The Mandragora Helix is the enemy in the Masque of Mandragora.',
   'osiris': 'Phaester Osiris is the home planet of the Osirans.',
   'dandy': 'The First Doctor described the Second and Third Doctors as a dandy and a clown.',
   'repose': 'Revelation of the Daleks is set on the planet Necros in the funeral home Tranquil Repose.',
   'wheel': 'The Wheel is a space station where the Doctor met his companion Zoe.',
   'chance': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'vanir': 'The Vanir work on the Terminus in the Fith Doctor episode Terminus.',
   'voord': 'The alien Voord were the monsters in the Keys of Marinus.',
   'martha': 'Martha Jones was a companion to the tenth Doctor.',
   'shoals': 'In The Return of Doctor Mysterio, the Doctor is investigating the company Harmony Shoals.',
   'vortex': 'The Tardis travels through the Time Vortex.',
   'wraith': 'Wraiths inhabit the catacombs on Galligrey.',
   'child': 'The Doctor is the Timeless Child.',
   'hecate': 'Nightmare of Eden involes a collision between the space ships Empress and Hecate.',
   'morpho': 'The Morpho are a disemboided brain-like creature who ruled the city of Morphoton on Marinus.',
   'sarff': 'Colony Sarff was a servant of Davros in The Magician\'s Apprectice and the Witch\'s Familiar.',
   'totter': 'In the first episode the Tardis is in Totter\'s Yard.',
   'heriot': 'Zoe Heriot was a companion to the second Doctor.',
   'mavity': 'In Wild Blue Yonder the Doctor and Donna accidentally change thework Gravity to Mavity.',
   'watch': 'Time Lords seem to frequently hide their memories in pocket watches.',
   'vogan': 'The Vogans are the inhabitants of the planet Voga in Revenge of the Cybermen.',
   'foster': 'Mrs Foster is the Adipose Nanny in Partners in Crime.',
   'jones': 'Martha Jones was a companion of the Tenth Doctor.',
   'clegg': 'Professor Clegg is an unwilling psychic in Planet of the Spiders.',
   'brown': 'Peri Brown was a companion of the Fifth and Sixth Doctors.',
   'graham': 'Graham O\'Brien was a companion to the thirteenth Doctor.',
   'crater': 'The Menoptera were kept prisoners by the Zarbi in the Crater of Needles.',
   'almost': 'The Almost People is an eleventh Doctor story.',
   'wester': 'We first meet the Weeping Angels in an abandoned house in Wester Drumlins.',
   'grand': 'The Grand Serpent helped found and then disassemble UNIT.',
   'nuton': 'The Nuton Power Complex is blown up by the Axons in the Claws of Axos.',
   'light': 'Light is one of the villains in Ghost Light.',
   'harry': 'Harry Sullivan was a companion of the Fourth Doctor.',
   'craze': 'Michael Craze played Ben, companion to the First and Second Doctors.',
   'magpie': 'The Wire operates out of Magpie Electronics in The Idiot\'s Lantern.',
   'faith': 'Faith can be used to hold back haemovores, but it also feeds the creature in the God Complex.',
   'tivoli': 'Tivoli is the most invaded planet in the galaxy.',
   'mercy': 'A Town called Mercy is an Eleventh Doctor story.',
   'yvonne': 'Yvonne Hartman leads Torchwood in Army of Ghosts and Doomsday.',
   'moffat': 'Steven Moffat was the showrunner for the eleventh and twelfth Doctor series.',
   'forest': 'Forest of the Dead and In the Forest of the Night are both Doctor Who stories.',
   'second': 'The Second Doctor was played by Patrick Troughton.',
   'temple': 'Donna marries Sean Temple.',
   'earth': 'Lots of stories are set on the planet Earth.',
   'turner': 'John Nathan-Turner was a Doctor Who producer.',
   'piers': 'Piers Wenger was an executive producer of Doctor Who.',
   'sharon': 'Amy Pond is raised by her Aunt Sharon after her parents disappear into the crack in her wall.',
   'daphne': 'Daphne Ashbrook played companion Grace.',
   'martin': 'Jo Martin plays the Fugitive Doctor in Fugitive of the Judoon.',
   'shada': 'Shada is an unbroadcast episode of Doctor Who.',
   'orion': 'The Fifth Doctor often tried to get to the Eye of Orion, succeeding in The Five Doctors.',
   'erisa': 'Captain Erisa Magambo is a UNIT Captain who appears in Turn Left and Planet of the Dead.',
   'jacobi': 'Derek Jacobi played Professor Yana who was revealed as the Master.',
   'zaroff': 'Zaroff is the villain in The Underwater Menace.  He got to say \'Nothing the the World can stop me now!\'',
   'ninth': 'The Ninth Doctor was played by Christopher Eccleston.',
   'sorin': 'Captain Sorin is a love interest for Ace in The Curse of Fenric.',
   'dalek': 'The Daleks are the show\'s most famous monster.',
   'cheem': 'Home of the Forest of Cheem from The End of the World.',
   'nitro': 'Ace often blew things up with Nitro Nine.',
   'circus': 'The Doctor and Ace visit the Psychic Circus in The Greatest Show in the Galaxy.',
   'sunday': 'Millie Gibson will played companion Ruby Sunday.',
   'sauvix': 'Sauvix is the Sea Devil leader in Warriors of the Deep.',
   'fifth': 'The Fifth Doctor was played by Peter Davison.',
   'audrey': 'Ace\'s mother was called Audrey.  Ace met her as a baby in The Curse of Fenric.',
   'villa': 'The Haunting of Villa Diodati is a Thirteenth Doctor story.',
   'huasen': 'The Huasen is a massive sea beast used by the Sea Devils in Legend of the Sea Devils.',
   'clown': 'The Chief Clown is a villian in The Greatest Show in the Galaxy.',
   'simeon': 'Dr Simeon is taken over by the Great Intelligence in The Snowmen which continues to use his body in The Name of the Doctor.',
   'gomez': 'Michelle Gomez played Missy.',
   'cherry': 'Carla Sunday is Ruby\'s grandmother.',
   'punjab': 'Demons of the Punjab is a thirteenth Doctor story.',
   'lewis': 'Dan Lewis is a companion of the Thirteenth Doctor.',
   'dances': 'The Doctor Dances is a ninth Doctor story.',
   'angel': 'The Weeping Angels are a popular Doctor Who Monster.',
   'twist': 'There is always a twist at the end.',
   'bonnie': 'Bonnie Langford played companion Mel Bush.',
   'xanxia': 'Queen Xanxia is one of the villains in The Pirate Planet.',
   'graff': 'Graff Vynda-K is the villain in the Ribos Operation.',
   'times': 'The regeneration of the Tenth Doctor into the Eleventh is prophesied by He will Knock Four Times.',
   'thorn': 'Leela is initially very keen on killing people with Janis Thorns.',
   'sidrat': 'The SIDRAT\'s were the War Lord\'s time and space machines in The War Games.',
   'reimer': 'Kartz and Reimer\'s time travel experiments cause the Time Lords to send the Doctor and Jamie to intervene in The Two Doctors.',
   'karra': 'Karra is a Cheetah person who befriends Ace in Survival.',
   'brave': 'The Fifth Doctor often urged Tegan to have a brave heart.',
   'static': 'In The Daleks the Daleks need static electricty to move.  In Evil of the Daleks Maxtible and Waterfield accidentally bring the Daleks to Earth when trying to invent a time machine using mirrors and static electricity.',
   'fariah': 'Fariah is the villain Salamander\'s food taster in Enemy of the WOrld.  She is killed helping Jamie and Victoria escape.',
   'lilith': 'Lilith is the main Carrionite in The Shakespeare Code.',
   'hepesh': 'Hepesh is the high priest of Peladon in The Curse of Peladon.',
   'skulls': 'The Tardis crew are held captive in the Cave of Skulls in An Unearthly Child.',
   'pocket': 'In Human Nature and Family of Blood the Doctor transfers his Time Lord essence into a Pocket Watch.',
   'wings': '"Chap with wings.  Five Rounds Rapid." was said by the Brigadier.',
   'josiah': 'Josiah Smith seeks to assassinate Queen Victoria in Ghost Light.',
   'robot': 'Robot and Robot of Sherwood are both Doctor Who stories.',
   'chula': 'A Chula medical transport causes all the trouble in The Empty Child/The Doctor Dances.',
   'gavrok': 'Gavrok leads the Bannermen in Delta and the Bannermen.',
   'shallo': 'Shallo is a Sontaran in The Vanquishers.  He is caught looting a corner shop for chocolate by the Fam.',
   'minyan': 'The Minyans come from Minyos.',
   'empire': 'Empire of Death is a Fifteenth Doctor story.',
   'andred': 'Leela, rather implausbily, leaves the Doctor to marry Andred.',
   'winder': 'The Winders were the police force of Starship UK.  They were half-human half-Smiler cyborgs.',
   'enough': 'World Enough and Time is a twelfth Doctor story.',
   'icthar': 'Icthar is the Silurian leader in Warriors of the Deep.',
   'nerada': 'The Vashta Nerada are the monsters in Silence in the Library and Forest of the Dead.',
   'waris': 'Waris Hussein was Doctor Who\'s first director.',
   'vashta': 'The Vashta Nerada are the monsters in Silence in the Library and Forest of the Dead.',
   'siege': 'The Time of the Doctor is about the Siege of Trenzalore.',
   'tooth': 'Tooth and Claw is a Tenth Doctor episode.',
   'stike': 'Stike is a Sontaran in The Two Doctors.',
   'shade': 'A Quantum Shade takes the form of a raven and deals out justice in Face the Raven.',
   'claws': 'The Claws of Axos is Third Doctor Who story.',
   'ortron': 'Ortron is Chancellor of Peladon in The Monster of Peladon.',
   'atraxi': 'The Atraxi appear in The Eleventh Hour.',
   'system': 'Mavic Chen is Guardian of the Solar System.',
   'sound': 'The Sound of Drums is a Tenth Doctor story.',
   'vardan': 'The Vardans invade Gallifrey in The Invasion of Time.',
   'mccall': 'Davina McCall appears as herself in The Church on Ruby Road.',
   'purves': 'Peter Purves played companion Steven Taylor.',
   'betan': 'The Thal woman Betan helps the Doctor in Genesis of the Daleks.',
   'yards': '73 Yards is a Fifteenth Doctor story.',
   'potts': 'Bill Potts was a companion to the Twelfth Doctor.',
   'solon': 'Doctor Solon is the villain in The Brain of Morbius.',
   'kaleds': 'The Daleks are mutated Kaleds.',
   'walsh': 'Bradley Walsh played companion Graham O\'Brien.',
   'joanna': 'Jean Marsh plays Richard the Lionheart\'s sister Joanna in The Crusade.',
   'shooty': 'K9 is referred to as the Shooty Dog Thing in School Reunion.',
   'curse': 'The Curse of Peladon, The Curse of Fenric, and the Curse of the Black Spot are all Doctor Who stories',
   'zondal': 'Zondal is an Ice Warrior in The Ice Warriors.',
   'kizlet': 'Miss Kizlet is the front for the Great Intelligence in the Bells of St. John.',
   'angels': 'The Time of Angels, The Angels Take Manhattan and Village of the Angels are all Doctor Who stories.',
   'global': 'Global Chemicals is the source of the contamination that causes the Green Death.',
   'mouri': 'The Mouri are the gatekeepers of the Temple of Atropos.',
   'gordon': 'Alister Gordon Lethbridge-Stewart is the Brigadier\'s full name.',
   'memory': 'In Empire of Death, The Doctor, Ruby and Mel take refuge in a Memory Tardis.',
   'matrix': 'The Matrix on Gallifrey holds the combined knowledge of the Time Lords.',
   'mavic': 'Mavic Chen is the villain in The Daleks\' Masterplan.',
   'frost': 'Thin Ice takes place at a Frost Fair on the Thames.',
   'bryant': 'Nicola Bryant played companion Peri Brown.',
   'sirius': 'Sirius IV is mentinoed in Frontier in Space and Sirius V in City of Death.',
   'gelth': 'The Gelth are the villians in The Unquiet Dead.',
   'raaga': 'Raaga is the penal planet of the Tereleptils.',
   'tardis': 'The TARDIS is the Doctor\'s space and time machine.',
   'elders': 'The Elders govern the parasitic civilisation in The Savages.',
   'magma': 'The Magma Beast appeared in The Caves of Androzani.',
   'opens': 'The Pandorica Opens is an Eleventh Doctor story.',
   'truth': 'Truth or Consequences is a town occupied by Zygons in The Zygon Invasion.',
   'build': 'The Kangs in Paradise Towers use the phrase Build High for Happiness.',
   'doris': 'Doris is the Brigadier\'s wife in Battlefield.',
   'jensen': 'Rachel Jensen is scientific advisor to the Intrusion Counter Measures group in Rememberance of the Daleks.',
   'baird': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'skaro': 'Skaro is the Dalek planet.',
   'minor': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'minyos': 'The planet Minyos was destroyed after the Time Lords interfered with its development.',
   'zombie': 'Time Zombies appear in Journey to the Centre of the TARDIS.',
   'tenza': 'The boy, George, in Night Terrors is really a Tenza.',
   'house': 'House is the villain in The Doctor\'s Wife.',
   'carla': 'Carla Sunday is Ruby\'s mother.',
   'demons': 'The King\'s Demons and Demons of the Punjab are both Doctor Who stories.',
   'takes': 'It Takes You Away is a Thirteenth Doctor story.',
   'zocci': 'Bannakaffalatta from Voyage of the Damned was a Zocci.',
   'maddox': 'Judy Maddox is the head of human resources at Kerblam.',
   'oliver': 'Ingrid Oliver plays Osgood - UNIT Scientist and Zygon.',
   'robber': 'The Mind Robber is a second Doctor story.',
   'spiral': 'Mutter\'s Spiral seems to be a synonym for the Milky Way.',
   'rogue': 'Rogue is a Fifteenth Doctor story.',
   'mandip': 'Mandip Gill played companion Yaz Khan.',
   'trial': 'Trial of a Time Lord is the over-arching title of the Sixth Doctor\'s second season.',
   'triton': 'Triton is a city on Neptune.  The soldiers in Sleep No More are sent from there.',
   'stenza': 'Tzim-Sha in the Woman who Fell to Earth is a Stenza.',
   'aldred': 'Sophie Aldred played companion Ace.',
   'kolos': 'The Battle of Ranskoor Av Kolos is a Thirteenth Doctor story.',
   'leela': 'Leela was a companion to the Fourth Doctor.',
   'babies': 'Space Babies is a Fifteenth Doctor story.',
   'cutler': 'General Cutler is the leader of Snowcap Base in The Tenth Planet.',
   'horus': 'The Eye of Horus held Sutekh prisoner on Earth.',
   'romana': 'Romana was a companion to the fourth Doctor.',
   'plant': 'There are many dangerous plants in Doctor Who, such as the Varga plants and the Krynoids.',
   'larvae': 'The Zarbi used Larvae guns in The Web Planet.',
   'heaven': 'Death in Heaven and Heaven Sent are both Doctor Who stories.',
   'menace': 'The Underwater Menace is a second Doctor story.',
   'jackie': 'Jackie Lane played companion Dodo Chaplet.',
   'flint': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'hybrid': 'There is a Gallifreyan Prophesy that a hybrid creature would stand over the ruins of Gallifrey and unravel the Web of Time.  The creature is referred to as The Hybrid.',
   'ghost': 'Ghost Light and The Ghost Monument are both Doctor Who stories.',
   'parks': 'The Doctor Who story Rosa is about activist Rosa Parks.',
   'rheum': 'The Sandmen monsters in Sleep No More are made from rheum.',
   'tenth': 'Mondas, home of the Cybermen, was once the tenth planet in the Earth\'s solar system (according to Doctor Who).',
   'mirror': 'Mirrors form the interface between E-Space and N-Space in Warriors\' Gate.',
   'rills': 'The Rills were aliens in Galaxy Four.',
   'ingrid': 'Ingrid Oliver plays Osgood - UNIT Scientist and Zygon.',
   'death': 'The Seeds of Death, The Ambassadors of Death, The Green Death, Death to the Daleks, The Robots of Death, City of Death, Death in Heaven, and Empire of Death are all Doctor Who stories.',
   'galaxy': 'Galaxy 4 and The Greatest Show in the Galaxy are both Doctor Who stories.',
   'animus': 'The Animus is the enemy in the Web Planet.',
   'major': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'laszlo': 'Laszlo is Tallulah\'s missing boyfriend in Daleks in Manhattan.  He has been transformed into a pig man.',
   'powell': 'Rose and her Mum live on the Powell Estate.',
   'oxygen': 'Oxygen is a twelfth Doctor story.',
   'kraals': 'The Kraals appear in The Android Invasion.',
   'dhawan': 'Sacha Dhawan played the Master opposite Jodie Whittaker\'s Doctor.',
   'fudge': 'Fudge is a friend of Rose Noble in The Star Beast.  He plays a more prominent role in the comic the story is based on.',
   'inayat': 'The Doctor meets Noor Inayat Khan in Spyfall.',
   'jodie': 'Jodie Whittaker played the Thirteenth Doctor.',
   'beast': 'The Beast Below is an Eleventh Doctor story and the Star Beast is a Fourteenth Doctor story.',
   'kalid': 'Kalid is a disguise adopted by the Master in Time-Flight.',
   'clone': 'The Doctor\'s Daughter is created using a form of cloning technology.',
   'awsok': 'Awsok was an alias used by Tecteun who considered herself the Doctor\'s mother.',
   'karfel': 'The Doctor and Peri visit Karfel in Timelash.',
   'melody': 'Amy and Rory name their daughter Melody.',
   'uvanov': 'Uvanov is commander of the Sandminer in Robots of Death.',
   'called': 'A Town Called Mercy is an eleventh Doctor story.',
   'kassia': 'Kassia is Nyssa\'s step-mother and pawn of the Master in The Keeper of Traken.',
   'sharaz': 'Sharaz Jek is the tragic villain in The Caves of Androzani.',
   'clever': 'Run you clever boy and remember me.',
   'dryad': 'Dryad beetles are the monsters in Knock Knock.',
   'ballad': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'canary': 'The Battle of Canary Wharf between the Daleks and the Cybermen takes place during Doomsday.',
   'osiran': 'Sutekh from the Pyramids of Mars is an Osiran.',
   'river': 'River Song is the Doctor\'s wife.',
   'donald': 'Donald Tosh script-edited Doctor Who.',
   'bysshe': 'The Doctor meets Percey Bysshe Shelley in the The Haunting of Villa Diodati.',
   'nimrod': 'Nimrod is a neanderthal acting as a manservant in Ghost Light.',
   'piper': 'Billie Piper played Rose Tyler, companion.',
   'sacha': 'Sacha Dhawan played The Master during the Thirteenth Doctor series.',
   'vastra': 'Madame Vastra is a Silurian who leads the Paternoster Gang.',
   'walker': 'In the TV Movie the Doctor is taken to Walker General Hospital.',
   'louvre': 'The City of Death involves the theft of the Mona Lisa from the Louvre.',
   'hobbes': 'Professor Hobbes and his student Dee Dee Biasco are two of the shuttle passengers in Midnight.',
   'kraal': 'The Kraals appeared in The Android Invasion.',
   'khalid': 'The Master disguises himself as Khalid in Time Flight.',
   'virus': 'The villain in The Invisible Enemy is a sentient virus.',
   'makers': 'The Myth Makers and the Sun Makers are both Doctor Who stories.',
   'claire': 'Claire is a recurring character in Flux.',
   'usher': 'The Gold Usher is a Time Lord ceremonial position.',
   'julie': 'Julie Gardner was an executive producer on Docor Who.',
   'barton': 'Daniel Barton, played by Lenny Henry is the antagonist in Spyfall.',
   'brooke': 'Adelaide Brooke is a pseudo-companion in The Waters of Mars.',
   'cyber': 'Humans fought many Cyber wars against the Cybermen.',
   'sydney': 'Doctor Who was the brain child of Syndney Newman.',
   'priam': 'King Priam of Troy appears in The Myth Makers.',
   'hiker': 'Susan Twist plays a Hiker in 73 Yards.',
   'lodger': 'The Lodger is an eleventh Doctor story.',
   };
