export const MOREWORDSR: {[key:string]:string } = {
       'arnhost': 'Deputy Marshal Arnhost is a character in The Power of the Doctor.',
       'zogroth': 'Zogroth is a character in The Star Beast.',
       'hinchey': 'Frank Hinchkey is a character in 73 Yards.',
       'deloach': 'Craig Deloach is a character in 73 Yards.',
       'bridges': 'Marti Bridges is a character in 73 Yards.',
       'colbert': 'Leon Colbert is a villain in The Reign of Terror',
       'thomson': 'Thomson is a character in The Dalek Invasion of Earth.',
       'madison': 'Larry Madison is a character in The Dalek Invasion of Earth.',
       'bennett': 'Bennett is the villain in The Rescue.',
       'poppaea': 'Poppaea Sabina is Empress of Rome in the Romans.',
       'ascaris': 'Ascaris is a character in The Romans.',
       'locusta': 'Locusta is the court poisoner in The Romans.',
       'maximus': 'The Doctor is mistaken for the lyre player Maximus Pettulian in the Romans.',
       'vrestin': 'Vrestin is a Menoptra in the Web Planet.',
       'hrostar': 'Hrostar is a Menoptra in the Web Planet.',
       'needles': 'The Menoptera were kept prisoners by the Zarbi in the Crater of Needles.',
       'saladin': 'Saladin appears in The Crusade.',
       'reynier': 'Reynier de Marun is a character in The Crusade.',
       'tornebu': 'William de Tornebu is a character in The Crusade.',
       'ferrigo': 'Luigi Ferrigo is a character in The Crusdae.',
       'maimuna': 'Maimuna is a character in The Crusade.',
       'sheyrah': 'Sheyrah is a character in The Crusade.',
       'lincoln': 'Abraham Lincoln appears briefly in The Chase.',
       'francis': 'Francis Bacon appears briefly in The Chase.',
       'prondyn': 'Prondyn is a character in The Chase.',
       'dracula': 'A robot Count Dracula appears in The Chase.',
       'wulnoth': 'Wulnoth is a character in The Time Meddler.',
       'cyclops': 'Cyclops is a character in The Myth Makers.',
       'karlton': 'Karlton is a character in The Daleks\' Masterplan.',
       'trantis': 'Trantis is a member of the Galatic Council in The Daleks\' Materplan.',
       'kirksen': 'Kirksen is a character in The Daleks\' Masterplan.',
       'rhynmal': 'Rhynmal is a character in The Daleks\' Masterplan.',
       'tranton': 'Darcy Tranton is a character in The Daleks\' Masterplan.',
       'khepren': 'Khepren is a character in The Daleks\' Masterplan.',
       'tuthmos': 'Tuthmos is a character in The Daleks\' Masterplan.',
       'coligny': 'Admiral de Coligny appears in The Massacre.',
       'teligny': 'Teligny is a character in The Massacre.',
       'preslin': 'In THe Massacre the Doctor goes to visit Charles Preslin.',
       'mellium': 'Mellium is a character in The Ark.',
       'maharis': 'Maharis is a character in The Ark.',
       'venussa': 'Venussa is a character in The Ark.',
       'phineas': 'Phineas Clanton is a character in The Gunfighters.',
       'jamaica': 'Jamaica is a character in The Smugglers.',
       'barclay': 'Barclay is a character in The Tenth Planet.',
       'schultz': 'Schultz is a character in The Tenth Planet.',
       'hensell': 'Hensell is a character in The Power of the Daleks.',
       'perkins': 'Characters called Perkins appear in The Highlanders, Fury from the Deep, The Invasion, and Mummy on the Orient Express.',
       'attwood': 'Colonel Attwood is a character in The Highlanders.',
       'meadows': 'Meadows is a character in The Faceless Ones.',
       'spencer': 'Spencer is a character in The Faceless Ones.',
       'jenkins': 'Jenkins is a character in The Faceless Ones.',
       'rinchen': 'Rinchen is a character in the Abominable Snowmen.',
       'garrett': 'Miss Garrett is a character in The Ice Warriors.',
       'walters': 'Walters is a character in The Ice Warriors, The Invasion and Earthshock.',
       'ferrier': 'Astrid Ferrier appears in The Enemy of the World.',
       'fedorin': 'Fedorin is a character in The Enemy of the World.',
       'griffin': 'Griffin the Chef is a character in The Enemy of the World.',
       'chorley': 'Harold Chorley is a character in The Web of Fear.',
       'lutyens': 'Van Lutyens is a character in Fury from the Deep.',
       'watkins': 'Isobel Watkins and her father Professor Watkins appear in The Invasion.',
       'gregory': 'Gregory is a character in The Invasion.',
       'fewsham': 'Fewsham works for the Ice Warriors in The Seeds of Death before regretting his choice.',
       'gregson': 'Gregson is a character in The Seeds of Death.',
       'clancey': 'Milo Clancey is a space prospector in The Space Pirates.',
       'hermark': 'General Hermack is a character in The Space Pirates.',
       'dervish': 'Dervish is a character in The Space Pirates.',
       'hibbert': 'Hibbert is a character in Spearhead from Space.',
       'mullins': 'Mullins is a character in Spearhed from Space.',
       'masters': 'Masters is a character in The Silurians.',
       'hawkins': 'Captain Hawking is a character in The Silurians.',
       'nutting': 'Corporal Nutting is a character in The Silurians.',
       'cornish': 'Ralph Cornish is a character in The Ambassadors of Death.',
       'quinian': 'Sir James Quinian is a character in The Ambassadors of Death.',
       'heldorf': 'Heldorf is a character in The Ambassadors of Death.',
       'rossini': 'In Terror of the Autons, the Master hides in Rossini\'s Circus.',
       'summers': 'Dr Roland Summers is played by Michael Sheard in The Mind of Evil.',
       'linwood': 'Arthur Linwood is a character in The Mind of Evil.',
       'smedley': 'CPO Smedley is a character in The Sea Devils.',
       'hippias': 'Hippias is a character in the Time Monster.',
       'wootton': 'The science institute where the Master is posing as a professor in the Time Monster is in the village of Wootton.',
       'pletrac': 'Pletrac is a character in Carnival of Monsters.',
       'stevens': 'Stevens is a character in The Green Death.',
       'eleanor': 'Lady Eleanor is a character in The Time Warrior.',
       'railton': 'Richard Railton is a character in Death to the Daleks.',
       'tarrant': 'Jill Tarrant is a character in Death to the Daleks.',
       'hopkins': 'Hopkins is a character in Planet of the Spiders.',
       'gharman': 'Gharman is a character in Genesis of the Daleks.',
       'gerrill': 'Gerrill is a character in Genesis of the Daleks.',
       'kellman': 'Kellman appears to be the antagonist in Revenge of the Cybermen.',
       'sheprah': 'Sheprah is a character in Revenge of the Cybermen.',
       'forgill': 'In Terror of the Zygons, the Zygon leader disguises himself as the Duke of Forgill.',
       'salamar': 'Salamar is a character in Planet of Evil.',
       'morelli': 'Morelli is a character in Planet of Evil.',
       'baldwin': 'Baldwin is a character in Planet of Evil.',
       'warlock': 'Dr. Warlock is a character in Pyramids of Mars.',
       'chedaki': 'Chedaki is a Kraal in The Android Invasion.',
       'faraday': 'Colonel Faraday is a character in The Android Invasion.',
       'winlett': 'Charles Winlett is a character in The Seeds of Doom.',
       'chester': 'Doctor Chester is a character in The Seeds of Doom.',
       'martino': 'The Masque of Mandragora is set in San Martino.',
       'herrick': 'Herrick is a character in Underworld.',
       'sholakh': 'Sholakh is a character in The Ribos Operation.',
       'balaton': 'Balaton is a character in The Pirate Planet.',
       'kurster': 'Kurster is a character in The Androids of Tara.',
       'ranquin': 'Ranquin leads the Swampies in the Power of Kroll.',
       'sharrel': 'Commander Sharrel appears in Destiny of the Daleks.',
       'hermann': 'Hermann is a character in City of Death.',
       'organon': 'Organon is a character in Creature from the Pit.',
       'tollund': 'Tollund is a character in Creature from the Pit.',
       'stimson': 'Stimson is a character in The Leisure Hive.',
       'grugger': 'General Grugger is a character in Meglos.',
       'deedrix': 'Deedrix is a character in Meglos.',
       'dexeter': 'Dexeter is a doctor in Full Circle.',
       'packard': 'Packard is a character in Warriors\' Gate.',
       'monitor': 'The Monitor is a character in Logopolis.',
       'sanders': 'Sanders is a character in Kinda.',
       'markham': 'Sergeant Markham is a character in Black Orchid.',
       'ringway': 'Ringway works for the Cybermen in Earthshock.',
       'stapley': 'Captain Stapley is a character in Time-Flight.',
       'andrews': 'Andrews is a charcter in Time-Flight.',
       'anithon': 'Anithon is a Xeraphin in Time-Flight.',
       'dugdale': 'Dugdale is a character in Snakedance.',
       'valgard': 'Valgard is a character in Terminus.',
       'striker': 'Striker is a character in Enlightenment.',
       'mansell': 'Mansell is a character in Enlightenment.',
       'collier': 'Collier is a character in Enlightenment.',
       'vorshak': 'Vorshak is a character in Warriors of the Deep.',
       'preston': 'Preston is a character in Warriors of the Deep.',
       'hampden': 'Jane Hampden is a character in The Awakening.',
       'timanov': 'Timanov is a character in Planet of Fire.',
       'sorasta': 'Sorasta is a character in Planet of Fire.',
       'krelper': 'Krelper is a character in The Caves of Androzani.',
       'chellak': 'Chellak is the army commander in The Caves of Androzani.',
       'quillam': 'Quillam is a character in Vengeance on Varos.',
       'seville': 'The Two Doctors takes place in Seville.',
       'kendron': 'Kendron is a character in Timelash.',
       'brunner': 'Brunner is a character in Timelash.',
       'bostock': 'Bostock is a character in Revelation of the Daleks.',
       'grigory': 'Grigory is a character in Revelation of the Daleks.',
       'stengos': 'In Revelation of the Daleks the Doctor visits Tranquil Repose because of his friend Stengos.',
       'merdeen': 'Merdeen is a character in The Mysterious Planet.',
       'balazar': 'Balazar is a character in The Mysterious Planet.',
       'lukozer': 'King Yrcanos\' equerry, Dorf is referred to as The Lukoser after he is experimented upon in Mindwarp.',
       'matrona': 'Matrona Kani is a character in Mindwarp.',
       'fantasy': 'The Fantasy Factory forms the Valeyard\'s hideout in the Matrix in The Ultimate Foe.',
       'lanisha': 'Lanisha is a character in Time and the Rani.',
       'goronwy': 'Goronwy is a friendly bee-keeper in Delta and the Bannermen.',
       'keillor': 'Keillor is a character in Delta and the Bannermen.',
       'bollitt': 'Bollitt is a character in Delta and the Bannerman.',
       'mcluhan': 'McLuhan is a character in Dragonfire.',
       'arnheim': 'Arnhelm is a character in Dragonfire.',
       'stellar': 'Stellar is a little girl in Dragonfire.',
       'allison': 'Allison is a character in Remembrance of the Daleks.',
       'wulfric': 'Wulfric is a character in The Happiness Patrol.',
       'windsor': 'Silver Nemesis takes place in the environs of Windsor Castle.',
       'bellboy': 'Bellboy is a character in The Greatest Show in the Galaxy.',
       'morgana': 'Morgana is a character in The Greatest Show in the Galaxy.',
       'kingpin': 'Kingpin is a character in The Greatest Show in the Galaxy.',
       'warmsly': 'Peter Warmsly is a character in Battlefield.',
       'ancelyn': 'Ancelyn is a character in Battlefield.',
       'redvers': 'Redvers Fenn-Cooper is a character in Ghost Light.',
       'control': 'Control is the control experiment to Josiah in Ghost Light.',
       'shreela': 'Shreela is a character in Survival.',
       'balhoon': 'Moxx of Balhoon is a character in The End of the World.',
       'raffalo': 'Raffalo is a character in The End of the World.',
       'redpath': 'Redpath is a character in The Unquiet Dead.',
       'cathica': 'Cathica saves the day in The Long Game.',
       'crosbie': 'Crosbie is a character in Bad Wolf.',
       'rodrick': 'Rodrick is a character in Bad Wolf and The Parting of the Ways.',
       'zachary': 'Zachary Cross Flane is a character in The Impossible Planet/The Satan Pit.',
       'manista': 'Scooti Manista is a character in The Impossible Planet/The Satan Pit.',
       'bethlem': 'The Bethlem Hospital appears in The Shakespeare Code.',
       'wiggins': 'Wiggins is a character in The Shakespeare Code.',
       'kincade': 'Thomas Kincade Brannigan is a character in Gridlock.',
       'calypso': 'Sally Calypso is a character in Gridlock.',
       'vashtee': 'Riley Vashtee is a charcter in 42.',
       'torajii': '42 is set in the Torajii system.',
       'kistane': 'Kistane is a character in Utopia.',
       'metella': 'Metalla is a character in The Fires of Pompeii.',
       'quintus': 'Quintus is a charcter in The Fires of Pompeii.',
       'thalina': 'Thalina is a character in The Fires of Pompeii.',
       'evelina': 'Evelina is a character in The Fires of Pompeii.',
       'greeves': 'Greeves is a character in The Unicorn and the Wasp.',
       'sanchez': 'General Sanchez is a character in The Stolen Earth.',
       'scoones': 'Mr Scoones is a character in The Next Doctor.',
       'praygat': 'Praygat is a character in Planet of the Dead.',
       'ehrlich': 'Steffi Ehrlich is a character in The Waters of Mars.',
       'ramsden': 'Dr Ramsden is a character in The Eleventh Hour.',
       'rosanna': 'Rosanna Calvierri is the villain in The Vampires of Venice.',
       'nasreen': 'Nasreen Chaudhry is a character in The Hungry Earth/Cold Blood.',
       'ambrose': 'Ambrose is a character in The Hungry Earth/Cold Blood.',
       'tabetha': 'Tabetha is a character in The Big Bang.',
       'renfrew': 'Dr Renfrew is a character in The Impossible Planet/Day of the Moon.',
       'florres': 'De Florres is a character in The Curse of the Black Spot.',
       'mcgrath': 'McGrath is a character in The Curse of the Black Spot.',
       'cleaves': 'Miranda Cleaves is a character in The Rebel Flesh/The Also People.',
       'purcell': 'Purcell is a character in Night Terrors.',
       'hayward': 'Lucy Hayward is a character in The God Complex.',
       'malokeh': 'Dr Malokeh is a character in The Wedding of River Song.',
       'karlsen': 'Darla von Karlsen is a character in Asylum of the Daleks.',
       'bleytal': 'Bleytal is a character in Dinosaurs on a Spaceship.',
       'dockery': 'Dockery is a character in A Town Called Mercy.',
       'bentham': 'Lord Bentham is a character in Day of the Doctor.',
       'abramal': 'Abramal is a character in Time of the Doctor.',
       'fleming': 'Fleming is a character in Into the Dalek.',
       'delphox': 'Ms Delphox is Madame Karabraxos\' clone in Time Heist.',
       'porrima': 'Mr Porrima is a character in Time Heist.',
       'lundvik': 'Lundvik is a character in Kill the Moon.',
       'forrest': 'PC Forrest is a character in Flatline.',
       'bellows': 'Bellows is a character in Last Christmas.',
       'nollarr': 'Nollar is a character in The Girl who Died.',
       'anahson': 'Anahson is a character in Face the Raven.',
       'quantum': 'The epoynymous Raven in Face the Raven is a Quantum Shade.',
       'gastron': 'Gastron is a character in Hell Bent.',
       'scratch': 'Scratch is a character in The Husbands of River Song.',
       'shireen': 'Shireen is a character in Knock Knock.',
       'dahhren': 'Dahh-Ren is a character in Oxygen.',
       'rafando': 'Rafando is a character in Extremis.',
       'brabbit': 'Colonel Don Brabbit is a character in The Pyramid at the End of the World.',
       'jackdaw': 'Jackdaw is a character in Empress of Mars.',
       'rexhill': 'Rexhill is a character in The Doctor Falls.',
       'twiston': 'Willa and Old Mother Twiston are characters in The Witchfinders.',
       'alfonso': 'Alfonso is a character in The Witchfinders.',
       'andinio': 'Andinio is a character in The Battle of Ranskoor av Kolos.',
       'clayton': 'Lee Clayton appears to be the Fugitive Doctor\'s husband at the start of Fugitive of the Judoon.',
       'solpado': 'Solpado is a character in The Timeless Children.',
       'rugazzi': 'Leo Rugazzi is a scientist working for Jack Robertson who revives the Daleks in Revolution of the Daleks.',
       'ritskaw': 'Ritskaw is a character in The Halloween Apocalypse.',
       'ganatus': 'Ganatus is a thal in The Daleks.',
       'antodus': 'Antodus is a thal in The Daleks.',
       'kristas': 'Kristas is a thal in The Daleks.',
       'chenchu': 'Chenchu is a character in Marco Polo.',
       'sabetha': 'Sabetha is the daughter of Arbitan, Keeper of the Conscience of Marinus.',
       'darrius': 'Darrius is a character in The Keys of Marinus.',
       'webster': 'Webster is a character in The Reign of Terror',
       'rouvray': 'Rouvray is a character in The Reign of Terror',
};


