export const WORDSDICT7: {[key:string]:string } = {
       'ganatus': 'Ganatus is a thal in The Daleks.',
       'antodus': 'Antodus is a thal in The Daleks.',
       'kristas': 'Kristas is a thal in The Daleks.',
       'chenchu': 'Chenchu is a character in Marco Polo.',
       'empress': 'Empress of Mars is a Twelfth Doctor story.',
       'marinus': 'The Keys of Marinus is a first Doctor story.',
       'arbitan': 'Arbitan is the Keeper of the Conscience of Marinus.',
       'sabetha': 'Sabetha is the daughter of Arbitan, Keeper of the Conscience of Marinus.',
       'darrius': 'Darrius is a character in The Keys of Marinus.',
       'tlotoxl': 'Tlotoxl is the antagonist in The Aztecs.',
       'webster': 'Webster is a character in The Reign of Terror',
       'rouvray': 'Rouvray is a character in The Reign of Terror',
       'colbert': 'Leon Colbert is a villain in The Reign of Terror',
       'dortmun': 'Dortmun leads the resistence in The Dalek Invasion of Earth.',
       'thomson': 'Thomson is a character in The Dalek Invasion of Earth.',
       'madison': 'Larry Madison is a character in The Dalek Invasion of Earth.',
       'roboman': 'The Robomen are controlled humans in The Dalek Invasion of Earth.',
       'slyther': 'The deadly Slyther is the Daleks\' pet in The Dalek Invasion of Earth.',
       'bennett': 'Bennett is the villain in The Rescue.',
       'poppaea': 'Poppaea Sabina is Empress of Rome in the Romans.',
       'ascaris': 'Ascaris is a character in The Romans.',
       'locusta': 'Locusta is the court poisoner in The Romans.',
       'maximus': 'The Doctor is mistaken for the lyre player Maximus Pettulian in the Romans.',
       'vrestin': 'Vrestin is a Menoptra in the Web Planet.',
       'hrostar': 'Hrostar is a Menoptra in the Web Planet.',
       'needles': 'The Menoptera were kept prisoners by the Zarbi in the Crater of Needles.',
       'crusade': 'The Crusade is a first Doctor story.',
       'saladin': 'Saladin appears in The Crusade.',
       'reynier': 'Reynier de Marun is a character in The Crusade.',
       'tornebu': 'William de Tornebu is a character in The Crusade.',
       'ferrigo': 'Luigi Ferrigo is a character in The Crusdae.',
       'maimuna': 'Maimuna is a character in The Crusade.',
       'sheyrah': 'Sheyrah is a character in The Crusade.',
       'aridius': 'The Chase starts on the planet Aridius,',
       'lincoln': 'Abraham Lincoln appears briefly in The Chase.',
       'francis': 'Francis Bacon appears briefly in The Chase.',
       'prondyn': 'Prondyn is a character in The Chase.',
       'dracula': 'A robot Count Dracula appears in The Chase.',
       'meddler': 'The Time Meddler is a first Doctor story.',
       'wulnoth': 'Wulnoth is a character in The Time Meddler.',
       'drahvin': 'The Drahvins are the villains in Galaxy 4.',
       'mission': 'Mission to the Unknown is a first Doctor story that does not feature either Doctor nor companions.',
       'unknown': 'Mission to the Unknown is a first Doctor story that does not feature either Doctor nor companions.',
       'troilus': 'Vicki leaves Doctor Who to marry Troilus.',
       'cyclops': 'Cyclops is a character in The Myth Makers.',
       'karlton': 'Karlton is a character in The Daleks\' Masterplan.',
       'trantis': 'Trantis is a member of the Galatic Council in The Daleks\' Materplan.',
       'kirksen': 'Kirksen is a character in The Daleks\' Masterplan.',
       'rhynmal': 'Rhynmal is a character in The Daleks\' Masterplan.',
       'tranton': 'Darcy Tranton is a character in The Daleks\' Masterplan.',
       'khepren': 'Khepren is a character in The Daleks\' Masterplan.',
       'tuthmos': 'Tuthmos is a character in The Daleks\' Masterplan.',
       'coligny': 'Admiral de Coligny appears in The Massacre.',
       'teligny': 'Teligny is a character in The Massacre.',
       'preslin': 'In THe Massacre the Doctor goes to visit Charles Preslin.',
       'mellium': 'Mellium is a character in The Ark.',
       'maharis': 'Maharis is a character in The Ark.',
       'venussa': 'Venussa is a character in The Ark.',
       'refusis': 'In The Ark the human race journeys to the planet Refusis.',
       'clanton': 'In The Gunfighters, the Doctor, Steven and Dodo become caught up in the feud betwen the Clantons and Doc Holliday.',
       'phineas': 'Phineas Clanton is a character in The Gunfighters.',
       'savages': 'The Savages is a first Doctor story.',
       'jamaica': 'Jamaica is a character in The Smugglers.',
       'barclay': 'Barclay is a character in The Tenth Planet.',
       'schultz': 'Schultz is a character in The Tenth Planet.',
       'snowcap': 'The Tenth Planet takes place at Snowcap Base.',
       'hensell': 'Hensell is a character in The Power of the Daleks.',
       'perkins': 'Characters called Perkins appear in The Highlanders, Fury from the Deep, The Invasion, and Mummy on the Orient Express.',
       'attwood': 'Colonel Attwood is a character in The Highlanders.',
       'meadows': 'Meadows is a character in The Faceless Ones.',
       'spencer': 'Spencer is a character in The Faceless Ones.',
       'jenkins': 'Jenkins is a character in The Faceless Ones.',
       'travers': 'Professor Travers appears in both The Abominable Snowmen and The Web of Fear.  His daughter Anne also appears in the latter.,',
       'rinchen': 'Rinchen is a character in the Abominable Snowmen.',
       'garrett': 'Miss Garrett is a character in The Ice Warriors.',
       'walters': 'Walters is a character in The Ice Warriors, The Invasion and Earthshock.',
       'ferrier': 'Astrid Ferrier appears in The Enemy of the World.',
       'fedorin': 'Fedorin is a character in The Enemy of the World.',
       'griffin': 'Griffin the Chef is a character in The Enemy of the World.',
       'chorley': 'Harold Chorley is a character in The Web of Fear.',
       'lutyens': 'Van Lutyens is a character in Fury from the Deep.',
       'seaweed': 'Sentient Seaweed in the form of foam is the monster in Fury from the Deep.',
       'mercury': 'The Doctor has, at least twice, had issues with the mercury fluid links in the Tardis.',
       'fiction': 'The Mind Robber takes place in the Land of Fiction.',
       'watkins': 'Isobel Watkins and her father Professor Watkins appear in The Invasion.',
       'gregory': 'Gregory is a character in The Invasion.',
       'fewsham': 'Fewsham works for the Ice Warriors in The Seeds of Death before regretting his choice.',
       'gregson': 'Gregson is a character in The Seeds of Death.',
       'clancey': 'Milo Clancey is a space prospector in The Space Pirates.',
       'issigri': 'The Space Pirates revolves around the activities of the Issigre Mining Corporation.',
       'hermark': 'General Hermack is a character in The Space Pirates.',
       'dervish': 'Dervish is a character in The Space Pirates.',
       'pirates': 'The Space Pirates is a Second Doctor Story.',
       'nestene': 'The Nestene Consciousness is the villain in Spearhead from Space.',
       'hibbert': 'Hibbert is a character in Spearhead from Space.',
       'mullins': 'Mullins is a character in Spearhed from Space.',
       'masters': 'Masters is a character in The Silurians.',
       'hawkins': 'Captain Hawking is a character in The Silurians.',
       'nutting': 'Corporal Nutting is a character in The Silurians.',
       'cornish': 'Ralph Cornish is a character in The Ambassadors of Death.',
       'quinian': 'Sir James Quinian is a character in The Ambassadors of Death.',
       'heldorf': 'Heldorf is a character in The Ambassadors of Death.',
       'inferno': 'Inferno is a third Doctor story.',
       'primord': 'The Primords are monsters in Inferno.',
       'rossini': 'In Terror of the Autons, the Master hides in Rossini\'s Circus.',
       'summers': 'Dr Roland Summers is played by Michael Sheard in The Mind of Evil.',
       'linwood': 'Arthur Linwood is a character in The Mind of Evil.',
       'axonite': 'The Axons offer the Earth a wonder molecule called Axonite as a plot to absorb all the world\'s energy.',
       'daemons': 'The Daemons is a third Doctor story.',
       'peladon': 'The Curse of Peladon and the Monster of Peladon are both third Doctor stories.',
       'aggedor': 'Aggedor is the Sacred Royal beast of Peladon.',
       'smedley': 'CPO Smedley is a character in The Sea Devils.',
       'mutants': 'The Mutants is a third Doctor story.',
       'marshal': 'The Marshal is the antagonist in The Mutants.',
       'galleia': 'Galleia is Queen of Atlantis in The Time Monster.',
       'hippias': 'Hippias is a character in the Time Monster.',
       'wootton': 'The science institute where the Master is posing as a professor in the Time Monster is in the village of Wootton.',
       'doctors': 'The Three Doctors, The Five Doctors and the Two Doctors are all Doctor Who stories.',
       'pletrac': 'Pletrac is a character in Carnival of Monsters.',
       'bernice': 'The SS Bernice with its crew and passengers is stored in a miniscope in Carnvial of Monsters.  Bernice Summerfield is also a companion from the Virgin New Adventures with her own series of Big Finish stories.',
       'drashig': 'The Drashigs are monsters in Carnival of Monsters.',
       'stevens': 'Stevens is a character in The Green Death.',
       'eleanor': 'Lady Eleanor is a character in The Time Warrior.',
       'warrior': 'The Time Warrior is a third Doctor story.',
       'rubeish': 'Professor Rubeish is a character in The Time Warrior.',
       'railton': 'Richard Railton is a character in Death to the Daleks.',
       'tarrant': 'Jill Tarrant is a character in Death to the Daleks.',
       'exxilon': 'Death to the Daleks takes place on the planet Exxilon.',
       'thalira': 'Queen Thalira is the ruler of Peladon in the Monster of Peldaon.',
       'monster': 'The Monster of Peladon is a third Doctor story.',
       'spiders': 'Planet of the Spiders is a third Doctor story.',
       'hopkins': 'Hopkins is a character in Planet of the Spiders.',
       'crystal': 'The Doctor takes a blue crystal from Metebelis 3 which he gives to Jo Grant as a wedding present.  When she returns it, it triggers the events of Planet of the Spiders.',
       'winters': 'Miss Winters is the villain in Robot.',
       'gharman': 'Gharman is a character in Genesis of the Daleks.',
       'genesis': 'Genesis of the Daleks is a fourth Doctor story.',
       'gerrill': 'Gerrill is a character in Genesis of the Daleks.',
       'kellman': 'Kellman appears to be the antagonist in Revenge of the Cybermen.',
       'revenge': 'Revenge of the Cybermen is a fourth Doctor story.',
       'sheprah': 'Sheprah is a character in Revenge of the Cybermen.',
       'forgill': 'In Terror of the Zygons, the Zygon leader disguises himself as the Duke of Forgill.',
       'salamar': 'Salamar is a character in Planet of Evil.',
       'morelli': 'Morelli is a character in Planet of Evil.',
       'baldwin': 'Baldwin is a character in Planet of Evil.',
       'scarman': 'The Scarman brothers feature prominently in Pyramids of Mars.',
       'warlock': 'Dr. Warlock is a character in Pyramids of Mars.',
       'collins': 'Collins is a character in Pyramids of Mars.',
       'chedaki': 'Chedaki is a Kraal in The Android Invasion.',
       'android': 'The Android Invasion is a fourth Doctor story.',
       'faraday': 'Colonel Faraday is a character in The Android Invasion.',
       'morbius': 'The Brain of Morbius is a fourth Doctor story.',
       'krynoid': 'Krynoids are the monsters in The Seeds of Doom.',
       'winlett': 'Charles Winlett is a character in The Seeds of Doom.',
       'chester': 'Doctor Chester is a character in The Seeds of Doom.',
       'martino': 'The Masque of Mandragora is set in San Martino.',
       'kastria': 'In the Hand of Fear, Eldrad comes from Kastria.',
       'fendahl': 'Image of the Fendahl is a fourth Doctor story.',
       'ransome': 'Thea Ransome is possessed by the Fendahl in Image of the Fendahl.',
       'herrick': 'Herrick is a character in Underworld.',
       'sholakh': 'Sholakh is a character in The Ribos Operation.',
       'jethrik': 'Jethrik is a valuatel mineral that is the centre of Garron and Unstoffe\'s scam in The Ribos Operation.',
       'shrieve': 'The Shrieves are guards in The Ribos Operation.',
       'balaton': 'Balaton is a character in The Pirate Planet.',
       'mentiad': 'The Mentiads are a group with psychic powers in The Pirate Planet.',
       'avatron': 'The Polyphase Avatron is the Captain\'s parrot in The Pirate Planet.',
       'rumford': 'Professor Rumford helps the Doctor and Romana in The Stones of Blood.',
       'cessair': 'Cessair of Diplos is the villain in The Stones of Blood.',
       'reynart': 'The Androids of Tara revolves around Prince Reynart\'s attempts to hold onto his throne.',
       'grendel': 'Count Grendel is the villain in The Androids of Tara.',
       'kurster': 'Kurster is a character in The Androids of Tara.',
       'strella': 'Princess Strella is a character in The Androids of Tara and Romana\'s double.',
       'ranquin': 'Ranquin leads the Swampies in the Power of Kroll.',
       'swampie': 'The Swampies are the indiginous inhabitants of Delta Magna in The Power of Kroll.',
       'destiny': 'Destiny of the Daleks is a fourth Doctor story.',
       'sharrel': 'Commander Sharrel appears in Destiny of the Daleks.',
       'hermann': 'Hermann is a character in City of Death.',
       'adrasta': 'Lady Adrasta is the villain in Creature from the Pit.',
       'organon': 'Organon is a character in Creature from the Pit.',
       'tollund': 'Tollund is a character in Creature from the Pit.',
       'chloris': 'The planet Chloris appears in Creature from the Pit.',
       'vraxoin': 'Vraxoin is a highly addictive drug in Nightmare of Eden.',
       'mandrel': 'The Mandrels are the monster in Nightmare of Eden.',
       'skonnos': 'The Horns of Nimon takes place on Skonnos and Crinoth.',
       'crinoth': 'The Horns of Nimon takes place on Skonnos and Crinoth.',
       'soldeed': 'Soldeed is a villain in The Horns of Nimon.',
       'leisure': 'The Leisure Hive is a fourth Doctor story.',
       'stimson': 'Stimson is a character in The Leisure Hive.',
       'foamasi': 'The Foamasi are some of the villains in The Leisure Hive.',
       'argolis': 'Argolis is the location of the Leisure Hive.',
       'tachyon': 'Tachyons are manipulated in the Leisure Hive\'s Tachyon Recreation Generator.',
       'grugger': 'General Grugger is a character in Meglos.',
       'deedrix': 'Deedrix is a character in Meglos.',
       'tigella': 'Tigella is a planet in Meglos.',
       'chronic': 'In Meglos the Doctor, Romana and K9 become trapped in a chronic hysteresis.',
       'dexeter': 'Dexeter is a doctor in Full Circle.',
       'decider': 'The Deciders govern the Starliner in Full Circle.',
       'camilla': 'Camilla is one of the three who rule in State of Decay.',
       'packard': 'Packard is a character in Warriors\' Gate.',
       'vanessa': 'Tegan\'s Aunt Vanessa is murdered by the Master in Logopolis.',
       'monitor': 'The Monitor is a character in Logopolis.',
       'monarch': 'Monarch is the villain in Four to Doomsday.',
       'sanders': 'Sanders is a character in Kinda.',
       'pudding': 'The Doctor accidentally starts the Great Fire of London in Pudding Lane in The Visitation.',
       'markham': 'Sergeant Markham is a character in Black Orchid.',
       'ringway': 'Ringway works for the Cybermen in Earthshock.',
       'stapley': 'Captain Stapley is a character in Time-Flight.',
       'andrews': 'Andrews is a charcter in Time-Flight.',
       'anithon': 'Anithon is a Xeraphin in Time-Flight.',
       'dugdale': 'Dugdale is a character in Snakedance.',
       'manussa': 'Snakedance takes place on Manussa.',
       'sumaran': 'The Mara destroyed the Sumaran Empire on Manussa.',
       'mawdryn': 'Mawdryn Undead is a fifth Doctor story.',
       'valgard': 'Valgard is a character in Terminus.',
       'striker': 'Striker is a character in Enlightenment.',
       'mansell': 'Mansell is a character in Enlightenment.',
       'collier': 'Collier is a character in Enlightenment.',
       'eternal': 'The Eternals are a race beings that live in the trackless wastes of eternity and are generally bored.',
       'vorshak': 'Vorshak is a character in Warriors of the Deep.',
       'preston': 'Preston is a character in Warriors of the Deep.',
       'hampden': 'Jane Hampden is a character in The Awakening.',
       'timanov': 'Timanov is a character in Planet of Fire.',
       'sorasta': 'Sorasta is a character in Planet of Fire.',
       'krelper': 'Krelper is a character in The Caves of Androzani.',
       'chellak': 'Chellak is the army commander in The Caves of Androzani.',
       'sylvest': 'The Sylvest twins are the eponymous twins in The Twin Dilemma.',
       'dilemma': 'The Twin Dilemma is a sixth Doctor story.',
       'romulus': 'Romulus is one of the Twins in the Twin Dilemma.',
       'jaconda': 'The Twin Dilemma is set on Jaconda.',
       'quillam': 'Quillam is a character in Vengeance on Varos.',
       'dastari': 'Dastari is one of the antagonists in The Two Doctors.',
       'seville': 'The Two Doctors takes place in Seville.',
       'kendron': 'Kendron is a character in Timelash.',
       'brunner': 'Brunner is a character in Timelash.',
       'bandril': 'The Bandrils are an alien race in Timelash.',
       'kontron': 'A Kontron Tunnel ensares the Tardis in Timelash.',
       'bostock': 'Bostock is a character in Revelation of the Daleks.',
       'grigory': 'Grigory is a character in Revelation of the Daleks.',
       'stengos': 'In Revelation of the Daleks the Doctor visits Tranquil Repose because of his friend Stengos.',
       'merdeen': 'Merdeen is a character in The Mysterious Planet.',
       'drathro': 'Drathro is the villain in The Mysterious Planet.',
       'balazar': 'Balazar is a character in The Mysterious Planet.',
       'ravolox': 'Ravolox is the Mysterious Planet.',
       'sabalom': 'Sabalom Glitz is a con man in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
       'crozier': 'Crozier replaces Peri\'s brain with that of Kiv in Mindwarp.',
       'lukozer': 'King Yrcanos\' equerry, Dorf is referred to as The Lukoser after he is experimented upon in Mindwarp.',
       'matrona': 'Matrona Kani is a character in Mindwarp.',
       'vervoid': 'The Vervoids are the monster in Terror of the Vervoids.',
       'fantasy': 'The Fantasy Factory forms the Valeyard\'s hideout in the Matrix in The Ultimate Foe.',
       'lanisha': 'Lanisha is a character in Time and the Rani.',
       'goronwy': 'Goronwy is a friendly bee-keeper in Delta and the Bannermen.',
       'keillor': 'Keillor is a character in Delta and the Bannermen.',
       'bollitt': 'Bollitt is a character in Delta and the Bannerman.',
       'mcluhan': 'McLuhan is a character in Dragonfire.',
       'arnheim': 'Arnhelm is a character in Dragonfire.',
       'stellar': 'Stellar is a little girl in Dragonfire.',
       'svartos': 'Dragonfire is set on Svartos.',
       'proamon': 'The villain Kane, in Dragonfire, wishes to return to his planet of Proamon.',
       'allison': 'Allison is a character in Remembrance of the Daleks.',
       'gilmore': 'Group Captain Gilmore is a character in Remembrance of the Daleks.',
       'killjoy': 'The Happiness Patrol hunts down Killjoys.',
       'wulfric': 'Wulfric is a character in The Happiness Patrol.',
       'prevail': 'Happiness will prevail.',
       'nemesis': 'Silver Nemesis is a Seventh Doctor Story.',
       'windsor': 'Silver Nemesis takes place in the environs of Windsor Castle.',
       'bellboy': 'Bellboy is a character in The Greatest Show in the Galaxy.',
       'morgana': 'Morgana is a character in The Greatest Show in the Galaxy.',
       'kingpin': 'Kingpin is a character in The Greatest Show in the Galaxy.',
       'segonax': 'The Greatest Show in the Galaxy takes place on Segonax.',
       'psychic': 'The Psychic Circus is the Greatest Show in the Galaxy.',
       'bambera': 'Brigadier Winifred Bambera of UNIT appears in Battlefield.',
       'warmsly': 'Peter Warmsly is a character in Battlefield.',
       'mordred': 'Mordred is a villain in Battlefield.',
       'ancelyn': 'Ancelyn is a character in Battlefield.',
       'redvers': 'Redvers Fenn-Cooper is a character in Ghost Light.',
       'control': 'Control is the control experiment to Josiah in Ghost Light.',
       'gabriel': 'The events of Ghost Light take place at Gabriel Chase.',
       'shreela': 'Shreela is a character in Survival.',
       'balhoon': 'Moxx of Balhoon is a character in The End of the World.',
       'raffalo': 'Raffalo is a character in The End of the World.',
       'unquiet': 'The Unquiet Dead is a Ninth Doctor story.',
       'redpath': 'Redpath is a character in The Unquiet Dead.',
       'gwyneth': 'Gwyneth helps the Doctor in the Unquiet Dead.  The actress goes on to place Gwen in Torchwood.',
       'dickens': 'Charles Dickens appears in The Unquiet Dead.',
       'trinity': 'The newsreader Trinity Wells appears in several Doctor Who stories.',
       'harriet': 'Harriet Jones first appears as an MP in Aliens of London/World War Three and returns as Prime Minister in The Christmas Invasion before dying in Journey\'s End.',
       'statten': 'Henry van Statten is the villain in Dalek.',
       'cathica': 'Cathica saves the day in The Long Game.',
       'cardiff': 'Doctor Who is filmed in Cardiff and Torchwood was set there.',
       'crosbie': 'Crosbie is a character in Bad Wolf.',
       'station': 'Bad Wolf and The Parting of the Ways are set on the Game Station.',
       'parting': 'The Parting of the Ways is a Ninth Doctor episode.',
       'rodrick': 'Rodrick is a character in Bad Wolf and The Parting of the Ways.',
       'sycorax': 'The Sycorax are the monsters in The Christmas Invasion.',
       'reunion': 'School Reunion is a Tenth Doctor episode.',
       'lantern': 'The Idiot\'s Lantern is a Tenth Doctor epsiode.',
       'zachary': 'Zachary Cross Flane is a character in The Impossible Planet/The Satan Pit.',
       'manista': 'Scooti Manista is a character in The Impossible Planet/The Satan Pit.',
       'skinner': 'Mr Skinner is a character in Love & Monsters.',
       'hartman': 'Yvonne Hartman leads Torchwood in Army of Ghosts and Doomsday.',
       'runaway': 'The Runaway Bride is a Tenth Doctor episode.',
       'racnoss': 'The Empress of the Racnoss is the villain in The Runaway Bride.',
       'bethlem': 'The Bethlem Hospital appears in The Shakespeare Code.',
       'wiggins': 'Wiggins is a character in The Shakespeare Code.',
       'kincade': 'Thomas Kincade Brannigan is a character in Gridlock.',
       'calypso': 'Sally Calypso is a character in Gridlock.',
       'lazarus': 'The Lazarus Experiment is a Tenth Doctor Story.',
       'vashtee': 'Riley Vashtee is a charcter in 42.',
       'torajii': '42 is set in the Torajii system.',
       'redfern': 'Joan Redfern falls in love with the Doctor\'s human alter ego in Human Nature/The Famaily of Blood.',
       'latimer': 'Tim Latimer holds the Doctor\'s pocket watch in Human Nature/The Family of Blood.',
       'sparrow': 'Sally Sparrow is the protagonist in Blink.',
       'shipton': 'Billy Shipton is a character in Blink.',
       'weeping': 'The Weeping Angels are a monster in New Who.',
       'chantho': 'Chantho is Professor Yana\'s assistant in Utopia.',
       'kistane': 'Kistane is a character in Utopia.',
       'valiant': 'The Valiant is the UNIT flying aircraft carrier, taken over by The Master in The Sound of Drums and Last of the Time Lords.',
       'paradox': 'The Master builds a Paradox Machine in The Sound of Drums.',
       'wilfred': 'Wilfred Mott is Donna\'s grandfather.',
       'titanic': 'Voyage of the Damned takes place on the starship Titanic.',
       'adipose': 'The Adipose are small fat creatures in Partners in Crime.',
       'metella': 'Metalla is a character in The Fires of Pompeii.',
       'quintus': 'Quintus is a charcter in The Fires of Pompeii.',
       'pompeii': 'The Fires of Pompeii is a Tenth Doctor story.',
       'thalina': 'Thalina is a character in The Fires of Pompeii.',
       'evelina': 'Evelina is a character in The Fires of Pompeii.',
       'unicorn': 'The Unicorn and the Wasp is a Tenth Doctor story.',
       'greeves': 'Greeves is a character in The Unicorn and the Wasp.',
       'silence': 'Silence in the Library is a Tenth Doctor story.',
       'library': 'Silence in the Library is a Tenth Doctor story.',
       'magambo': 'Unit Captain Magambo appears in Turn Left and Planet of the Dead.',
       'sanchez': 'General Sanchez is a character in The Stolen Earth.',
       'cascade': 'The Earth is taken to the Medusa Cascade in The Stolen Earth.',
       'journey': 'Journey\'s End is a Tenth Doctor story and Journey to the Centre of the Tardis is an Eleventh Doctor story.',
       'scoones': 'Mr Scoones is a character in The Next Doctor.',
       'praygat': 'Praygat is a character in Planet of the Dead.',
       'ehrlich': 'Steffi Ehrlich is a character in The Waters of Mars.',
       'ramsden': 'Dr Ramsden is a character in The Eleventh Hour.',
       'victory': 'Victory of the Daleks is an Eleventh Doctor story.',
       'rosanna': 'Rosanna Calvierri is the villain in The Vampires of Venice.',
       'nasreen': 'Nasreen Chaudhry is a character in The Hungry Earth/Cold Blood.',
       'ambrose': 'Ambrose is a character in The Hungry Earth/Cold Blood.',
       'vincent': 'Vincent and the Doctor is an Eleventh Doctor story.',
       'tabetha': 'Tabetha is a character in The Big Bang.',
       'sardick': 'Kazran Sardick is the antagonist in A Christmas Carol.',
       'everett': 'Canton Everett Delarware III helps the Doctor in The Impossible Planet/Day of the Moon.',
       'renfrew': 'Dr Renfrew is a character in The Impossible Planet/Day of the Moon.',
       'florres': 'De Florres is a character in The Curse of the Black Spot.',
       'mcgrath': 'McGrath is a character in The Curse of the Black Spot.',
       'cleaves': 'Miranda Cleaves is a character in The Rebel Flesh/The Also People.',
       'terrors': 'Night Terrors is an Eleventh Doctor story.',
       'purcell': 'Purcell is a character in Night Terrors.',
       'handbot': 'The Handbots appear in The Girl Who Waited.',
       'complex': 'The God Complex is an Eleventh Doctor episode.',
       'hayward': 'Lucy Hayward is a character in The God Complex.',
       'closing': 'Closing Time is an Eleventh Doctor episode.',
       'wedding': 'The Wedding of River Song is an Eleventh Doctor episode.',
       'winston': 'Winston Churchill appears in several Eleventh Doctor stories.',
       'malokeh': 'Dr Malokeh is a character in The Wedding of River Song.',
       'karlsen': 'Darla von Karlsen is a character in Asylum of the Daleks.',
       'riddell': 'Riddell is a big game hunter in Dinosaurs on a Spaceship.',
       'solomon': 'Solomon is the villain in Dinosaurs on a Spaceship.',
       'bleytal': 'Bleytal is a character in Dinosaurs on a Spaceship.',
       'dockery': 'Dockery is a character in A Town Called Mercy.',
       'snowmen': 'The Abominable Snowmen and The Snowmen are both Doctor Who stories.',
       'akhaten': 'The Rings of Akhaten is an eleventh Doctor story.',
       'skaldak': 'Skaldak is the Ice Warrior enemy in Cold War.',
       'crimson': 'The Crimson Horror is an Eleventh Doctor story.',
       'whisper': 'The Whisper Men are the monsters in The Name of the Doctor.',
       'arcadia': 'Arcadia is a city on Gallifrey that fell during the Time War.',
       'bentham': 'Lord Bentham is a character in Day of the Doctor.',
       'curator': 'Tom Baker appears as The Curator in Day of the Doctor.',
       'abramal': 'Abramal is a character in Time of the Doctor.',
       'handles': 'Handles is the Doctor\'s Cyberhead.',
       'fleming': 'Fleming is a character in Into the Dalek.',
       'delphox': 'Ms Delphox is Madame Karabraxos\' clone in Time Heist.',
       'porrima': 'Mr Porrima is a character in Time Heist.',
       'blitzer': 'The Skovox Blitzer appears in The Caretaker.',
       'lundvik': 'Lundvik is a character in Kill the Moon.',
       'express': 'Mummy on the Orient Express is a Twelfth Doctor story.',
       'forrest': 'PC Forrest is a character in Flatline.',
       'stewart': 'Kate Stewart is the daughter of the Brigadier.',
       'bellows': 'Bellows is a character in Last Christmas.',
       'prentis': 'Prentis is a Tivolian undertaker in Under the Lake/Before the Flood.',
       'ashildr': 'Ashildr first appears in The Girl Who Died and becomes an antagonist in Season 9.',
       'nollarr': 'Nollar is a character in The Girl who Died.',
       'leandro': 'Leandro is the villain in The Woman who Lived.',
       'anahson': 'Anahson is a character in Face the Raven.',
       'quantum': 'The epoynymous Raven in Face the Raven is a Quantum Shade.',
       'gastron': 'Gastron is a character in Hell Bent.',
       'scratch': 'Scratch is a character in The Husbands of River Song.',
       'halassi': 'The Halassi Androvar is the most valuable diamond in the universer and is inside the brain of King Hydroflax.',
       'heather': 'Heather is Bill\'s girlfriend - and also a sentient puddle.',
       'shireen': 'Shireen is a character in Knock Knock.',
       'dahhren': 'Dahh-Ren is a character in Oxygen.',
       'veritas': 'Veritas is a text that causes readers to commit suicide in Extremis.',
       'rafando': 'Rafando is a character in Extremis.',
       'pyramid': 'The Pyramid at the End of the World is a Twelfth Doctor story.',
       'brabbit': 'Colonel Don Brabbit is a character in The Pyramid at the End of the World.',
       'jackdaw': 'Jackdaw is a character in Empress of Mars.',
       'rexhill': 'Rexhill is a character in The Doctor Falls.',
       'tzimsha': 'Tzim-Sha is the villain in The Woman who Fell to Earth and The Battle of Ranskor av Kolos.',
       'umbreen': 'Yaz\'s nani is called Umbreen.',
       'kerblam': 'Kerblam! is a Thirteenth Doctor story.',
       'twiston': 'Willa and Old Mother Twiston are characters in The Witchfinders.',
       'alfonso': 'Alfonso is a character in The Witchfinders.',
       'ribbons': 'Ribbons is a character in It Takes You Away.',
       'andinio': 'Andinio is a character in The Battle of Ranskoor av Kolos.',
       'spyfall': 'Spyfall is a Thirteenth Doctor story.',
       'skithra': 'The Skithra are the monsters in Nikola Tesla\'s Night of Terror.',
       'clayton': 'Lee Clayton appears to be the Fugitive Doctor\'s husband at the start of Fugitive of the Judoon.',
       'praxeus': 'Praxeus is a Thirteenth Doctor story.',
       'diodati': 'The Haunting of Villa Diodati is a thirteenth Doctor story.',
       'shelley': 'Percy Bysshe Shelley appears in the Haunting of Villa Diodati.',
       'sharmus': 'Ko Sharmus helps humans through the boundary in Ascension of the Cybermen and sacrifices himself to save the universe in The Timeless Children.',
       'brendan': 'Brendan is a dream version of the Doctor in Ascension of the Cybermen.',
       'tecteun': 'Tecteun is the Doctor\'s adoptive mother.',
       'solpado': 'Solpado is a character in The Timeless Children.',
       'rugazzi': 'Leo Rugazzi is a scientist working for Jack Robertson who revives the Daleks in Revolution of the Daleks.',
       'ritskaw': 'Ritskaw is a character in The Halloween Apocalypse.',
       'seacole': 'Mary Seacole appears in War of the Sontarans.',
       'atropos': 'The Temple of Atropos contains the Mouri on the planet time.',
       'village': 'Village of the Angels is a Thirteenth Doctor story.',
       'jericho': 'Professor Jericho assists Yaz and Dan in Flux.',
       'arnhost': 'Deputy Marshal Arnhost is a character in The Power of the Doctor.',
       'shirley': 'Shirley Bingham is UNIT\'s scientific advisor in The Star Beast and The Giggle.',
       'bingham': 'Shirley Bingham is UNIT\'s scientific advisor in The Star Beast and The Giggle.',
       'zogroth': 'Zogroth is a character in The Star Beast.',
       'ibrahim': 'Colonel Ibrahim is a UNIT colonel who appears in The Giggle and The Legend of Ruby Sunday/The Empire of Death.',
       'maestro': 'Maestro is the villain in The Devil\'s Chord.',
       'beatles': 'The Beatles appear in The Devil\'s Chord.',
       'hinchey': 'Frank Hinchkey is a character in 73 Yards.',
       'deloach': 'Craig Deloach is a character in 73 Yards.',
       'bridges': 'Marti Bridges is a character in 73 Yards.',
       'mantrap': 'The Man-Traps are the monsters in Dot and Bubble.',
       'chuldur': 'The Chuldur are the monters in Rogue.',
       'gibbons': 'Morris Gibbons is the UNIT scientific advisor in The Legend of Ruby Sunday and Empire of Death.',
       'william': 'William Hartnell played the first Doctor.',
       'foreman': 'I. M. Foreman owned Totter\'s Yard from and Susan borrowed the surname.',
       'barbara': 'Barbara Wright was a companion to the first Doctor.',
       'russell': 'Russell T. Davies bought back Doctor Who in 2003.',
       'maureen': 'Maureen O\'Brien played companion Vicki.',
       'chaplet': 'Dodo Chaplet was a companion to the first Doctor.',
       'jackson': 'Ben Jackson was a companion to the first and second Doctors.',
       'michael': 'Michael Craze played companion Ben Jackson.',
       'kingdom': 'Sara Kingdom was a companion to the first Doctor.',
       'patrick': 'Patrick Troughton played the second Doctor.',
       'manning': 'Katy Manning played companion Jo  Grant.',
       'jameson': 'Louise Jameson played companion Leela.',
       'matthew': 'Matthew Waterhouse played companion Adric.',
       'jovanka': 'Tegan Jovanka was a companion to the fourth and fifth Doctors.',
       'pertwee': 'Jon Pertwee played the third Doctor.',
       'davison': 'Peter Davison played the fifth Doctor.',
       'melanie': 'Melanie Bush was a companion to the sixth and seventh Doctors.',
       'tennant': 'David Tennant played the tenth and fourteenth Doctors.',
       'agyeman': 'Freema Agyeman played companion Martha Jones.',
       'darvill': 'Arthur Darvill played companion Rory Williams.',
       'coleman': 'Jenna Louise Coleman played companion Clara Oswald.',
       'capaldi': 'Peter Capaldi played the twelfth Doctor.',
       'bradley': 'Bradley Walsh played companion Graham O\'Brien.',
};


