export const WORDSDICT7: {[key:string]:string } = {
       'ganatus': 'Ganatus is a thal in The Daleks.',
       'antodus': 'Antodus is a thal in The Daleks.',
       'kristas': 'Kristas is a thal in The Daleks.',
       'chenchu': 'Chenchu is a character in Marco Polo.',
       'empress': 'Kublai Khan fears his Empress in Marco Polo.',
       'marinus': 'The Keys of Marinus is a first Doctor story.',
       'arbitan': 'Arbitan is the Keeper of the Conscience of Marinus.',
       'sabetha': 'Sabetha is the daughter of Arbitan, Keeper of the Conscience of Marinus.',
       'darrius': 'Darrius is a character in The Keys of Marinus.',
       'tlotoxl': 'Tlotoxl is the antagonist in The Aztecs.',
       'webster': 'Webster is a character in The Reign of Terror',
       'rouvray': 'Rouvray is a character in The Reign of Terror',
       'colbert': 'Leon Colbert is a villain in The Reign of Terror',
       'dortmun': 'Dortmun leads the resistence in The Dalek Invasion of Earth.',
       'thomson': 'Thomson is a character in The Dalek Invasion of Earth.',
       'madison': 'Larry Madison is a character in The Dalek Invasion of Earth.',
       'roboman': 'The Robomen are controlled humans in The Dalek Invasion of Earth.',
       'slyther': 'The deadly Slyther is the Daleks\' pet in The Dalek Invasion of Earth.',
       'bennett': 'Bennett is the villain in The Rescue.',
       'poppaea': 'Poppaea Sabina i
       'sardick': 'Kazran Sardick is the antagonist in A Christmas Carol.',
       'everett': 'Canton Everett Delarware III helps the Doctor in The Impossible Planet/Day of the Moon.',
       'silence': 'The Silence are the monsters in the Impossible Planet/Day of the Moon.',
       'renfrew': 'Dr Renfrew is a character in The Impossible Planet/Day of the Moon.',
       'florres': 'De Florres is a character in The Curse of the Black Spot.',
       'mcgrath': 'McGrath is a character in The Curse of the Black Spot.',
       'cleaves': 'Miranda Cleaves is a character in The Rebel Flesh/The Also People.',
};


