export const WORDSDICT: {[key:string]:string } = {
   'shard': 'The Shard is the base of the Great Intelligence in The Bells of Saint John.',
   'anjli': 'Anjli Mohindra played Rani and the Sarah Jane Adventures and the Queen Skithra in Nikola Tesla\'s Night of Terror.',
   'harry': 'Harry Sullivan was a companion of the Fourth Doctor.',
   'roger': 'Roger Delgado was the first actor to play The Master.',
   'graff': 'Graff Vynda-K is the villain in the Ribos Operation.',
   'mercy': 'A Town called Mercy is an Eleventh Doctor story.',
   'chase': 'The Chase is a First Doctor story.',
   'xeros': 'The Tardis visits the planet Xeros in The Space Museum.',
   'borad': 'The Borad is the villain in Timelash.',
   'panda': 'Steven Taylor brings his toy panda with him into the Tardis.  Panda is also Iris Wildthyme\'s companion in Paul Mags\' stories.',
   'flesh': 'Flesh and Stone and The Rebel Flesh are both Eleventh Doctor stories.',
   'davis': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'stike': 'Stike is a Sontaran in The Two Doctors.',
   'klieg': 'Eric Klieg is one of the villains in Tomb of the Cybermen.',
   'claws': 'The Claws of Axos is Third Doctor Who story.',
   'chula': 'A Chula medical transport causes all the trouble in The Empty Child/The Doctor Dances.',
   'steel': 'The Age of Steel is a Tenth Doctor story.',
   'grace': 'Grace Holloway was the Doctor\'s companion in the TV Movie.',
   'awsok': 'Awsok was an alias used by Tecteun who considered herself the Doctor\'s mother.',
   'clams': 'Giant clams lurk in the sewers of the Kaled City in Genesis of the Daleks.  One of them attacks Harry.',
   'kaled': 'The Daleks are mutated Kaleds.',
   'hedin': 'Councillor Hedin is a villain in Arc of Infinity.',
   'brain': 'The Brain of Morbius is Fourth Doctor story.',
   'rheum': 'The Sandmen monsters in Sleep No More are made from rheum.',
   'elyon': 'Elyon is Thal in The Daleks.',
   'kinda': 'Kinda is a Fifth Doctor story.',
   'janis': 'Leela is initially very keen on killing people with Janis Thorns.',
   'logic': 'According to the Second Doctor logic merely allows one to be wrong with authority.',
   'night': 'Night Terrors, In the Forest of the Night and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'sarah': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'terra': 'Terra Alpha is the planet in The Happiness Patrol.',
   'marco': 'Marco Polo was the show\'s fourth story.',
   'times': 'The regeneration of the Tenth Doctor into the Eleventh is prophesied by He will Knock Four Times.',
   'ringo': 'Johnny Ringo appears in the Doctor Who story The Gunfighters and Ringo Star appears in The Devil\'s Chord.',
   'great': 'The Great Intelligence is a recurring enemy of the Doctor.',
   'styre': 'Styre is the Sontaran in The Sontaran Experiment.',
   'tenth': 'Mondas, home of the Cybermen, was once the tenth planet in the Earth\'s solar system (according to Doctor Who).',
   'mccoy': 'Sylvester McCoy played the Seventh Doctor.',
   'ergon': 'The Ergon is a monster that appears in Arc of Infinity.',
   'varos': 'Varos is the planet in Vengeance on Varos.',
   'sense': 'The Sense Sphere is home to the Sensorites.',
   'ribos': 'The planet Ribos appears in the Ribos Operation.',
   'mummy': 'Mummy on the Orient Express is a Twelfth Doctor story.',
   'ninth': 'The Ninth Doctor was played by Christopher Eccleston.',
   'vogan': 'The Vogans are the inhabitants of the planet Voga in Revenge of the Cybermen.',
   'zargo': 'Zargo is one of the Three Who Rule, villains in State of Decay.',
   'under': 'Under the Lake is a Twelfth Doctor story.',
   'souza': 'Lady Christina de Souza acts as the companion in Planet of the Dead.',
   'varga': 'Varga plants are deadly, but slow-moving, mobile plants from the planet Kembel.  It is also the name of an Ice Warrior.',
   'dryad': 'Dryad beetles are the monsters in Knock Knock.',
   'razor': 'The Master disguises himself as Razor in World Enough and Time.',
   'gelth': 'The Gelth are the villians in The Unquiet Dead.',
   'segal': 'Philip Segal was Executive Producer for the TV Movie.',
   'glitz': 'Glitz is a character in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'lumic': 'John Lumic is the villain in Rise of the Cybermen and The Age of Steel.',
   'pting': 'The Pting is the monster in The Tsuranga Conundrum.',
   'peter': 'There are lots of Peters associated with Doctor Who including, Peter Purves who played companion Steven Taylor, Peter Bryant producer, Peter Davison who played the Fifth Doctor and Peter Capaldi who played the Twelfth Doctor.',
   'james': 'King James I of England and VI of Scotland appears in The Witchfinders.',
   'adams': 'Douglas Adams was a script editor on Doctor Who.',
   'macra': 'The Macra are giant crab like monsters that appeared in both The Macra Terror and Gridlock.',
   'whale': 'A Star Whale is carrying Starship UK in the Beast Below.',
   'curse': 'The Curse of Peladon, The Curse of Fenric, and the Curse of the Black Spot are all Doctor Who stories',
   'magma': 'The Magma Beast appeared in The Caves of Androzani.',
   'zolfa': 'Zolfa Thura is the home planet of Meglos.',
   'minor': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'rebel': 'The Rebel Flesh is an Eleventh Doctor story.',
   'woman': 'The Woman who Lived and the Woman who Fell to Earth are both Doctor Who stories.',
   'robot': 'Robot and Robot of Sherwood are both Doctor Who stories.',
   'poosh': 'The Lost Moon of Poosh, mentioned in Midnight is one of the stolen planets in The Stolen Earth.',
   'plant': 'There are many dangerous plants in Doctor Who, such as the Varga plants and the Krynoids.',
   'craze': 'Michael Craze played Ben, companion to the First and Second Doctors.',
   'vardy': 'The Nano-bot Vardy are the monsters in Smile.',
   'below': 'The Beast Below was an Eleventh Doctor episode.',
   'lynda': 'Lynda (with a Y) is almost a companion in Bad Wolf and the Parting of the Ways.',
   'nikki': 'Nikki Wilson was executive producer of Doctor Who.',
   'seeds': 'The Seeds of Death and the Seeds of Doom are both Doctor Who stories.',
   'malus': 'The Malus is the evil beneath the Church in The Awakening.',
   'banks': 'David Banks played many Cyber Leaders in the 1980s.',
   'piers': 'Piers Wenger was an executive producer of Doctor Who.',
   'reign': 'The Reign of Terror is a First Doctor story.',
   'jelly': 'The Fourth Doctor often offered people Jelly Babies.',
   'gerry': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'solon': 'Doctor Solon is the villain in The Brain of Morbius.',
   'myrka': 'The Myrka is a beast controlled by the Silurians and Sea Devils in Warriors of the Deep.',
   'queen': 'The milk of the Queen Bat is a cure for Spectrox Toxaemia in Tge Caves of Androzani.  The Doctor also married Queen Elizabeth I and was exiled by Queen Victoria.',
   'venus': 'Presumably where the Doctor learned Venusian Aikido.',
   'jodie': 'Jodie Whittaker plays the Thirteenth Doctor.',
   'julie': 'Julie Gardner was an executive producer on Docor Who.',
   'timey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'alien': 'The Earth is frequently invaded by aliens in Doctor Who.',
   'claus': 'Santa Claus appears in Last Christmas.',
   'solos': 'Solos is an Earth Colony in The Mutants',
   'david': 'There are lots of Davids associated with Doctor Who including David Whitaker the show\'s first story editor, David Brierly who voiced K9 and David Tennant who played the Tenth Doctor.',
   'atmos': 'ATMOS, short for Atmospheric Omission System, was a device created by the Sontarans to convert the Earth into a Sontaran Hatchery.',
   'hulke': 'Malcolm Hulke wrote many episodes of Doctor Who and co-write The Making of Doctor Who with Terrance Dicks.',
   'engin': 'Co-ordinator Engin is in charge of the Matrix in The Deadly Assassin.',
   'strax': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'eater': 'The Eater of Light is the monster in The Eaters of Light.',
   'kraal': 'The Kraals appeared in The Android Invasion.',
   'stotz': 'Stotz leads the mercenaries in The Caves of Androzani.',
   'clent': 'Leader Clent runs the Britanicus Base in the Ice Warriors.',
   'marsh': 'Jean Marsh played several roles in Doctor Who, including companion Sara Kingdom.',
   'magna': 'In the King\'s Demons, the Master attempts to intefere with the signing of the Magna Carta.',
   'papal': 'The Papal Mainframe is the headquarters of the militarised Church.',
   'green': 'The Green Death is a Third Doctor story.',
   'wiles': 'John Wiles was the second producer of Doctor Who.',
   'ogros': 'Planet of the Ogri from the Stones of Blood.',
   'erato': 'Erato was the Creature from the Pit.',
   'wrack': 'Captain Wrack is the villain in Enlightnement.',
   'potts': 'Bill Potts was a companion to the Twelfth Doctor.',
   'taran': 'The Taran Wood Beast is a creature in the Androids of Tara.',
   'omega': 'Omega was a legendary Time Lord who created the supernova that powers Time Lord civilisation',
   'nitro': 'Ace often blew things up with Nitro Nine.',
   'blitz': 'The Empty Child and the Doctor Dances take place during the London Blitz.',
   'juice': 'Mel makes the Sixth Doctor drink carrot juice in the hopes that he will lose weight.',
   'wheel': 'The Wheel is a space station where the Doctor met his companion Zoe.',
   'tesla': 'Nikola Tesla\'s Night of Terror is a Thirteenth Doctor story.',
   'ncuti': 'Ncuti Gatwa will play the Fourteenth Doctor.',
   'lucas': 'Matt Lucas played companion Nardole.',
   'usher': 'The Gold Usher is a Time Lord ceremonial position.',
   'morok': 'The Moroks are the villains in The Space Museum.',
   'izlyr': 'Izlyr is an Ice Warrior who appears in The Curse of Peladon',
   'aneth': 'Aneth is a planet in The Horns of Nimon.',
   'dream': 'The Dream Lord is a manifestation of the Doctor\'s subconscious.  Dream Crabs attack the characters in Last Christmas.',
   'frock': 'The First Doctor wore an Edwardian frock coat.',
   'moths': 'Flesh Moths inhabit the space between universes in It Takes You Away.',
   'erisa': 'Captain Erisa Magambo is a UNIT Captain who appears in Turn Left and Planet of the Dead.',
   'tower': 'Rassilon\'s Tomb lies in a Tower in the Death Zone on Gallifrey.',
   'morax': 'The Morax are the villains in The Witchfinders.',
   'wings': '"Chap with wings.  Five Rounds Rapid." was said by the Brigadier.',
   'scoop': 'The Time Scoop was created during the Dark Time on Gallifrey.',
   'elton': 'Elton is the viewpoint character in Love & Monsters.',
   'wotan': 'WOTAN was an evil computer that appeared in The War Machines.',
   'dregs': 'The Dregs are the remains of humanity in Orphan 55',
   'zanak': 'Zanak is the Pirate Planet.',
   'chalk': 'In Battlefield, Ace and Shou Yuing hold off the Destroyer with a chalk circle.',
   'derek': 'There have been lots of Dereks associated with Doctor Who, including Derek Ware who founded the stunt team HAVOC and Derek Jacobi who played the Master',
   'vault': 'In his final series, the Twelfth Doctor keeps Missy locked in a vault.',
   'susan': 'Susan was is the Doctor\'s Grandaughter.',
   'horns': 'The Horns of Nimon is a Fourth Doctor story.',
   'light': 'Light is one of the villains in Ghost Light.',
   'monks': 'The Meddling Monk, the Headless Monks and the Monks have all opposed the Doctor.',
   'storm': 'Robots of Death takes place on a Storm Mine.',
   'kemel': 'Kemel is a servant of the Maxfields in The Evil of the Daleks and helps Jamie rescue Victroia.',
   'lalla': 'Lalla Ward played Romana, companion to the Fourth Doctor.',
   'image': 'Image of the Fendahl is a Fourth Doctor story.',
   'wimey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'quark': 'The Quarks are the robot servants of the Dominators',
   'byron': 'Lord Byron appears in the Haunting of Villa Diodati.',
   'ogron': 'The Ogrons appeared as servants to the Daleks in Day of the Daleks and Frontier in Space.',
   'brave': 'The Fifth Doctor often urged Tegan to have a brave heart.',
   'rings': 'The Rings of Akhaten is an Eleventh Doctor story.',
   'snake': 'The Mara takes the form of a giant snake.',
   'exile': 'The Third Doctor is exiled to Earth.',
   'segun': 'Segun Akinola currently composes the music for Doctor Who.',
   'smile': 'Smile is a Twelfth Doctor story.',
   'sigma': 'Theta Sigma was the Doctor\'s nickname at the Time Lord academy.  In the Happiness Patrol all aliens are designated Sigma.  Later Ood Sigma is instramental in freeing the Ood.',
   'heist': 'Time Heist is a Twelfth Doctor story.',
   'venom': 'Venom Grubs are one of the races on the Web Planet, Vortis.',
   'sixth': 'The Sixth Doctor was played by Colin Baker.',
   'finch': 'Mr Finch is the villain in School Reunion.',
   'jenna': 'Jenna Coleman played companion Clara Oswald.',
   'yates': 'Captain Mike Yates was a regular character during the UNIT years.',
   'space': 'Doctor Who adventures in Time and Space.',
   'heart': 'The Doctor has two hearts.',
   'auton': 'The Autons are plastic creatures controlled by the Nestene Consciousness.',
   'cheem': 'Home of the Forest of Cheem from The End of the World.',
   'build': 'The Kangs in Paradise Towers use the phrase Build High for Happiness.',
   'alpha': 'Alpha Centauri is a diplomat who appears in The Curse of Peladon',
   'tigus': 'A volcanic planet visited in The Daleks\' Masterplan.',
   'virus': 'The villain in The Invisible Enemy is a sentient virus.',
   'shada': 'Shada is an unbroadcast episode of Doctor Who.',
   'letts': 'Barry Letts was a producer and director of Doctor Who.',
   'raven': 'Face the Raven is a Twelfth Doctor story.',
   'human': 'Human Nature is a Tenth Doctor story.',
   'skaro': 'Skaro is the Dalek planet.',
   'paris': 'Paris is the City of Death.',
   'oswin': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'nyder': 'Nyder is Davros\' Henchman in Genesis of the Daleks.',
   'cruel': 'In various forms the words \'Never cruel or cowardly\' have been used in Doctor Who.',
   'sleep': 'Sleep No More is a Twelfth Doctor story.',
   'cyron': 'The Cryons were a race in Attack of the Cybermen.',
   'nyssa': 'Nyssa was a companion of the Fourth and Fifth Doctors.',
   'selby': 'Tony Selby played Glitz in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'ching': 'Madam Ching, the famous pirate, appeared in Legend of the Sea Devils.',
   'barry': 'Barry Letts was a producer and director of Doctor Who.',
   'grant': 'Jo Grant was a companion of the Third Doctor.',
   'leela': 'Leela was a companion to the Fourth Doctor.',
   'ssorg': 'Ssorg is an Ice Warrior who appears in the Curse of Peladon',
   'tryst': 'Professor Tryst was the villian in The Nightmare of Eden.',
   'roman': 'The Romans is a First Doctor story.',
   'mouri': 'The Mouri are the gatekeepers of the Temple of Atropos.',
   'vanir': 'The Vanir work on the Terminus in the Fith Doctor episode Terminus.',
   'blood': 'The Stones of Blood, The Family of Blood, and Cold Blood are all Doctor Who stories.',
   'fifth': 'The Fifth Doctor was played by Peter Davison.',
   'paper': 'The Doctor often uses Psychic Paper to get past officials.',
   'missy': 'Missy is the Doctor\'s arch enemy.',
   'death': 'The Seeds of Death, The Ambassadors of Death, The Green Death, Death to the Daleks, The Robots of Death, City of Death, Death in Heaven, and Empire of Death are all Doctor Who stories.',
   'decay': 'State of Decay is a Fourth Doctor story.',
   'trial': 'Trial of a Time Lord is the over-arching title of the Sixth Doctor\'s second season.',
   'maren': 'Maren is leader of the Sisterhood of Karn in The Brain of Morbius.',
   'rigsy': 'Rigsy appears in Flatline and Face the Raven.',
   'lazar': 'Nyssa catches Lazar disease in Terminus and remains behind to help find a cure.',
   'innes': 'Innes Lloyd was a Doctor Who producer.',
   'polly': 'Polly was a companion of the first and second Doctors.',
   'vworp': 'Allegedly the Tardis goes Vworp Vworp when it materialises.',
   'xeron': 'The Tardis visits the planet Xeros in The Space Museum and helps the Xerons gain freedom from the oppressive Moroks.',
   'brian': 'There have been several Brians associated with Doctor Who included Brian Hayles who created the Ice Warriors and executive producer Brian Minchin.',
   'satan': 'The Satan Pit is a Tenth Doctor story.',
   'power': 'The Power of the Daleks, The Power of Kroll and The Power of Three are all Doctor Who stories.',
   'pluto': 'The Sun Makers is set on Pluto.',
   'sorin': 'Captain Sorin is a love interest for Ace in The Curse of Fenric.',
   'avery': 'Pirate Henry Avery appears in The Curse of the Black Spot and is mentioned in The Smugglers.',
   'opens': 'The Pandorica Opens is an Eleventh Doctor story.',
   'dicks': 'Terrance Dicks was a Doctor Who writer, script editor and prolific noveliser of Doctor Who stories.',
   'rusty': 'Rusty is a "good" Dalek.',
   'villa': 'The Haunting of Villa Diodati is a Thirteenth Doctor story.',
   'brown': 'Peri Brown was a companion of the Fifth and Sixth Doctors.',
   'event': 'In Castrovalva the Tardis races back to Event One.',
   'greel': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'fires': 'The Fires of Pompei is a Tenth Doctor story.',
   'state': 'State of Decay is a Fourth Doctor story.',
   'lewis': 'Dan Lewis is a companion of the Thirteenth Doctor.',
   'chris': 'Chris Chibnall is the current Doctor Who showrunner.  Christopher Eccleston played the Ninth Doctor.',
   'sugar': 'In The Moonbase, the Cybermen poison the sugar.',
   'skorr': 'Commander Skorr is a Sontaran in The Sontaran Stratagem.',
   'pilot': 'The Pilot is a Twelfth Doctor story.',
   'globe': 'Much of The Shakespeare Code is set at the Globe Theatre in London.',
   'trees': 'The Trees save the day in Into the Forest of the Night and the Androzani Trees are endangered in The Doctor, The Widow and the Wardrobe.',
   'nixon': 'President Richard Nixon appears in The Impossible Astronaut and Day of the Moon.',
   'azure': 'Azure is one of the villains in Flux.',
   'jamie': 'Jamie McCrimmon was a companion of the Second Doctor.',
   'slaar': 'Slaar is an Ice Warrior who appears in The Seeds of Death.',
   'horus': 'The Eye of Horus held Sutekh prisoner on Earth.',
   'takes': 'It Takes You Away is a Thirteenth Doctor story.',
   'lords': 'Last of the Time Lords is a Tenth Doctor story.',
   'kalid': 'Kalid is a disguise adopted by the Master in Time-Flight.',
   'third': 'Jon Pertwee played the Third Doctor.',
   'scarf': 'The Fourth Doctor was famous for his long scarf.',
   'telos': 'Telos is a Cyberman planet that featured in both Tomb of the Cybermen and Attack of the Cybermen.',
   'major': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'robin': 'Robin Hood appears in Robot of Sherwood.',
   'smith': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.  Matt Smith played the Eleventh Doctor.',
   'bride': 'The Runaway Bride is a Tenth Doctor story.',
   'santa': 'Robot Santas threaten the Doctor in the Christmas Invasion and the Runaway Bride.',
   'wyatt': 'Wyatt Earp appears in the Doctor Who story The Gunfighters.',
   'carol': 'A Christmas Carol is an Eleventh Doctor story.',
   'spain': 'The Two Doctors was filmed on location in Spain.  This was a big deal at the time.',
   'wills': 'Anneke Wills played Polly, companion to the First and Second Doctors.',
   'devil': 'The Sea Devils are relatives of the Silurians.',
   'staal': 'General Staal is a Sontaran in The Sontaran Stratagem.',
   'cyril': 'Cyril is an evil school boy in The Celestial Toryroom.',
   'clara': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'black': 'Black Orchid and The Curse of the Black Spot are both Doctor Who stories.',
   'caves': 'The Caves of Androzani is a Fifth Doctor story.',
   'madge': 'Madge Arwell is the Widow in the Doctor, the Widow and the Wardrobe.',
   'wendy': 'Wendy Padbury played Zoe, companion to the Second Doctor.',
   'ianto': 'Ianto Jones was a series regular in the Torchwood Doctor Who spin-off and also appeared in The Stolen Earth and Journey\'s End.',
   'parks': 'The Doctor Who story Rosa is about activist Rosa Parks.',
   'nimon': 'The Nimon are minotaur like creatures from The Horns of Nimon.',
   'karen': 'Karen Gillan played Amy Pond, companion.',
   'dalek': 'The Daleks are the show\'s most famous monster.',
   'sacha': 'Sacha Dhawan played The Master during the Thirteenth Doctor series.',
   'maxil': 'Commander Maxil is a Time Lord played by future Doctor, Colin Baker.',
   'tegan': 'Tegan Jovanka was a companion of the Fourth and Fifth Doctors.',
   'gomez': 'Michelle Gomez played Missy.',
   'chang': 'Chang Lee was the Doctor (or the Master)\'s companion in the TV Movie.',
   'lloyd': 'Innes Lloyd was a Doctor Who producer.',
   'gatwa': 'Ncuti Gatwa will play the Fourteenth Doctor.',
   'bells': 'The Bells of Saint John is an Eleventh Doctor story.',
   'bland': 'Terrance Dicks used the pseudonum Robin Bland for The Brain of Morbius because he disliked the changes made to his script by the production team.',
   'dyall': 'Valentine Dyall played the Black Guardian.',
   'class': 'Class is a Doctor Who spin-off show set in Cole Hill School.',
   'maaga': 'Maaga was the villainous leader of the Drahvin in Galaxy Four.',
   'quill': 'Mr Quill is a servant of the seaweed in Fury from the Deep.',
   'frost': 'Thin Ice takes place at a Frost Fair on the Thames.',
   'gonds': 'The Gonds live on the Planet of the Gonds in The Krotons.',
   'water': 'Dark Water is a Twelfth Doctor story.',
   'wharf': 'Doomsday ends with the Battle of Canary Wharf between the Daleks and the Cybermen.',
   'waris': 'Waris Hussein was Doctor Who\'s first director.',
   'adric': 'Adric was a companion of the Fourth and Fifth Doctors.',
   'priam': 'King Priam of Troy appears in The Myth Makers.',
   'nuton': 'The Nuton Power Complex is blown up by the Axons in the Claws of Axos.',
   'above': 'He who to Rassilon\'s Tower would go must choose above, between, below.',
   'munro': 'Rona Munro wrote Survival the final story in the original run of Doctor Who.  She is the only writer to have written for both the classic and the new series.',
   'karra': 'Karra is a Cheetah person who befriends Ace in Survival.',
   'benny': 'In the novels, Bernice Summerfield (known as Benny) was a companin to the Seventh Doctor.',
   'child': 'The Doctor is the Timeless Child.',
   'river': 'River Song is the Doctor\'s wife.',
   'twice': 'Twice Upon a Time is a Twelfth Doctor story.',
   'jenny': 'Jenny is the Doctor\'s Daughter.',
   'doris': 'Doris is the Brigadier\'s wife in Battlefield.',
   'thura': 'Zolfa Thura is the home planet of Meglos.',
   'orion': 'The Fifth Doctor often tried to get to the Eye of Orion, succeeding in The Five Doctors.',
   'sweet': 'Mr Sweet is a villain in The Crimson Horror.',
   'germs': 'Spider Germs menace the characters in Kill the Moon.',
   'saint': 'The Bells of Saint John is an Eleventh Doctor story.',
   'zarbi': 'The Zarbi were monters appearing in the The Web Planet.',
   'thals': 'The Thals are the enemy of the Daleks... And I promised Prof. Dresner I would include them.',
   'angel': 'The Weeping Angels are a popular Doctor Who Monster.',
   'tosin': 'Tosin Cole played companion Ryan Sinclair.',
   'wales': 'The modern Doctor Who series was bought back by BBC Wales and is made in Cardiff.',
   'helen': 'Helen A was the villain in The Happiness Patrol.',
   'blink': 'Blink is a Tenth Doctor episode.',
   'axons': 'The Axons are the monsters in The Claws of Axos.',
   'rills': 'The Rills were aliens in Galaxy Four.',
   'danny': 'Danny Pink is Clara Oswald\'s boyfriend.',
   'altos': 'Altos is an agent of Arbitan in the Keys of Marinus.',
   'ohila': 'Ohila is the leader of the Sisterhood of Karn in Night of the Doctor, The Magician\'s Apprentice and Hell Bent.',
   'chips': 'Chips coated in Krillitane Oil were served to the children in School Reunion.',
   'zocci': 'Bannakaffalatta from Voyage of the Damned was a Zocci.',
   'hines': 'Frazer Hines played Jamie, companion to the Second Doctor.',
   'alaya': 'Alaya is a Silurian in the The Hungry Earth and Cold Blood.',
   'world': 'The Enemy of the World, The End of the World, World War Three, The Pyramid at the End of the World and World Enough and Time are all Doctor Who stories.',
   'voord': 'The alien Voord were the monsters in the Keys of Marinus.',
   'nerva': 'The Nerva Space Station features in both The Ark in Space and Revenge of the Cybermen.',
   'shura': 'Shura is a rebel time traveller from the Daleks in Day of the Daleks who nearly creates a bootstrap paradox.',
   'clown': 'The Chief Clown is a villian in The Greatest Show in the Galaxy.',
   'crime': 'Partners in Crime is a Tenth Doctor story.',
   'knock': 'Knock Knock is a Twelfth Doctor story.',
   'donna': 'Donna Noble was a companion of the Tenth Doctor.',
   'giant': 'The Doctor has faced Giant Rats, Giant Crabs and Giant Robots among other menaces.',
   'tyler': 'Rose Tyler was a companion of the Ninth and Tenth Doctors.',
   'games': 'The War Games is a Third Doctor story.',
   'drums': 'The Sound of Drums is a Tenth Doctor story.',
   'piper': 'Billie Piper played Rose Tyler, companion.',
   'swamp': 'When Mistfall comes the Marshmen leave the Swamp in Full Circle.',
   'varsh': 'Varsh was Adric\'s brother in Full Circle.',
   'theta': 'The Doctor\'s nickname at the Time Lord academy was Theta Sigma.',
   'clone': 'The Doctor\'s Daughter is created using a form of cloning technology.',
   'ohica': 'Ohica is a member of the Sisterhood of Karn in The Brain of Morbius.',
   'rutan': 'The Rutans are the deadly enemies of the Sontarans.',
   'noble': 'Donna Noble was a companion of the Tenth Doctor.',
   'hilio': 'Hilio was a Menoptera, played by Martin Jarvis, in The Web Planet.',
   'faith': 'Faith can be used to hold back haemovores, but it also feeds the creature in the God Complex.',
   'capel': 'Taren Capel is the villain in The Robots of Death',
   'swarm': 'Swarm is one of the villains in Flux.',
   'helix': 'The Mandragora Helix is the enemy in the Masque of Mandragora.',
   'grand': 'The Grand Serpent helped found and then disassemble UNIT.',
   'stone': 'Flesh and Stone is an Eleventh Doctor episode.',
   'baker': 'Tom Baker played the Fourth Doctor and Colin Baker played the Sixth Doctor.',
   'titan': 'Titan Base is taken over by a sentient virus in The Invisible Enemy',
   'liner': 'Bin Liner is a Kang in Paradise Towers.',
   'thorn': 'Leela is initially very keen on killing people with Janis Thorns.',
   'lance': 'Lance Bennet is Donna Noble\'s fiance in The Runaway Bride.',
   'idiot': 'The Idiot\'s Lantern is a Tenth Doctor story.',
   'crack': 'The Eleventh Doctor\'s first series is plagued by cracks in time and space.',
   'condo': 'Condo was Solon\'s Henchman in The Brain of Morbius.',
   'colin': 'The Sixth Doctor was played by Colin Baker.',
   'binro': 'Binro is a heretic on Ribos because of his belief in life in the stars.',
   'zygon': 'The Zygons appeared in Terror of the Zygons, The Day of the Doctor, The Zygon Invasion and The Zygon Inversion.',
   'cyber': 'Humans fought many Cyber wars against the Cybermen.',
   'rodan': 'Rodan was a female Gallifreyan Traffic Controller who helps the Doctor and Leela in the Invasion of Time.',
   'wirrn': 'The Wirrn were monsters that appeared in The Ark in Space.',
   'kroll': 'Kroll is a giant squid from The Power of Kroll.',
   'trion': 'Home planet of the Doctor\'s companion Turlough.',
   'zodin': 'The Terrible Zodin was mentioned but never seen.',
   'white': 'The White Guardian is the anthropomorphic personification of order and good.',
   'remus': 'Romulus and Remus were the twins in The Twin Dilemma.',
   'clegg': 'Professor Clegg is an unwilling psychic in Planet of the Spiders.',
   'raaga': 'Raaga is the penal planet of the Tereleptils.',
   'earth': 'Lots of stories are set on the planet Earth.',
   'sarff': 'Colony Sarff was a servant of Davros in The Magician\'s Apprectice and the Witch\'s Familiar.',
   'paddy': 'Paddy Russell was the first female director to work on Doctor Who.',
   'sound': 'The Sound of Drums is a Tenth Doctor story.',
   'three': 'The Three Doctors, World War Three and the Power of Three are all Doctor Who stories.',
   'tooth': 'Tooth and Claw is a Tenth Doctor episode.',
   'ghost': 'Ghost Light and The Ghost Monument are both Doctor Who stories.',
   'terry': 'Terry Nation created the Daleks.',
   'solar': 'The villainous Mavic Chen is Guardian of the Solar System.',
   'havoc': 'HAVOC was a team of stuntmen that provided action scenes for many Third Doctor episodes.',
   'beast': 'The Beast Below is an Eleventh Doctor story and the Star Beast is a Fourteenth Doctor story.',
   'gebek': 'Gebek leads the miners in The Monster of Peladon.',
   'wells': 'H. G. Wells appears in the story Timelash.',
   'kandy': 'The Kandy Man is a deadly robot in The Happiness Patrol.',
   'widow': 'The Doctor, the Widow and the Wardrobe is an Eleventh Doctor story.',
   'empty': 'The Empty Child is a Ninth Doctor story.',
   'watch': 'Time Lords seem to frequently hide their memories in pocket watches.',
   'flint': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'astra': 'Princess Astra of Atrios is the sixth segment of the Key to Time.  Romana chooses to look like her when she regenerates.',
   'sally': 'Sally Sparrow is the protagonist of Blink.',
   'cybus': 'Cybus Industries creates the Cybermen in Rise of the Cybermen and The Age of Steel.',
   'dandy': 'The First Doctor described the Second and Third Doctors as a dandy and a clown.',
   'carta': 'In the King\'s Demons the Master attempts to intefere with the signing of the Magna Carta.',
   'siren': 'The malfunctioning medical system in The Curse of the Black Spot was considered a Siren by the pirates.',
   'stien': 'Stien betrays the Doctor in Resurrection of the Daleks.',
   'shade': 'A Quantum Shade takes the form of a raven and deals out justice in Face the Raven.',
   'first': 'William Hartnell played the First Doctor.',
   'idris': 'Idris is a personification of the Tardis in The Doctor\'s Wife.',
   'guard': 'Gel Guards are the servants of Omega in The Three Doctors.',
   'mavic': 'Mavic Chen is the villain in The Daleks\' Masterplan.',
   'taren': 'Taren Capel is the villain in The Robots of Death',
   'svild': 'Svild is a Sontaran in War of the Sontarans.',
   'jemma': 'Jemma Redgave played Kate Stewart, the head of UNIT.',
   'vasor': 'Vasor is an antagonist in the frozen wastes in The Keys of Marinus.',
   'cheng': 'Suki Cheng was the villain in Praxeus.',
   'aztec': 'The Aztecs is a First Doctor story.',
   'jones': 'Martha Jones was a companion of the Tenth Doctor.',
   'tenza': 'The boy, George, in Night Terrors is really a Tenza.',
   'janet': 'Janet Fielding played Tegan Jovanka, companion to the Fourth and Fifth Doctors.',
   'aukon': 'Aukon is one of the Three Who Rule, villains in State of Decay.',
   'yuing': 'Show Yuing is Ace\'s friend in Battlefied.',
   'delia': 'Delia Derbyshire composed the theme tune.',
   'witch': 'The Doctor is tried as a witch in The Witchfinders',
   'truth': 'Truth or Consequences is a town occupied by Zygons in The Zygon Invasion.',
   'diplos': 'The Great Seal of Diplos is the third segment of the Key to Time.',
   'vigil': 'The Vigil were one of the races of the Rings of Akhaten.',
   'kolos': 'The Battle of Ranskoor Av Kolos is a Thirteenth Doctor story.',
   'flood': 'Mrs Flood is a mysterious neighbour of the Sundays.',
   'pearl': 'Pearl Mackie played companion Bill Potts.',
   'walsh': 'Bradley Walsh played companion Graham O\'Brien.',
   'chief': 'The War Chief was one of the villains in The War Games',
   'siege': 'The Time of the Doctor is about the Siege of Trenzalore.',
   'solow': 'Ingrid Pitt plays the villainous Doctor Solow in Warriors of the Deep.',
   'saxon': 'Harold Saxon is the alias adopted by the Master in the Tenth Doctor\'s second series.',
   'sonic': 'The Doctor often uses the Sonic Screwdriver to get out of scrapes.',
   'india': 'The Demons of the Punjab is about the Partition of India.',
   'linda': 'The London Investigation \'n\' Detective Agency (LINDA) seeks to learn more about the Doctor in Love & Monsters.',
   'vicki': 'Vicki was a companion of the first Doctor.',
   'ashad': 'Ashad is the lone Cyberman.',
   'house': 'House is the villain in The Doctor\'s Wife.',
   'lived': 'The Woman who Lived is a Twelfth Doctor story.',
   'delta': 'Delta and the Bannermen is a Seventh Doctor story.',
   'enemy': 'The Enemy of the World and The Invisible Enemy are both Doctor Who stories.',
   'betan': 'The Thal woman Betan helps the Doctor in Genesis of the Daleks.',
   'tasha': 'Tasha Lem leads the Church of the Papal Mainframe in Time of the Doctor.',
   'skaak': 'Skaak is a sontaran in War of the Sontarans.',
   'diane': 'Diane is Dan Lewis\' girlfriend.',
   'fudge': 'Fudge is a friend of Rose Noble in The Star Beast.  He plays a more prominent role in the comic the story is based on.',
   'isaac': 'Isaac Newton appears (briefly) in Wild Blue Yonder.',
   'twist': 'There is always a twist at the end.',
   'logie': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'baird': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'vlinx': 'The Vlinx works for UNIT.',
   'carla': 'Carla Sunday is Ruby\'s mother.',
   'poppy': 'Poppy is captain of the Space Babies.',
   'chord': 'The Devil\'s Chord is a Fifteenth Doctor story.',
   'cilla': 'Cilla Black appears in The Devil\'s Chord.',
   'abbey': 'The famous Abbey Road zebra crossing appears in The Devil\'s Chord.',
   'vater': 'Vater is a title in the Anglican Army that appears in Boom.',
   'mundy': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'flynn': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'sethu': 'Varada Sethu will play a new companion in the 2025 season.',
   'yards': '73 Yards is a Fifteenth Doctor story.',
   'hiker': 'Susan Twist plays a Hiker in 73 Yards.',
   'lindy': 'Lindy Pepper-Bean is the protagonist in Dot and Bubble.',
   'ricky': 'Ricky September is Lindy Pepper-Bean\'s love interest in Dot and Bubble before she kills him.',
   'penny': 'Susan Twist plays Penny Pepper-Bean in Dot and Bubble.',
   'rogue': 'Rogue is a Fifteenth Doctor story.',
   'triad': 'Susan Twist playse Susan Triad in The Legend of Ruby Sunday and The Empire of Death.',
   };
