export const WORDSDICT: {[key:string]:string } = {
   'susan': 'Susan was is the Doctor\'s Grandaughter.',
   'delia': 'Delia Derbyshire composed the theme tune.',
   'waris': 'Waris Hussein was Doctor Who\'s first director.',
   'earth': 'Lots of stories are set on the planet Earth.',
   'dalek': 'The Daleks are the show\'s most famous monster.',
   'skaro': 'Skaro is the Dalek planet.',
   'terry': 'Terry Nation created the Daleks.',
   'david': 'There are lots of Davids associated with Doctor Who including, David Whitaker the show\'s first story editor, David Brierly who voiced K9.',
   'marco': 'Marco Polo was the show\'s fourth story.',
   'voord': 'The alien Voord were the monsters in the Keys of Marinus.',
   'vicki': 'Vicki was a companion of the first Doctor.',
   'zarbi': 'The Zarbi were monters appearing in the episode The Web Planet.',
   'morok': 'The Morok\'s are the villains in The Space Museum.',
   'xeros': 'The Tardis visits the planet Xeros in The Space Museum.',
   'peter': 'There are lots of Peters associated with Doctor Who including, Peter Purves who played companion Steven Taylor, Peter Bryant producer.',
   'rills': 'The Rills were aliens in Galaxy Four.',
   'maaga': 'Maaga was the villainous leader of the Drahvin in Galaxy Four.',
   'marsh': 'Jean Marsh played several roles in Doctor Who, including companion Sara Kingdom.',
   'mavic': 'Mavic Chen is the villain in The Daleks\' Masterplan.',
   'varga': 'Varga plants are deadly, but slow-moving, mobile plants from the planet Kembel.  It is also the name of an Ice Warrior.',
   'paddy': 'Paddy Russell was the first female director to work on Doctor Who.',
   'wiles': 'John Wiles was the second producer of Doctor Who.',
   'gerry': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'davis': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'gough': 'Michael Gough played the Celestial Toymaker and Councillor Hedin in Doctor Who.',
   'innes': 'Innes Lloyd was a Doctor Who producer.',
   'lloyd': 'Innes Lloyd was a Doctor Who producer.',
   'wyatt': 'Wyatt Earp appears in the Doctor Who story The Gunfighters.',
   'ringo': 'Johnny Ringo appears in the Doctor Who story The Gunfighters.',
   'wotan': 'WOTAN was an evil computer that appeared in The War Machines.',
   'wills': 'Anneke Wills played Polly, companion to the First and Second Doctors.',
   'polly': 'Polly was a companion of the first and second Doctors.',
   'craze': 'Michael Craze played Ben, companion to the First and Second Doctors.',
   'hines': 'Frazer Hines played Jamie, companion to the Second Doctor.',
   'jamie': 'Jamie McCrimmon was a companion of the Second Doctor.',
   'macra': 'The Macra are giant crab like monsters that appeared in both The Macra Terror and Gridlock.',
   'hulke': 'Malcolm Hulke wrote many episodes of Doctor Who and co-write The Making of Doctor Who with Terrance Dicks.',
   'telos': 'Telos is a Cyberman planet that featured in both Tomb of the Cybermen and Attack of the Cybermen.',
   'klieg': 'Eric Klieg is one of the villains in Tomb of the Cybermen.',
   'barry': 'Barry Letts was a producer and director of Doctor Who.',
   'letts': 'Barry Letts was a producer and director of Doctor Who.',
   'sonic': 'The Doctor often uses the Sonic Screwdriver to get him out of scrapes.',
   'wendy': 'Wendy Padbury played Zoe, companion to the Second Doctor.',
   'wheel': 'The Wheel is a space station where the Doctor met his companion Zoe.',
   'tenth': 'Mondas, home of the Cybermen, was once the tenth planet in the Earth\'s solar system (according to Doctor Who).',
   'dicks': 'Terrance Dicks was a Doctor Who write, script editor and prolific noveliser of Doctor Who stories.',
   'slaar': 'Slaar is an Ice Warrior who appears in The Seeds of Death.',
   'space': 'Doctor Who adventures in Time and Space.',
   'madoc': 'Philip Madoc appeared in four Doctor Who stories and in the Daleks\' Invasion Earth 2140 A.D. movie.',
   'auton': 'The Autons are plastic creatures controlled by the Nestene Consciousness.',
   'havoc': 'HAVOC was a team of stuntmen that provided action scenes for  many Third Doctor episodes.',
   'walsh': 'Terry Walsh provided stunts for many Doctor Who episodes.',
   'yates': 'Captain Mike Yates was a regular character during the UNIT years.',
   'roger': 'Roger Delgado was the first actor to play The Master.',
   'derek': 'There have been lots of Dereks associated with Doctor Who, including Derek Ware who founded the stunt team HAVOC,',
   'grant': 'Jo Grant was a companion of the Third Doctor.',
   'first': 'William Hartnell played the First Doctor.',
   'third': 'Jon Pertwee played the Third Doctor.',
   'ogron': 'The Ogrons appeared as servants to the Daleks in Day of the Daleks and Frontier in Space.',
   'izlyr': 'Izlyr an Ice Warrior who appears in The Curse of Peladon',
   'alpha': 'Alpha Centauri is a diplomat who appears in The Curse of Peladon',
   'ssorg': 'Ssorg is an Ice Warrior who appears in the Curse of Peladon',
   'curse': 'The Curse of Peladon and The Curse of Fenric are both Doctor Who stories',
   'solos': 'Solos is an Earth Colony in The Mutants',
   'omega': 'Omega was a legendary Time Lord who created the supernova that powers Time Lord civilisation',
   'sarah': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'smith': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'robot': 'Robot was a Fourth Doctor Story',
   'baker': 'Tom Baker played the Fourth Doctor and Colin Baker played the Sixth Doctor.',
   'harry': 'Harry Sullivan was a companion of the Fourth Doctor.',
   'wirrn': 'The Wirrn were monsters that appeared in The Ark in Space.',
   'nerva': 'The Nerva Space Station features in both The Ark in Space and Revenge of the Cybermen.',
   'styre': 'Styre is the Sontaran in The Sontaran Experiment.',
   'miles': 'Peter Miles played several roles in Doctor Who including Davros\' assistant Nyder.',
   'kaled': 'The Daleks are mutated Kaleds.',
   'vogan': 'The Vogans are the inhabitants of the planet Voga in Revenge of the Cybermen.',
   'zygon': 'The Zygons appeared in Terror of the Zygons, The Day of the Doctor, The Zygon Invasion and The Zygon Inversion.',
   'kraal': 'The Kraals appeared in The Android Invasion.',
   'solon': 'Doctor Solon is the villain in The Brain of Morbius.',
   'leela': 'Leela was a companion to the Fourth Doctor.',
   'salem': 'Pamela Salem appeared in The Robots of Death and Remebrance of the Daleks',
   'taren': 'Taren Capel is the villain in The Robots of Death',
   'capel': 'Taren Capel is the villain in The Robots of Death',
   'greel': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'rutan': 'The Rutans are the deadly enemies of the Sontarans.',
   'titan': 'Titan Base is taken over by a sentient virus in The Invisible Enemy',
   'wanda': 'Wanda Ventham played several roles in Doctor Who appearing in The Faceless Ones, Image of the Fendahl and Time and the Rani.',
   'pluto': 'The Sun Makers is set on Pluto.',
   'ribos': 'The planet Ribos appears in the Ribos Operation.',
   'graff': 'Graff Vynda-K is the villain in the Ribos Operation.',
   'adams': 'Douglas Adams was a script editor on Doctor Who.',
   'zanak': 'Zanak is the Pirate Planet.',
   'diplos': 'The Great Seal of Diplos is the third segment of the Key to Time.',
   'kroll': 'Kroll is a giant squid from The Power of Kroll.',
   'dyall': 'Valentine Dyall played the Black Guardian.',
   'astra': 'Princess Astra of Atrios is the sixth segment of the Key to Time.',
   'lalla': 'Lalla Ward played Romana, companion to the Fourth Doctor.',
   'paris': 'Paris is the City of Death.',
   'erato': 'Erato was the Creature from the Pit.',
   'nimon': 'The Nimon are minotaur like creatures from The Horns of Nimon.',
   'aneth': 'Aneth is a planet in The Horns of Nimon.',
   'shada': 'Shada is an unbroadcast episode of Doctor Who.',
   'adric': 'Adric was a companion of the Fourth and Fifth Doctors.',
   'zargo': 'Zargo is one of the Three Who Rule, villains in State of Decay.',
   'aukon': 'Aukon is one of the Three Who Rule, villains in State of Decay.',
   'nyssa': 'Nyssa was a companion of the Fourth and Fifth Doctors.',
   'tegan': 'Tegan Jovanka was a companion of the Fourth and Fifth Doctors.',
   'janet': 'Janet Fielding played Tegan Jovanka, companion to the Fourth and Fifth Doctors.',
   };

