export const WORDSDICT: {[key:string]:string } = {
   'susan': 'Susan was is the Doctor\'s Grandaughter.',
   'delia': 'Delia Derbyshire composed the theme tune.',
   'waris': 'Waris Hussein was Doctor Who\'s first director.',
   'earth': 'Lots of stories are set on the planet Earth.',
   'dalek': 'The Daleks are the show\'s most famous monster.',
   'skaro': 'Skaro is the Dalek planet.',
   'terry': 'Terry Nation created the Daleks.',
   'david': 'There are lots of Davids associated with Doctor Who including David Whitaker the show\'s first story editor, David Brierly who voiced K9 and David Tennant who played the Tenth Doctor.',
   'marco': 'Marco Polo was the show\'s fourth story.',
   'voord': 'The alien Voord were the monsters in the Keys of Marinus.',
   'vicki': 'Vicki was a companion of the first Doctor.',
   'zarbi': 'The Zarbi were monters appearing in the episode The Web Planet.',
   'morok': 'The Morok\'s are the villains in The Space Museum.',
   'xeros': 'The Tardis visits the planet Xeros in The Space Museum.',
   'peter': 'There are lots of Peters associated with Doctor Who including, Peter Purves who played companion Steven Taylor, Peter Bryant producer, Peter Davison who played the Fifth Doctor and Peter Capaldi who played the Twelfth Doctor.',
   'rills': 'The Rills were aliens in Galaxy Four.',
   'maaga': 'Maaga was the villainous leader of the Drahvin in Galaxy Four.',
   'marsh': 'Jean Marsh played several roles in Doctor Who, including companion Sara Kingdom.',
   'mavic': 'Mavic Chen is the villain in The Daleks\' Masterplan.',
   'varga': 'Varga plants are deadly, but slow-moving, mobile plants from the planet Kembel.  It is also the name of an Ice Warrior.',
   'paddy': 'Paddy Russell was the first female director to work on Doctor Who.',
   'wiles': 'John Wiles was the second producer of Doctor Who.',
   'gerry': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'davis': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'gough': 'Michael Gough played the Celestial Toymaker and Councillor Hedin in Doctor Who.',
   'innes': 'Innes Lloyd was a Doctor Who producer.',
   'lloyd': 'Innes Lloyd was a Doctor Who producer.',
   'wyatt': 'Wyatt Earp appears in the Doctor Who story The Gunfighters.',
   'ringo': 'Johnny Ringo appears in the Doctor Who story The Gunfighters.',
   'wotan': 'WOTAN was an evil computer that appeared in The War Machines.',
   'wills': 'Anneke Wills played Polly, companion to the First and Second Doctors.',
   'polly': 'Polly was a companion of the first and second Doctors.',
   'craze': 'Michael Craze played Ben, companion to the First and Second Doctors.',
   'hines': 'Frazer Hines played Jamie, companion to the Second Doctor.',
   'jamie': 'Jamie McCrimmon was a companion of the Second Doctor.',
   'macra': 'The Macra are giant crab like monsters that appeared in both The Macra Terror and Gridlock.',
   'hulke': 'Malcolm Hulke wrote many episodes of Doctor Who and co-write The Making of Doctor Who with Terrance Dicks.',
   'telos': 'Telos is a Cyberman planet that featured in both Tomb of the Cybermen and Attack of the Cybermen.',
   'klieg': 'Eric Klieg is one of the villains in Tomb of the Cybermen.',
   'barry': 'Barry Letts was a producer and director of Doctor Who.',
   'letts': 'Barry Letts was a producer and director of Doctor Who.',
   'sonic': 'The Doctor often uses the Sonic Screwdriver to get him out of scrapes.',
   'wendy': 'Wendy Padbury played Zoe, companion to the Second Doctor.',
   'wheel': 'The Wheel is a space station where the Doctor met his companion Zoe.',
   'tenth': 'Mondas, home of the Cybermen, was once the tenth planet in the Earth\'s solar system (according to Doctor Who).',
   'dicks': 'Terrance Dicks was a Doctor Who write, script editor and prolific noveliser of Doctor Who stories.',
   'slaar': 'Slaar is an Ice Warrior who appears in The Seeds of Death.',
   'space': 'Doctor Who adventures in Time and Space.',
   'madoc': 'Philip Madoc appeared in four Doctor Who stories and in the Daleks\' Invasion Earth 2140 A.D. movie.',
   'auton': 'The Autons are plastic creatures controlled by the Nestene Consciousness.',
   'havoc': 'HAVOC was a team of stuntmen that provided action scenes for  many Third Doctor episodes.',
   'walsh': 'Bradley Walsh played companion Graham O\'Brien.',
   'yates': 'Captain Mike Yates was a regular character during the UNIT years.',
   'roger': 'Roger Delgado was the first actor to play The Master.',
   'derek': 'There have been lots of Dereks associated with Doctor Who, including Derek Ware who founded the stunt team HAVOC, Derek Jacobi who played the Master',
   'grant': 'Jo Grant was a companion of the Third Doctor.',
   'first': 'William Hartnell played the First Doctor.',
   'third': 'Jon Pertwee played the Third Doctor.',
   'ogron': 'The Ogrons appeared as servants to the Daleks in Day of the Daleks and Frontier in Space.',
   'izlyr': 'Izlyr an Ice Warrior who appears in The Curse of Peladon',
   'alpha': 'Alpha Centauri is a diplomat who appears in The Curse of Peladon',
   'ssorg': 'Ssorg is an Ice Warrior who appears in the Curse of Peladon',
   'curse': 'The Curse of Peladon, The Curse of Fenric, and the Curse of the Black Splot are all Doctor Who stories',
   'solos': 'Solos is an Earth Colony in The Mutants',
   'omega': 'Omega was a legendary Time Lord who created the supernova that powers Time Lord civilisation',
   'sarah': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'smith': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.  Matt Smith played the Eleventh Doctor.',
   'robot': 'Robot and Robot of Sherwood are both Doctor Who stories.',
   'baker': 'Tom Baker played the Fourth Doctor and Colin Baker played the Sixth Doctor.',
   'harry': 'Harry Sullivan was a companion of the Fourth Doctor.',
   'wirrn': 'The Wirrn were monsters that appeared in The Ark in Space.',
   'nerva': 'The Nerva Space Station features in both The Ark in Space and Revenge of the Cybermen.',
   'styre': 'Styre is the Sontaran in The Sontaran Experiment.',
   'miles': 'Peter Miles played several roles in Doctor Who including Davros\' assistant Nyder.',
   'kaled': 'The Daleks are mutated Kaleds.',
   'vogan': 'The Vogans are the inhabitants of the planet Voga in Revenge of the Cybermen.',
   'zygon': 'The Zygons appeared in Terror of the Zygons, The Day of the Doctor, The Zygon Invasion and The Zygon Inversion.',
   'kraal': 'The Kraals appeared in The Android Invasion.',
   'solon': 'Doctor Solon is the villain in The Brain of Morbius.',
   'leela': 'Leela was a companion to the Fourth Doctor.',
   'salem': 'Pamela Salem appeared in The Robots of Death and Remebrance of the Daleks',
   'taren': 'Taren Capel is the villain in The Robots of Death',
   'capel': 'Taren Capel is the villain in The Robots of Death',
   'greel': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'rutan': 'The Rutans are the deadly enemies of the Sontarans.',
   'titan': 'Titan Base is taken over by a sentient virus in The Invisible Enemy',
   'wanda': 'Wanda Ventham played several roles in Doctor Who appearing in The Faceless Ones, Image of the Fendahl and Time and the Rani.',
   'pluto': 'The Sun Makers is set on Pluto.',
   'ribos': 'The planet Ribos appears in the Ribos Operation.',
   'graff': 'Graff Vynda-K is the villain in the Ribos Operation.',
   'adams': 'Douglas Adams was a script editor on Doctor Who.',
   'zanak': 'Zanak is the Pirate Planet.',
   'diplos': 'The Great Seal of Diplos is the third segment of the Key to Time.',
   'kroll': 'Kroll is a giant squid from The Power of Kroll.',
   'dyall': 'Valentine Dyall played the Black Guardian.',
   'astra': 'Princess Astra of Atrios is the sixth segment of the Key to Time.',
   'lalla': 'Lalla Ward played Romana, companion to the Fourth Doctor.',
   'paris': 'Paris is the City of Death.',
   'erato': 'Erato was the Creature from the Pit.',
   'nimon': 'The Nimon are minotaur like creatures from The Horns of Nimon.',
   'aneth': 'Aneth is a planet in The Horns of Nimon.',
   'shada': 'Shada is an unbroadcast episode of Doctor Who.',
   'adric': 'Adric was a companion of the Fourth and Fifth Doctors.',
   'zargo': 'Zargo is one of the Three Who Rule, villains in State of Decay.',
   'aukon': 'Aukon is one of the Three Who Rule, villains in State of Decay.',
   'nyssa': 'Nyssa was a companion of the Fourth and Fifth Doctors.',
   'tegan': 'Tegan Jovanka was a companion of the Fourth and Fifth Doctors.',
   'janet': 'Janet Fielding played Tegan Jovanka, companion to the Fourth and Fifth Doctors.',
   'aztec': 'The Aztecs is a First Doctor story.',
   'reign': 'The Reign of Terro is a First Doctor story.',
   'roman': 'The Romans is a First Doctor story.',
   'chase': 'The Chase is a First Doctor story.',
   'power': 'The Power of the Daleks, The Power of Kroll and ... are all Doctor Who stories.',
   'enemy': 'The Enemy of the World and The Invisible Enemy are both Doctor Who stories.',
   'world': 'The Enemy of the World, The End of the World, World War Three, The Pyramid at the End of the World and World Enough and Time are all Doctor Who stories.',
   'seeds': 'The Seeds of Death and the Seeds of Doom are both Doctor Who stories.',
   'death': 'The Seeds of Death, The Ambassadors of Death, The Green Death, Death to the Daleks, The Robots of Death, City of Death, Death in Heaven and ... are all Doctor Who stories.',
   'games': 'The War Games is a Third Doctor story.',
   'claws': 'The Claws of Axos is Third Doctor Who story.',
   'three': 'The Three Doctors, World War Three and the Power of Three are all Doctor Who stories.',
   'green': 'The Green Death is a Third Doctor  story.',
   'brain': 'The Brain of Morbius is Fourth Doctor story.',
   'image': 'Image of the Fendahl is a Fourth Doctor story.',
   'blood': 'The Stones of Blood, The Family of Blood, Cold Blood and ... are all Doctor Who stories.',
   'taran': 'The Taran Wood Beast is a creature in the Androids of Tara.',
   'horns': 'The Horns of Nimon is a Fourth Doctor story.',
   'state': 'State of Decay is a Fourth Doctor story.',
   'decay': 'State of Decay is a Fourth Doctor story.',
   'fifth': 'The Fifth Doctor was played by Peter Davison.',
   'kinda': 'Kinda is a Fifth Doctor story.',
   'black': 'Black Orchid and The Curse of the Black Spot are both Doctor Who stories.',
   'kalid': 'Kalid is a disguise adopted by the Master in Time-Flight.',
   'ergon': 'The Ergon is a monster that appears in Arc of Infinity.',
   'hedin': 'Councillor Hedin is a villain in Arc of Infinity.',
   'maxil': 'Commander Maxil is a Time Lord played by future Doctor, Colin Baker.',
   'vanir': 'The Vanir work on the Terminus in the Fith Doctor episode Terminus.',
   'white': 'The White Guardian is the anthropomorphic personification of order and good.',
   'flood': 'Gerald Flood was the voice of Kamelion.',
   'orion': 'The Fifth Doctor often tried to get to the Eye of Orion, succeeding in The Five Doctors.',
   'malus': 'The Malus is the evil beneath the Church in The Awakening.',
   'brown': 'Peri Brown was a companion of the Fifth and Sixth Doctors.',
   'caves': 'The Caves of Androzani is a Fifth Doctor Episode.',
   'sixth': 'The Sixth Doctor was played by Colin Baker.',
   'colin': 'The Sixth Doctor was played by Colin Baker.',
   'remus': 'Romulus and Remus were the twins in The Twin Dilemma.',
   'cyron': 'The Cryons were a race in Attack of the Cybermen.',
   'banks': 'David Banks played many Cyber Leaders in the 1980s.',
   'varos': 'Varos is the planet in Vengeance on Varos.',
   'stike': 'Stike is a Sontaran in The Two Doctors.',
   'borad': 'The Borad is the villain in Timelash.',
   'selby': 'Tony Selby played Glitz in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'glitz': 'Glitz is a character in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'mccoy': 'Sylvester McCoy played the Seventh Doctor.',
   'delta': 'Delta and the Bannermen is a Seventh Doctor story.',
   'clown': 'The Chief Clown is a villian in The Greatest Show in the Galaxy.',
   'doris': 'Doris is the Brigadier\'s wife in Battlefield.',
   'ghost': 'Ghost Light and The Ghost Monument are both Doctor Who stories.',
   'light': 'Light on of the villains in Ghost Light.',
   'munro': 'Rona Munro wrote Survival the final story in the original run of Doctor Who.  She is the only write to have written for both the classic and the new series.',
   'grace': 'Grace Holloway was the Doctor\'s companion in the TV Movie.',
   'chang': 'Chang Lee was the Doctor (or the Master)\'s companion in the TV Movie.',
   'segal': 'Philip Segal was Executive Producer for the TV Movie.',
   'tyler': 'Rose Tyler was a of the Ninth and Tenth Doctors.',
   'ninth': 'The Ninth Doctor was played by Christopher Eccleston.',
   'piper': 'Billie Piper played Rose Tyler, companion.',
   'magma': 'The Magma Beast appeared in The Caves of Androzani.',
   'gelth': 'The Gelth are the villians in The Unquiet Dead.',
   'empty': 'The Empty Child is a Ninth Doctor story.',
   'child': 'The Doctor is the Timeless Child.',
   'chula': 'A Chula medical transport causes all the trouble in The Empty Child/The Doctor Dances.',
   'tooth': 'Tooth and Claw is a Tenth Doctor episode.',
   'finch': 'Mr Finch is the villain in School Reunion.',
   'lumic': 'John Lumic is the villain in Rise of the Cybermen and The Age of Steel.',
   'cybus': 'Cybus Industries creates the Cybermen in Rise of the Cybermen and The Age of Steel.',
   'steel': 'The Age of Steel is a Tenth Doctor story.',
   'beast': 'The Beast Below is an Eleventh Doctor story.',
   'satan': 'The Satan Pit is a Tenth Doctor story.',
   'elton': 'Elton is the viewpoint character in Love & Monsters.',
   'donna': 'Donna Noble was a companion of the Tenth Doctor.',
   'noble': 'Donna Noble was a companion of the Tenth Doctor.',
   'bride': 'The Runaway Bride is a Tenth Doctor story.',
   'santa': 'Robot Santas threaten the Doctor in the Christmas Invasion and the Runaway Bride.',
   'jones': 'Martha Jones was a companion of the Tenth Doctor.',
   'human': 'Human Nature is a Tenth Doctor story.',
   'watch': 'Time Lords seem to frequently hide their memories in pocket watches.',
   'blink': 'Blink is a Tenth Doctor episode.',
   'angel': 'The Weeping Angels are a popular Doctor Who Monster.',
   'sally': 'Sally Sparrow is the protagonist of Blink.',
   'saxon': 'Harold Saxon is the alias adopted by the Master in the Tenth Doctor\'s second series.',
   'sound': 'The Sound of Drums is a Tenth Doctor story.',
   'drums': 'The Sound of Drums is a Tenth Doctor story.',
   'lords': 'Last of the Time Lords is a Tenth Doctor story.',
   'crime': 'Partners in Crime is a Tenth Doctor story.',
   'fires': 'The Fires of Pompei is a Tenth Doctor story.',
   'alien': 'The Earth is frequently invaded by aliens in Doctor Who.',
   'staal': 'General Staal is a Sontaran in The Sontaran Stratagem.',
   'skorr': 'Commander Skorr is a Sontaran in The Sontaran Stratagem.',
   'jenny': 'Jenny is the Doctor\'s Daughter.',
   'river': 'River Song is the Doctor\'s wife.',
   'ianto': 'Ianto Jones was a series regular in the Torchwood Doctor Who spin-off and also appeared in The Stolen Earth and Journey\'s End.',
   'souza': 'Lady Christina de Souza acts as the companion in Planet of the Deat.',
   'karen': 'Karen Gillan played Amy Pond, companion.',
   'crack': 'The Eleventh Doctors first series is plagued by cracks in time and space.',
   'piers': 'Piers Wenger was an executive producer of Doctor Who.',
   'below': 'The Beast Below was an Eleventh Doctor episode.',
   'whale': 'A Star Whale is carrying Starship UK in the Beast Below.',
   'flesh': 'Flesh and Stone and The Rebel Flesh are both Eleventh Doctor stories.',
   'stone': 'Flesh and Stone is an Eleventh Doctor episode.',
   'paper': 'The Doctor often uses Psychic Paper to get past officials.',
   'dream': 'The Dream Lord is a manifestation of the Doctor\'s subconscious.  Dream Crabs attach the characters in Last Christmas.',
   'alaya': 'Alaya is a Silurian in the The Hungry Earth and Cold Blood.',
   'opens': 'The Pandorica Opens is an Eleventh Doctor story.',
   'carol': 'A Christmas Carol is an Eleventh Doctor story.',
   'nixon': 'President Richard Nixon appears in The Impossible Astronaut and Day of the Moon.',
   'avery': 'Pirate Henry Avery appears in The Curse of the Black Spot and is mentioned in The Smugglers.',
   'idris': 'Idris is a personification of the Tardis in The Doctor\'s Wife.',
   'house': 'House is the villain in The Doctor\'s Wife.',
   'rebel': 'The Rebel Flesh is an Eleventh Doctor story.',
   'flint': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'strax': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'night': 'Night Terrors, In the Forest of the Night and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'widow': 'The Doctor, the Widow and the Wardrobe is an Eleventh Doctor story.',
   'madge': 'Madge Arwell is the Widow in the Doctor, the Widow and the Wardrobe.',
   'clara': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'oswin': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'mercy': 'A Town called Mercy is an Eleventh Doctor story.',
   'jemma': 'Jemma Redgave places Kate Stewart, the head of UNIT.',
   'bells': 'The Bells of Saint John is an Eleventh Doctor story.',
   'saint': 'The Bells of Saint John is an Eleventh Doctor story.',
   'shard': 'The Shard is the base of the Great Intelligence in The Bells of Saint John.',
   'great': 'The Great Intelligence is a recurring enemy of the Doctor.',
   'helix': 'The Mandragora Helix is the enemy in the Masque of Mandragora.',
   'rings': 'The Rings of Akhaten is an Eleventh Doctor story.',
   'sweet': 'Mr Sweet is a villain in The Crimson Horror.',
   'ohila': 'Ohila is the leader of the Sisterhood of Karn in Night of the Doctor, The Magician\'s Apprentice and Hell Bent.',
   'papal': 'The Papal Mainframe is the headquarters of the militarised Church.',
   'siege': 'The Time of the Doctor is about the Siege of Trenzalore.',
   'missy': 'Missy is the Doctor\'s arch enemy.',
   'gomez': 'Michelle Gomez played Missy.',
   'jenna': 'Jenna Coleman played companion Clara Oswald.',
   'rusty': 'Rusty is a \"good\" Dalek.',
   'robin': 'Robin Hood appears in Robot of Sherwood.',
   'brian': 'There have been several Brian\'s associated with Doctor Who included Brian Hayles who created the Ice Warriors and executive producer Brian Minchin.',
   'heist': 'Time Heist is a Twelfth Doctor story.',
   'mummy': 'Mummy on the Orient Express is a Twelfth Doctor story.',
   'rigsy': 'Rigsy appears in Flatline and Face the Raven.',
   'danny': 'Danny Pink is Clara Oswald\'s boyfriend.',
   'water': 'Dark Water is a Twelfth Doctor story.',
   'claus': 'Santa Claus appears in Last Christmas.',
   'sarff': 'Colony Sarff is a servant of Davros in The Magician\'s Apprectice and the Witch\'s Familiar.',
   'under': 'Under the Lake is a Twelfth Doctor story.',
   'woman': 'The Woman who Lived and the Woman who Fell to Earth are both Doctor Who stories.',
   'lived': 'The Woman who Lived is a Twelfth Doctor story.',
   'truth': 'Truth or Consequences is a town occupied by Zygons in The Zygon Invasion.',
   'sleep': 'Sleep No More is a Twelfth Doctor story.',
   'rheum': 'The Sandmen monstersin Sleep No More are made from rheum.',
   'raven': 'Face the Raven is a Twelfth Doctor story.',
   'shade': 'A Quantum Shade takes the form of a raven and deals out justice in Face the Raven.',
   'lucas': 'Matt Lucas played companion Nardole.',
   'pilot': 'The Pilot is a Twelfth Doctor story.',
   'potts': 'Bill Potts was a companion to the Twelfth Doctor.',
   'pearl': 'Pearl Mackie played companion Bill Potts.',
   'vault': 'In his final series, the Twelfth Doctor keeps Missy locked in a vault.',
   'smile': 'Smile is a Twelfth Doctor story.',
   'vardy': 'The Nano-bot Vardy are the monsters in Smile.',
   'frost': 'Thin Ice takes place at a Frost Fair on the Thames.',
   'knock': 'Knock Knock is a Twelfth Doctor story.',
   'dryad': 'Dryad beetles are the monsters in Knock Knock.',
   'eater': 'The Eater of Light is the monster in The Eaters of Light.',
   'razor': 'The Master disguises himself as Razor in World Enough and Time.',
   'twice': 'Twice Upon a Time is a Twelfth Doctor story.',
   'jodie': 'Jodie Whittaker plays the Thirteenth Doctor.',
   'tosin': 'Tosin Cole played companion Ryan Sinclair.',
   'chris': 'Chris Chibnall is the current Doctor Who showrunner.  Christopher Eccleston played the Ninth Doctor.',
   'segun': 'Segun Akinola currently composes the music for Doctor Who.',
   'parks': 'The Doctor Who story Rosa is about activist Rosa Parks.',
   'pting': 'The Pting is the monster in The Tsuranga Conundrum.',
   'india': 'The Demons of the Punjab is about the Partition of India.',
   'witch': 'The Doctor is tried as a witch in The Witchfinders',
   'james': 'King James I of England and VI of Scotland appears in The Witchfinders.',
   'morax': 'The Morax are the villains in The Witchfinders.',
   'takes': 'It Takes You Away is a Thirteenth Doctor story.',
   'kolos': 'The Battle of Ranskoor Av Kolos is a Thirteenth Doctor story.',
   'sacha': 'Sacha Dhawan played The Master during the Thirteenth Doctor series.',
   'tesla': 'Nikola Tesla\'s Night of Terror is a Thirteenth Doctor story.',
   'class': 'Class is a Doctor Who spin-off show set in Cole Hill School.',
   'anjli': 'Anjli Mohindra played Rani and the Sarah Jane Adventures and the Queen Skithra in Nikola Tesla\'s Night of Terror.',
   'villa': 'The Haunting of Villa Diodati is a Thirteenth Doctor story.',
   'byron': 'Lord Byron appears in the Haunting of Villa Diodati.',
   'ashad': 'Ashad is the lone Cyberman.',
   'lewis': 'Dan Lewis is a companion of the Thirteenth Doctor.',
   'swarm': 'Swarm is one of the villains in Flux.',
   'azure': 'Azure is one of the villains in Flux.',
   };

