export const WORDSDICT: {[key:string]:string } = {
   'vulcan': 'Vulcan is the planet in Power of the Daleks.',
   'rorvik': 'Rorvik is the villain in Warriors\' Gate.',
   'simeon': 'Dr Simeon is taken over by the Great Intelligence in The Snowmen which continues to use his body in The Name of the Doctor.',
   'romans': 'The Romans is a first Doctor story.',
   'hepesh': 'Hepesh is the high priest of Peladon in The Curse of Peladon.',
   'tekker': 'Tekker is the ambitious leader of Karfel in Timelash.',
   'pangol': 'Pangol is the villain in The Leisure Hive.',
   'london': 'Aliens of London is a ninth Doctor story.',
   'kazran': 'Kazran is the antagonist in A Christmas Carol.',
   'arwell': 'The Doctor, the Widow and the Wardrobe centres around the Arwell family.',
   'finney': 'Yasmin Finney will play Rose in the Doctor Who specials in 2023.',
   'tetrap': 'The Tetraps serve the Rani in Time and the Rani.',
   'inayat': 'The Doctor meets Noor Inayat Khan in Spyfall.',
   'traken': 'The Keeper of Traken is a fourth Doctor story.',
   'purves': 'Peter Purves played companion Steven Taylor.',
   'nunton': 'The Nunton Experimental Complex is the setting for much of The Hand of Fear.',
   'orchid': 'Black Orchid is a fifth Doctor story.',
   'duggan': 'Duggan is a detective, somewhat prone to smashing things, in City of Death.',
   'billie': 'Billie Piper played companion Rose Tyler.',
   'hoothi': 'In The Brain of Morbius the Sisterhood of Karn claim to be able to detect the silent gas dirigibles of the Hoothi.',
   'henrik': 'At the start of the modern series, Rose works in Henrik\'s department store.',
   'mandip': 'Mandip Gill played companion Yaz Khan.',
   'daniel': 'Daniel Barton, played by Lenny Henry is the antagonist in Spyfall.',
   'marter': 'Ian Marter played companion Harry Sullivan.',
   'ogrons': 'Ogrons are the servants of the Daleks.',
   'jarvis': 'Jarvis Bennet is controller of the Wheel in Space.',
   'morgus': 'Morgus is the villain in The Caves of Androzani.',
   'planet': 'Planet of Giants, The Web Planet, The Tenth Planet, Planet of the Daleks, Planet of the Spiders, Planet of Evil, The Pirate Planet, Planet of Fire, The Mysterious Planet, The Impossible Planet, Planet of the Ood, and Planet of the Dead are all Doctor Who stories.',
   'minyan': 'The Minyans come from Minyos.',
   'wright': 'Barbara Wright was a companion to the first Doctor.',
   'sutekh': 'Sutekh the Destroyer is the villain in Pyramids of Mars.',
   'morton': 'Peter Purves appears as annoying tourist Morton Dill in The Chase before reappearing as new companion Steven Taylor later in the same story.',
   'wenley': 'Wenley Moor Nuclear Research Facility appears in The Silurians.',
   'kaleds': 'The Daleks are mutated Kaleds.',
   'called': 'A Town Called Mercy is an eleventh Doctor story.',
   'millie': 'Millie Gibson played companion Ruby Sunday.',
   'osiran': 'Sutekh from the Pyramids of Mars is an Osiran.',
   'moffat': 'Steven Moffat was the showrunner for the eleventh and twelfth Doctor series.',
   'canary': 'The Battle of Canary Wharf between the Daleks and the Cybermen takes place during Doomsday.',
   'bubble': 'In Kerblam! Charlie Duffy plans to discredit the company using weaponised bubble wrap.',
   'verity': 'Verity Lambert was the first producer of Doctor Who.',
   'spiral': 'Mutter\'s Spiral seems to be a synonym for the Milky Way.',
   'newman': 'Doctor Who was the brain child of Syndney Newman.',
   'zombie': 'Time Zombies appear in Journey to the Centre of the TARDIS.',
   'poison': 'The Poison Sky is a tenth Doctor story.',
   'mickey': 'Mickey Smith is Rose\'s boyfriend and briefly a companion of the Doctor.',
   'flight': 'Time-Flight is a fifth Doctor story.',
   'aliens': 'Aliens of London is a ninth Doctor story.',
   'davies': 'Russell T Davies was the showrunner who brought back Doctor Who.',
   'kroton': 'The Krotons are the monsters in The Krotons.',
   'undead': 'Mawdryn Undead is a fifth Doctor story.',
   'josiah': 'Josiah Smith seeks to assassinate Queen Victoria in Ghost Light.',
   'acteon': 'Metebelis 3 is the famous blue planet in the Acteon Galaxy.',
   'temple': 'Donna marries Sean Temple.',
   'gilles': 'In the King\'s Demons, the Master disguises himself as Sir Gilles Estram.',
   'tharil': 'The Tharils are time sensitives in Warriors\' Gate.',
   'minyos': 'The planet Minyos was destroyed after the Time Lords interfered with its development.',
   'angels': 'The Time of Angels, The Angels Take Manhattan and Village of the Angels are all Doctor Who stories.',
   'garron': 'Garron and Unstoffe are a criminal duo in The Ribos Operation.',
   'ingrid': 'Ingrid Oliver plays Osgood - UNIT Scientist and Zygon.',
   'ganger': 'The Gangers are human controlled Doppelgangers created from the Flesh.',
   'covent': 'WOTAN builds War Machines in a Warehouse near Covent Garden in The War Machines.  The travellers land at the tube station in The Web of Fear.',
   'puddle': 'Bill\'s girlfriend Heather is taken over by puddle of sentient engine oil.',
   'nicola': 'Nicola Bryant played companion Peri Brown.',
   'museum': 'The Space Museum is a first Doctor story.',
   'murray': 'Murray Gold composed Doctor Who\'s incidental music from the start of the ninth Doctor\'s episodes to the end of the twelfth.',
   'rakaya': 'Zellin and Rakaya are the immortal villains in Can You Hear Me?',
   'nimrod': 'Nimrod is a neanderthal acting as a manservant in Ghost Light.',
   'bysshe': 'The Doctor meets Percey Bysshe Shelley in the The Haunting of Villa Diodati.',
   'dryads': 'The Dryads are beetle creatures that live in the house in Knock Knock.',
   'pocket': 'In Human Nature and Family of Blood the Doctor transfers his Time Lord essence into a Pocket Watch.',
   'broton': 'Broton is the leader of the Zygons in Terror of the Zygons.',
   'dulkis': 'Dulkis is the planet invaded by the Dominators.',
   'melkur': 'The Melkur is a disguise for the Master\'s Tardis in The Keeper of Traken.',
   'aztecs': 'The Aztecs was a first Doctor story.',
   'george':  'A Tenza child becomes the terrified George in Night Terrors.',
   'rounds': 'The Brigadier famously said \'chap with wings, five rounds rapid.\'.',
   'stubbs': 'Stubbs and Cotton are two sympathetic guards in The Mutants.',
   'yartek': 'Yartek is leader of the alien Voord.',
   'cryons': 'The Cryons lived on Telos before the Cybermen came.',
   'krasko': 'Krasko is the antagonist in Rosa.',
   'chiang': 'The Talons of Weng-Chiang is a fourth Doctor story.',
   'jackie': 'Jackie Lane played companion Dodo Chaplet.',
   'orphan': 'Orphan 55 is a thirteenth Doctor story.',
   'factor': 'The Armageddon Factor is a fourth Doctor story.',
   'makers': 'The Myth Makers and the Sun Makers are both Doctor Who stories.',
   'autons': 'The Autons are monsters appearing in Spearhead from Space, Terror of the Autons and Rose.',
   'giants': 'Planet of Giants was a first Doctor story.',
   'tobias': 'Tobias Vaughn is the villian in The Invasion.',
   'forest': 'Forest of the Dead and In the Forest of the Night are both Doctor Who stories.',
   'detsen': 'The Detsen Monastery is where the Doctor first meets the Yeti in The Abominable Snowmen.',
   'shirna': 'Vorg and Shirna bring a miniscope to Inter Minor in Carnival of Monsters.',
   'zondal': 'Zondal is an Ice Warrior in The Ice Warriors.',
   'celery': 'The Fifth Doctor wore a stick of celery on his lapel.',
   'cutler': 'General Cutler is the leader of Snowcap Base in The Tenth Planet.',
   'tardis': 'The TARDIS is the Doctor\'s space and time machine.',
   'crater': 'The Menoptera were kept prisoners by the Zarbi in the Crater of Needles.',
   'fariah': 'Fariah is the villain Salamander\'s food taster in Enemy of the WOrld.  She is killed helping Jamie and Victoria escape.',
   'merlin': 'In Battlefied it is revealed that a future Doctor is Merlin.',
   'gerald': 'Gerald Flood voiced Kamelion.',
   'gracht': 'Count Grendal of Gracht is the villain in The Androids of Tara.',
   'matrix': 'The Matrix on Gallifrey holds the combined knowledge of the Time Lords.',
   'ursula': 'Ursula Blake is Elton Pope\'s love interest in Love and Monsters.',
   'saward': 'Eric Saward script-edited Doctor Who.',
   'nikola': 'Nikola Tesla\'s Night of Terror is a thirteenth Doctor story.',
   'patrol': 'The Happiness Patrol is a seventh Doctor story.',
   'donald': 'Donald Tosh script-edited Doctor Who.',
   'adeola': 'Martha\'s cousin Adeola appears in Army of Ghosts, also played by Freema Agyeman.',
   'fungus': 'In the Seeds of Death the Ice Warriors release a fungus to remove the Oxygen from the Earth.',
   'random': 'In Extremis the simulation\'s inhabitants work out they are simulations because they all pick the same random number.',
   'legion': 'In The Eaters of Light the remains of the Roman Ninth Legion help hold back the Eater inside a pictish cairn.',
   'quarks': 'The Quarks are the robot servants of the Dominators.',
   'vashta': 'The Vashta Nerada are the monsters in Silence in the Library and Forest of the Dead.',
   'tomtit': 'TOMTIT is a device for manipulating time in The Time Monster.',
   'marius': 'Professor Marius created K9',
   'listen': 'Listen is a twelfth Doctor story.',
   'zygons': 'Terror of the Zygons is a fourth Doctor story.',
   'skulls': 'The Tardis crew are held captive in the Cave of Skulls in An Unearthly Child.',
   'lupari': 'Karvanista in Flux is a member of the Lupari race.',
   'hitler': 'Let\'s Kill Hitler is an eleventh Doctor story.',
   'artron': 'Artron Energy is a form of mental energy utilised by the Time Lords.',
   'wester': 'We first meet the Weeping Angels in an abandoned house in Wester Drumlins.',
   'sharon': 'Amy Pond is raised by her Aunt Sharon after her parents disappear into the crack in her wall.',
   'global': 'Global Chemicals is the source of the contamination that causes the Green Death.',
   'hybrid': 'There is a Gallifreyan Prophesy that a hybrid creature would stand over the ruins of Gallifrey and unravel the Web of Time.  The creature is referred to as The Hybrid.',
   'earpod': 'The Cybermen use EarPods to take control of people in Rise of the Cybermen.',
   'levene': 'Jon Levene played UNIT sergeant Benton.',
   'skovox': 'The Skovox Blitzer is the monster in The Caretaker.',
   'source': 'The Source is a terraforming device in The Doctor\'s Daughter.',
   'rescue': 'The Rescue is a first Doctor story.',
   'skagra': 'Skagra is the villain in the untransmitted story Shada.',
   'robert': 'Robert Holmes script-edited Doctor Who.',
   'powell': 'Rose and her Mum live on the Powell Estate.',
   'dances': 'The Doctor Dances is a ninth Doctor story.',
   'babies': 'The Doctor is well known for handing out Jelly Babies.',
   'agatha': 'The Doctor meets Agatha Christie in the Unicorn and the Wasp.',
   'tahira': 'Tahira helps the Doctor in Can You Hear Me?',
   'lodger': 'The Lodger is an eleventh Doctor story.',
   'oxygen': 'Oxygen is a twelfth Doctor story.',
   'vaughn': 'Tobias Vaughn is the villian in The Invasion.',
   'daemon': 'Azal is a Daemon.',
   'leeson': 'John Leeson voiced K9.',
   'fenric': 'The Curse of Fenric is a seventh Doctor story.',
   'scroll': 'The Black Scrolls of Rassilon reveal the secrets of the Death Zone  on Gallifrey.',
   'horror': 'Horror of Fang Rock and The Crimson Horror are both Doctor Who stories.',
   'damned': 'Voyage of the Damned is a tenth Doctor story.',
   'venice': 'The Vampires of Venice is an eleventh Doctor story.',
   'rosita': 'Rosita Farisi is Jackson Lake\'s companion in the Next Doctor.',
   'manish': 'Manish is the antagonist in Demons of the Punjab.',
   'kembel': 'Kembel is the planet where the Daleks assemble their alliance in the Daleks\' Masterplan.',
   'joanna': 'Jean Marsh plays Richard the Lionheart\'s sister Joanna in The Crusade.',
   'savage': 'Becka Savage, landowner, magistrate and prosecutor of witch trials, is taken over by the Morax in The Witchfinders.',
   'kronos': 'Kronos the Chronovore appears in The Time Monster.',
   'moment': 'The Doctor contemplates using the Moment to end the Time War.',
   'dibber': 'Dibber is Glitz\'s partner in The Mysterious Planet.',
   'bessie': 'The Third Doctor\'s Edwardian Roadster is called Bessie.',
   'lupton': 'Lupton is the villain in Planet of the Spiders',
   'gurney': 'Smallbeer, Ringwood, Gurney - names on gravestones - are the clue to the location of Avery\'s treasure in The Smugglers.',
   'vivien': 'Vivien Fay is the identity assumed by Cessair of Diplos in The Stones of Blood.',
   'masque': 'The Masque of Mandragora is a fourth Doctor story.',
   'vacuum': 'Travel between E-Space and N-Space is possible through Charged Vaccuum Emboitments.',
   'estram': 'In the King\'s Demons, the Master disguises himself as Sir Gilles Estram.',
   'kassia': 'Kassia is Nyssa\'s step-mother and pawn of the Master in The Keeper of Traken.',
   'allons': 'The Tenth Doctor often said Allons-y.',
   'frazer': 'Frazer Hines played companion Jamie.',
   'sauvix': 'Sauvix is the Sea Devil leader in Warriors of the Deep.',
   'martin': 'Jo Martin plays the Fugitive Doctor in Fugitive of the Judoon.',
   'dragon': 'Dragonfire, the Key to the Iceworld space ship, is protected inside the Dragon\'s head.',
   'ramone': 'Ramone is one of River Song\'s husbands in the Husbands of River Song.',
   'hobbes': 'Professor Hobbes and his student Dee Dee Biasco are two of the shuttle passengers in Midnight.',
   'spider': 'Giant Spiders are the monsters in Planet of the Spiders',
   'matron': 'Matron Casp is the villain in New Earth and Matron Cofelia is the villain in Partners in Crime.',
   'mondas': 'Mondas is the home of the Cybermen.',
   'jensen': 'Rachel Jensen is scientific advisor to the Intrusion Counter Measures group in Rememberance of the Daleks.',
   'zellin': 'Zellin and Rakaya are the immortal villains in Can You Hear Me?',
   'devils': 'The Sea Devils and Legend of the Sea Devils are both Doctor Who stories.',
   'robber': 'The Mind Robber is a second Doctor story.',
   'moroks': 'The Moroks are the rulers of Xeros in the Space Museum.',
   'andred': 'Leela, rather implausbily, leaves the Doctor to marry Andred.',
   'choice': 'Amy\'s Choice is an eleventh Doctor story.',
   'estate': 'Tooth and Claw takes place on the Torchwood Estate.',
   'ballad': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'tivoli': 'Tivoli is the most invaded planet in the galaxy.',
   'hamish': 'The Brigadier\'s grandfather is Archibald Hamish Lethbridge-Stewart.',
   'ortron': 'Ortron is Chancellor of Peladon in The Monster of Peladon.',
   'cotton': 'Stubbs and Cotton are two sympathetic guards in The Mutants.',
   'circus': 'The Doctor and Ace visit the Psychic Circus in The Greatest Show in the Galaxy.',
   'briggs': 'Nick Briggs voices the Daleks in the modern Doctor Who series.',
   'andrew': 'Andrew Cartmel script-edited Doctor Who.',
   'static': 'In The Daleks the Daleks need static electricty to move.  In Evil of the Daleks Maxtible and Waterfield accidentally bring the Daleks to Earth when trying to invent a time machine using mirrors and static electricity.',
   'church': 'The Church on Ruby Road is a Fifteenth Doctor story.',
   'master': 'The Master is the Doctor\'s Arch enemy.',
   'utopia': 'Utopia is a tenth Doctor story.',
   'elders': 'The Elders govern the parasitic civilisation in The Savages.',
   'daphne': 'Daphne Ashbrook played companion Grace.',
   'kahler': 'The Aliens in A Town called Mercy are both Kahler.',
   'asgard': 'The Doctor and River Song had a picnic at Asgard.',
   'almost': 'The Almost People is an eleventh Doctor story.',
   'osgood': 'Corporal Osgood is a UNIT Technical Officer in The Daemons.  Petronella Osgood who may (or may not) be related, is UNIT\'s Scientific Advisor under Kate Stewart.',
   'mentor': 'The Mentors, including Sil and Kiv, control Thoros Beta in Mindwarp.',
   'edison': 'Thomas Edison appears as an antagonist in Nikola Tesla\'s Night of Terror.',
   'deadly': 'The Deadly Assassin is a fourth Doctor story.',
   'vogans': 'The Vogans appear in Revenge of the Cybermen.',
   'pirate': 'The Pirate Planet is a fourth Doctor story.',
   'bellal': 'The Exxilon Bellal helps the Doctor in Death to the Daleks.',
   'gadget': 'Gadget the Robot appears in The Waters of Mars.',
   'keller': 'The Keller machine holds the Mind of Evil.',
   'brooke': 'Adelaide Brooke is a pseudo-companion in The Waters of Mars.',
   'teller': 'In Time Heist the Doctor and his friends rescue The Teller.',
   'aldred': 'Sophie Aldred played companion Ace.',
   'beetle': 'A Time Beetle appears in Turn Left.',
   'yetaxa': 'In the Aztecs, Barbara is mistaken for a reincarnation of the high priest Yetaxa.',
   'saucer': 'The Dalek Saucer appears in The Dalek Invasion of Earth.',
   'carrot': 'Mel makes the Doctor drink carrot juice.',
   'gundan': 'The Gundan robots were designed to travel the time winds and destory the brutes who rule in Warriors\' Gate.',
   'heaven': 'Death in Heaven and Heaven Sent are both Doctor Who stories.',
   'things': 'The Journal of Impossible Things was a dream diary kept by the Tenth Doctor\'s human persona, John Smith, in The Family of Blood.',
   'gordon': 'Alister Gordon Lethbridge-Stewart is the Brigadier\'s full name.',
   'corral': 'The events of The Gunfighters lead up to the gunfight at the O.K. Corral.',
   'qurunx': 'The Qurunx is an energy being enslaved by the Master in The Power of the Doctor.',
   'hydrax': 'The Tower of the Lords in State of Decay is actually the spaceship Hydrax.',
   'alaska': 'Oswin, one of the fragments of Clara, thought she was a survivor of the crash of the Alaska into the Dalek prison planet.',
   'hungry': 'The Hungry Earth is an eleventh Doctor story.',
   'daleks': 'The Daleks are the Doctor\'s arch enemies and first appear in The Daleks.',
   'kraals': 'The Kraals appear in The Android Invasion.',
   'zucker': 'Mels Zucker is a friend of Amy and Rory who turns out to be an early incarnation of River Song.',
   'novice': 'Novice Hame is a Cat Nun who appears in New Earth and Gridlock.',
   'azmael': 'Azmael is an old friend of the Doctor\'s forced to help the evil giant Gastropods in The Twin Dilemma.',
   'bonnie': 'Bonnie Langford played companion Mel Bush.',
   'kaldor': 'Kaldor is a desert planet in The Robots of Death.',
   'mirror': 'Mirrors form the interface between E-Space and N-Space in Warriors\' Gate.',
   'galaxy': 'Galaxy 4 and The Greatest Show in the Galaxy are both Doctor Who stories.',
   'jungle': 'The Tardis crew find one of the keys to the Conscience of Marinus in the Screaming Jungle.',
   'iraxxa': 'Iraxxa is the Empress of the Ice Warriors.',
   'lilith': 'Lilith is the main Carrionite in The Shakespeare Code.',
   'towers': 'Paradise Towers is a seventh Doctor story.',
   'kizlet': 'Miss Kizlet is the front for the Great Intelligence in the Bells of St. John.',
   'victor': 'Victor Pemberton script-edited Doctor Who.',
   'keeper': 'The Keeper of Traken is a fourth Doctor story.',
   'clever': 'Run you clever boy and remember me.',
   'dorium': 'Dorium Maldovar was a somewhat unwilling ally of the eleventh Doctor.',
   'mcgann': 'Paul McGann played the Eighth Doctor.',
   'foster': 'Mrs Foster is the Adipose Nanny in Partners in Crime.',
   'louise': 'Louise Jameson played companion Leela.',
   'kublai': 'The Doctor meets Kublai Khan in Marco Polo.',
   'yasmin': 'Yasmin Khan was a companion of the thirteenth Doctor.',
   'thames': 'The Racnoss Empress is hidden under the Thames Barrier.',
   'robson': 'Robson is in charge of the gas refinery in Fury from the Deep.',
   'terror': 'The Reign of Terror, The Macra Terror, Terror of the Autons, Terror of the Zygons, Terror of the Vervoids, and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'sphere': 'The Sense Sphere (from the Sensorites) and the Ood Sphere (from Planet of the Ood) are both planets.',
   'chance': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'reaper': 'The Reapers appear where paradoxes arise.',
   'necros': 'Revelation of the Daleks is set on the planet Necros in the funeral home Tranquil Repose.',
   'doctor': 'Doctor Who?',
   'nerada': 'The Vashta Nerada are the monsters in Silence in the Library and Forest of the Dead.',
   'cicero': 'Eve Cicero is a renowned general who dies to save the Tsuranga in The Tsuranga Conundrum.',
   'giggle': 'The Giggle is a Fourteenth Doctor story.',
   'atraxi': 'The Atraxi appear in The Eleventh Hour.',
   'editor': 'The Editor runs Satellite 5 for the Jagrafess in The Long Game.',
   'puzano': 'Belle leaves a message for Vinder on Puzano in Village of the Angels.',
   'karkus': 'The Karkus was a fictional superhero from Zoe\'s time who appears as a character in The Mind Robber.',
   'kelner': 'Castellan Kelner serves the invaders of Gallifrey in The Invasion of Time.',
   'eighth': 'Paul McGann played the Eighth Doctor.',
   'eaters': 'The Eaters of Light is a twelfth Doctor story.',
   'thoros': 'Mindwarp takes place on Thoros Beta.',
   'sydney': 'Doctor Who was the brain child of Syndney Newman.',
   'skasis': 'The Skasis Paradigm is the mathematical equation behind the way the universe works.',
   'shoals': 'In The Return of Doctor Mysterio, the Doctor is investigating the company Harmony Shoals.',
   'heriot': 'Zoe Heriot was a companion to the second Doctor.',
   'biasco': 'Professor Hobbes and his student Dee Dee Biasco are two of the shuttle passengers in Midnight.',
   'gibson': 'Millie Gibson played companion Ruby Sunday.',
   'legend': 'Legend of the Sea Devils and the Legend of Ruby Sunday are both Doctor Who stories.',
   'police': 'The Tardis is disguised as a Police Public Call Box.',
   'waters': 'The Waters of Mars is a tenth Doctor story.',
   'oliver': 'Ingrid Oliver plays Osgood - UNIT Scientist and Zygon.',
   'stenza': 'Tzim-Sha in the Woman who Fell to Earth is a Stenza.',
   'bishop': 'John Bishop played companion Dan.',
   'cosmic': 'The Second Doctor was envisioned as a Cosmic Hobo.',
   'anneke': 'Anneke Wills played companion Polly.',
   'cromer': 'The Brigadier mistakes Omega\'s realm for Cromer in The Three Doctors.',
   'alfava': 'The Time of Angels and Flesh and Stone take place on the planet Alfava.',
   'vinder': 'Vinder was a recurring character in Flux.',
   'hobson': 'Hobson is the base commander in The Moonbase.',
   'saloon': 'The Ballad of the Last Chance Saloon provides a musical backdrop to The Gunfighters.',
   'animus': 'The Animus is the enemy in the Web Planet.',
   'nature': 'Human Nature is a tenth Doctor story.',
   'voyage': 'Voyage of the Damned is a tenth Doctor story.',
   'breath': 'Deep Breath is a twelfth Doctor story.',
   'smiler': 'The Winders were the police force of Starship UK.  They were half-human half-Smiler cyborgs.',
   'demnos': 'The Cult of Demnos were used by the Mandragora Helix in The Masque of Mandragora.',
   'mestor': 'Mestor is the leader of the Giant Gastropods in The Twin Dilemma.',
   'khalid': 'The Master disguises himself as Khalid in Time Flight.',
   'orient': 'Mummy on the Orient Express is a twelfth Doctor story.',
   'cooper': 'Gwen Cooper appears in the Stolen Earth and Journey\'s End as well as being one of the main characters in Torchwood.',
   'tremas': 'Tremas is Nyssa\'s father in The Keeper of Traken.  His body is taken over by the Master.',
   'hazran': 'Hazran is a Mondasian who takes a liking to Nardole in The Doctor Falls.',
   'asylum': 'Asylum of the Daleks is an eleventh Doctor story.',
   'jacobi': 'Derek Jacobi played Professor Yana who was revealed as the Master.',
   'canton': 'Canton Everett helps the Doctor in The Impossible Planet and Day of the Moon.',
   'xerons': 'The Xerons appear the The Space Museum.',
   'carole': 'Carole Ann Ford played Susan, the Doctor\'s granddaughter.',
   'vastra': 'Madame Vastra is a Silurian who leads the Paternoster Gang.',
   'yonder': 'Wild Blue Yonder is a Fourteenth Doctor Story.',
   'sophie': 'Sophie Aldred played companion Ace.',
   'optera': 'The Optera are caterpillar-like relatives of the Menoptera in the Web Planet.',
   'gavrok': 'Gavrok leads the Bannermen in Delta and the Bannermen.',
   'guitar': 'The Twelfth Doctor often played a guitar.',
   'judoon': 'Fugitive of the Judoon is a thirteenth Doctor story.',
   'styles': 'Day of Daleks involves time travellers attempting to assassinate diplomat Sir Reginald Styles.',
   'gravis': 'Gravis is the leader of the Tractators in Frontios.',
   'cameca': 'The Doctor accidentally becomes engaged to Cameca in The Aztecs.',
   'empire': 'Empire of Death is a Fifteenth Doctor story.',
   'winder': 'The Winders were the police force of Starship UK.  They were half-human half-Smiler cyborgs.',
   'walker': 'In the TV Movie the Doctor is taken to Walker General Hospital.',
   'dukkha': 'Dukkha is a representation of the Mara in Kinda.',
   'vislor': 'Vislor Turlough was a companion to the fifth Doctor.',
   'amelia': 'Amy Pond is called Amelia in her childhood.',
   'davros': 'Davros is the creater of the Daleks.',
   'before': 'Before the Flood is a twelfth Doctor story.',
   'demons': 'The King\'s Demons and Demons of the Punjab are both Doctor Who stories.',
   'benton': 'Sergeant Benton was a recurring UNIT character.',
   'talbot': 'Ann Talbot is Nyssa\'s double in The Black Orchid.',
   'gibbis': 'Gibbis is a Cowardly Tivolian in The God Complex.',
   'turner': 'John Nathan-Turner was a Doctor Who producer.',
   'huffle': 'In The Return of Doctor Mysterio, Lucy interogates the Doctor by squeezing a Mr. Huffle toy.',
   'viking': 'The Meddling Monk tries to alter history in the Time Meddlar by defeating the Viking invasion by Harald Hardrada using a missile.',
   'dennis': 'Dennis Spooner script-edited Doctor Who.',
   'yvonne': 'Yvonne Hartman leads Torchwood in Army of Ghosts and Doomsday.',
   'sirius': 'Sirius IV is mentinoed in Frontier in Space and Sirius V in City of Death.',
   'memory': 'In the Lie of the Land the Monks imprison those who recall that they have only been on Earth for six months for memory crimes.',
   'return': 'The Return of Doctor Mysterio is a twelfth Doctor story.',
   'nathan': 'John Nathan-Turner was a Doctor Who producer.',
   'tracer': 'The Tracer is used to detect segments of the Key to Time.',
   'flavia': 'Chancellor Flavia was appointed acting President of the Time Lords by the Doctor in The Five Doctors.',
   'madame': 'The Girl in the Fireplace is about Madame de Pompadour.',
   'taylor': 'Steven Taylor was a companion to the first Doctor.',
   'ffinch': 'Polly kidnaps Lt. Algernon Ffinch in The Highlanders.',
   'nation': 'Terry Nation invented the Daleks.',
   'circle': 'Full Circle is a fourth Doctor story.',
   'barton': 'Daniel Barton, played by Lenny Henry is the antagonist in Spyfall.',
   'xanxia': 'Queen Xanxia is one of the villains in The Pirate Planet.',
   'vortex': 'The Tardis travels through the Time Vortex.',
   'colony': 'Colony in Space is a third Doctor story.',
   'zhukov': 'Captain Zhukov commands the submarine in Cold War.',
   'sharaz': 'Sharaz Jek is the tragic villain in The Caves of Androzani.',
   'harold': 'Harold Saxon is the Master in disguise.',
   'tyburn': 'Sam Swift is to be hung at Tyburn before being saved by the Doctor and Me in The Woman Who Lived.',
   'cusick': 'Ray Cusick was responsible for the iconic Dalek design.',
   'stolen': 'The Stolen Earth is a tenth Doctor story.',
   'signet': 'The first Doctor wore a Signet Ring - also worn by the twelfth Doctor.',
   'goodge': 'The army base in The Web of Fear is under Goodge Street tube station.',
   'vardan': 'The Vardans invade Gallifrey in The Invasion of Time.',
   'silver': 'Silver Nemesis and Nightmare in Silver are both Doctor Who stories.',
   'steven': 'Steven Taylor was a companion to the first Doctor.',
   'gejelh': 'Merry Gejelh is the child chosen to sing to the Old God of Akhaten in the Rings of Akhaten.',
   'romana': 'Romana was a companion to the fourth Doctor.',
   'shakri': 'Shakri cubes appear all over the Earth in the Power of Three.',
   'prison': 'The Doctor spends a long time in Prison, most notably between The Timeless Children and Revolution of the Daleks.',
   'zaroff': 'Zaroff is the villain in The Underwater Menace.  He got to say \'Nothing the the World can stop me now!\'',
   'huasen': 'The Huasen is a massive sea beast used by the Sea Devils in Legend of the Sea Devils.',
   'icthar': 'Icthar is the Silurian leader in Warriors of the Deep.',
   'reimer': 'Kartz and Reimer\'s time travel experiments cause the Time Lords to send the Doctor and Jamie to intervene in The Two Doctors.',
   'fisher': 'The Fisher King is the monster in Before the Flood.',
   'father': 'Father\'s Day is a ninth Doctor story.',
   'megara': 'The Megara are Justice Machines in The Stones of Blood.',
   'verney': 'Andrew Verney is Tegan\'s grandfather.',
   'monoid': 'The Monoids are the monsters in The Ark.',
   'philip': 'Philip Hinchcliffe was a Doctor Who producer.',
   'oswald': 'Clara Oswald was a companion to the eleventh and twelfth Doctors.',
   'maddox': 'Judy Maddox is the head of human resources at Kerblam.',
   'freema': 'Freema Agyeman played companion Martha Jones.',
   'ainley': 'Anthony Ainley played the Master in the 1980s.',
   'louvre': 'The City of Death involves the theft of the Mona Lisa from the Louvre.',
   'repose': 'Revelation of the Daleks is set on the planet Necros in the funeral home Tranquil Repose.',
   'morpho': 'The Morpho are a disemboided brain-like creature who ruled the city of Morphoton on Marinus.',
   'morlox': 'The Molox lizards appear in Timelash.',
   'sladen': 'Elizabeth Sladen played companion Sarah Jane Smith.',
   'borusa': 'Borusa is a high ranking Time Lord, former tutor of the Doctor and ultimately the villain in the Five Doctors.',
   'second': 'The Second Doctor was played by Patrick Troughton.',
   'forced': 'In Power of the Doctor the Master uses a forced regeneration to steal the Doctor\'s body.',
   'vortis': 'Vortis is the planet of the Zarbi and the Menoptera in The Web Planet.',
   'auvers': 'Vincent van Gogh\'s painting The Church at Auvers depicts the Krafayis in Vincent and the Doctor.',
   'claire': 'Claire is a recurring character in Flux.',
   'hearts': 'The Knave, King and Queen of Hearts appear in The Celestial Toymaker.',
   'karfel': 'The Doctor and Peri visit Karfel in Timelash.',
   'system': 'Mavic Chen is Guardian of the Solar System.',
   'sutton': 'Sarah Sutton played companion Nyssa.',
   'arthur': 'Arthur Darvill played companion Rory Williams.',
   'farisi': 'Rosita Farisi is Jackson Lake\'s companion in the Next Doctor.',
   'people': 'The Almost People is an eleventh Doctor story.',
   'punjab': 'Demons of the Punjab is a thirteenth Doctor story.',
   'shadow': 'The Shadow Proclamation are a universal police force.',
   'cherub': 'Cherub versions of the Weeping Angelas appear in The Angels Take Manhattan.',
   'restac': 'Restac is a Silurian Warrior Leader in Cold Blood.',
   'magnus': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'triton': 'Triton is a city on Neptune.  The soldiers in Sleep No More are sent from there.',
   'orcini': 'Orcini is an ageing mercenary in Revelation of the Daleks.',
   'schism': 'The Master was driven mad when he gazed into the Untempered Schism as a child.',
   'halpen': 'Mr Halpen is the president of Ood Industries in Planet of the Ood.  The Ood turn him into an Ood.',
   'waited': 'The Girl Who Waited is an eleventh Doctor story.',
   'thalia': 'Chancellor Thalia is a Time Lord in Arc of Infinity.',
   'retcon': 'Retcon is a substance used to make people forget.  It was used a lot in Torchwood and also in Face the Raven.',
   'astrid': 'Kylie Minogue plays Astrid Peth in Voyage of the Damned.',
   'gillan': 'Karen Gillan played companion Amy Pond.',
   'tissue': 'The Master\'s signature weapon is the Tissue Compression Eliminator.',
   'osiris': 'Phaester Osiris is the home planet of the Osirans.',
   'uvanov': 'Uvanov is commander of the Sandminer in Robots of Death.',
   'xoanon': 'Xoanon is a crazed computer in The Face of Evil.',
   'palmer': 'Professor Alec Palmer is conducting pyschic experiments in Hide.',
   'sylvia': 'Sylvia Noble is Donna\'s mother.',
   'tegana': 'Tegana is the villain in Marco Polo.',
   'family': 'The Family of Blood is a tenth Doctor story.',
   'laszlo': 'Laszlo is Tallulah\'s missing boyfriend in Daleks in Manhattan.  He has been transformed into a pig man.',
   'visian': 'The Visians are the invisible inhabitants of the planet Mira in the Daleks\' Masterplan.',
   'malone': 'In later life Amy writes Melody Malone mysteries.',
   'audrey': 'Ace\'s mother was called Audrey.  Ace met her as a baby in The Curse of Fenric.',
   'school': 'School Reunion is a tenth Doctor story.',
   'centre': 'Journey to the Centre of the TARDIS is an elevent Doctor story.',
   'sunday': 'Millie Gibson will played companion Ruby Sunday.',
   'holmes': 'Robert Holmes script-edited Doctor Who.',
   'menace': 'The Underwater Menace is a second Doctor story.',
   'shooty': 'K9 is referred to as the Shooty Dog Thing in School Reunion.',
   'bunker': 'The Bunker is the location for all scientific research on Skaro at the time of the creation of the Daleks.',
   'hadron': 'The Master uses Hadron Energy to bind Adric in Castrovalva.',
   'battle': 'The Battle of Ranskoor Av Kolos is a thirteenth Doctor story.',
   'melody': 'Amy and Rory name their daughter Melody.',
   'enough': 'World Enough and Time is a twelfth Doctor story.',
   'eldrad': 'Eldrad is the villain in The Hand of Fear.',
   'magpie': 'The Wire operates out of Magpie Electronics in The Idiot\'s Lantern.',
   'attack': 'Attack of the Cybermen is a sixth Doctor story.',
   'medusa': 'The Daleks move 27 planets to the Medusa Cascade in The Stolen Earth.',
   'kaftan': 'Kaftan is one of the villains in Tomb of the Cybermen.',
   'behind': 'Doctor Who is traditionally watched from Behind the Sofa.',
   'isolus': 'Chloe Webber is possessed by an Isolus in Fear Her.',
   'hecate': 'Nightmare of Eden involes a collision between the space ships Empress and Hecate.',
   'obrien': 'Graham O\'Brien was a companion to the thirteenth Doctor.',
   'wenger': 'Piers Wenger was an executive producer of Doctor Who.',
   'drahva': 'Drahva is the home of the Drahvins.',
   'stairs': 'Not as often a problem for Daleks as some people think.',
   'effect': 'The Blinovitch Limitation Effect regulates time travel.',
   'pharos': 'The Fourth Doctor regenerates when he falls from the antenna of the Pharos Project.',
   'beacon': 'The Nerva Beacon space station features in several stories in Tom Baker\'s first season.',
   'bryant': 'Nicola Bryant played companion Peri Brown.',
   'sontar': 'Sontar is the home world of the Sontarans.',
   'golden': 'Operation Golden Age are trying to turn back time in Invasion of the Dinosaurs.',
   'atrios': 'Atrios and Zeos are two planets at war in The Armageddon Factor.',
   'meglos': 'Meglos is a fourth Doctor story.',
   'ghosts': 'Army of Ghosts is a tenth Doctor story.',
   'panama': 'The fifth Doctor wore a Panama Hat.',
   'stones': 'The Stones of Blood is a fourth Doctor story.',
   'robots': 'The Robots of Death is a fourth Doctor story.',
   'dhawan': 'Sacha Dhawan played the Master opposite Jodie Whittaker\'s Doctor.',
   'fourth': 'The Fourth Doctor was played by Tom Baker.',
   'wraith': 'Wraiths inhabit the catacombs on Galligrey.',
   'raston': 'The Raston Warrior Robot appears in the Five Doctors.',
   'silent': 'The Silent are the individual members of The Silence.',
   'rutans': 'The Rutans are the enemies of the Sontarans.',
   'martha': 'Martha Jones was a companion to the tenth Doctor.',
   'oberon': 'Orcini is a Knight of Oberon in Revelation of the Daleks.',
   'diplos': 'Vivien Fay is the identity assumed by Cessair of Diplos in The Stones of Blood.',
   'eocene': 'A period of Earth\'s history from which the Silurians probably didn\'t originate and so they shouldn\'t be called Eocenes either.',
   'graham': 'Graham O\'Brien was a companion to the thirteenth Doctor.',
   'mackie': 'Pearl Mackie played companion Bill Potts.',
   'azaxyr': 'Azaxyr is an Ice Lord in Monster of Peladon',
   'lytton': 'Lytton is a Space Mercenary who appears in Resurrection of the Daleks and Attack of the Cybermen.',
   'sidrat': 'The SIDRAT\'s were the War Lord\'s time and space machines in The War Games.',
   'scorby': 'Scorby is Harrison Chase\'s henchman in The Seeds of Doom.',
   'zeiton': 'Zeiton-7 ore is vital for realigning the power systems of time machines.',
   };
//   'stenck': 'Commander Stenck leads the Sontarans in The Vanquishers.',
//   'shallo': 'Shallo is a Sontaran in The Vanquishers.  He is caught looting a corner shop for chocolate by the Fam.',
//   'kragar': 'Kragar is a Sontaran Psychic Surveryor in The Vanquishers.',
//   'wrarth': 'The Wrath Warriors are monsters in The Star Beast.',
//   'newton': 'Isaac Newton appears (briefly) in Wild Blue Yonder.',
//   'mavity': 'In Wild Blue Yonder the Doctor and Donna accidentally change thework Gravity to Mavity.',
//   'stooky': 'Stooky Bill is the puppet used by John Logie Baird that starts the Giggle.',
//   'davina': 'Davina McCall appears as herself in The Church on Ruby Road.',
//   'mccall': 'Davina McCall appears as herself in The Church on Ruby Road.',
//   'goblin': 'Goblins are the enemy in The Church on Ruby Road.',
//   'babies': 'Space Babies is a Fifteenth Doctor story.',
//   'cherry': 'Carla Sunday is Ruby\'s grandmother.',
//   'varada': 'Varada Sethu will play a new companion in the 2025 season.',
//   'bubble': 'Dot and Bubble is a Fifteenth Doctor story.',
//   'pepper': 'Lindy Pepper-Bean is the protagonist in Dot and Bubble.',
//   'morris': 'Morris Gibbons is the UNIT scientific advisor in The Legend of Ruby Sunday and Empire of Death.',
