export const WORDSDICT: {[key:string]:string } = {
   'clegg': 'Professor Clegg is an unwilling psychic in Planet of the Spiders.',
   'omega': 'Omega was a legendary Time Lord who created the supernova that powers Time Lord civilisation',
   'varsh': 'Varsh was Adric\'s brother in Full Circle.',
   'kaled': 'The Daleks are mutated Kaleds.',
   'mavic': 'Mavic Chen is the villain in The Daleks\' Masterplan.',
   'skorr': 'Commander Skorr is a Sontaran in The Sontaran Stratagem.',
   'angel': 'The Weeping Angels are a popular Doctor Who Monster.',
   'janis': 'Leela is initially very keen on killing people with Janis Thorns.',
   'zolfa': 'Zolfa Thura is the home planet of Meglos.',
   'takes': 'It Takes You Away is a Thirteenth Doctor story.',
   'ogron': 'The Ogrons appeared as servants to the Daleks in Day of the Daleks and Frontier in Space.',
   'havoc': 'HAVOC was a team of stuntmen that provided action scenes for many Third Doctor episodes.',
   'sugar': 'In The Moonbase, the Cybermen poison the sugar.',
   'lumic': 'John Lumic is the villain in Rise of the Cybermen and The Age of Steel.',
   'eater': 'The Eater of Light is the monster in The Eaters of Light.',
   'grant': 'Jo Grant was a companion of the Third Doctor.',
   'sethu': 'Varada Sethu will play a new companion in the 2025 season.',
   'skaro': 'Skaro is the Dalek planet.',
   'zocci': 'Bannakaffalatta from Voyage of the Damned was a Zocci.',
   'atmos': 'ATMOS, short for Atmospheric Omission System, was a device created by the Sontarans to convert the Earth into a Sontaran Hatchery.',
   'zygon': 'The Zygons appeared in Terror of the Zygons, The Day of the Doctor, The Zygon Invasion and The Zygon Inversion.',
   'harry': 'Harry Sullivan was a companion of the Fourth Doctor.',
   'cruel': 'In various forms the words \'Never cruel or cowardly\' have been used in Doctor Who.',
   'trees': 'The Trees save the day in Into the Forest of the Night and the Androzani Trees are endangered in The Doctor, The Widow and the Wardrobe.',
   'chips': 'Chips coated in Krillitane Oil were served to the children in School Reunion.',
   'horus': 'The Eye of Horus held Sutekh prisoner on Earth.',
   'jenna': 'Jenna Coleman played companion Clara Oswald.',
   'vworp': 'Allegedly the Tardis goes Vworp Vworp when it materialises.',
   'nitro': 'Ace often blew things up with Nitro Nine.',
   'lloyd': 'Innes Lloyd was a Doctor Who producer.',
   'derek': 'There have been lots of Dereks associated with Doctor Who, including Derek Ware who founded the stunt team HAVOC and Derek Jacobi who played the Master',
   'mummy': 'Mummy on the Orient Express is a Twelfth Doctor story.',
   'lynda': 'Lynda (with a Y) is almost a companion in Bad Wolf and the Parting of the Ways.',
   'sorin': 'Captain Sorin is a love interest for Ace in The Curse of Fenric.',
   'dalek': 'The Daleks are the show\'s most famous monster.',
   'rings': 'The Rings of Akhaten is an Eleventh Doctor story.',
   'diane': 'Diane is Dan Lewis\' girlfriend.',
   'dryad': 'Dryad beetles are the monsters in Knock Knock.',
   'delta': 'Delta and the Bannermen is a Seventh Doctor story.',
   'erato': 'Erato was the Creature from the Pit.',
   'donna': 'Donna Noble was a companion of the Tenth Doctor.',
   'helen': 'Helen A was the villain in The Happiness Patrol.',
   'white': 'The White Guardian is the anthropomorphic personification of order and good.',
   'wrack': 'Captain Wrack is the villain in Enlightnement.',
   'souza': 'Lady Christina de Souza acts as the companion in Planet of the Dead.',
   'nikki': 'Nikki Wilson was executive producer of Doctor Who.',
   'gomez': 'Michelle Gomez played Missy.',
   'quark': 'The Quarks are the robot servants of the Dominators',
   'zarbi': 'The Zarbi were monters appearing in the The Web Planet.',
   'tesla': 'Nikola Tesla\'s Night of Terror is a Thirteenth Doctor story.',
   'tower': 'Rassilon\'s Tomb lies in a Tower in the Death Zone on Gallifrey.',
   'byron': 'Lord Byron appears in the Haunting of Villa Diodati.',
   'black': 'Black Orchid and The Curse of the Black Spot are both Doctor Who stories.',
   'stien': 'Stien betrays the Doctor in Resurrection of the Daleks.',
   'nyder': 'Nyder is Davros\' Henchman in Genesis of the Daleks.',
   'polly': 'Polly was a companion of the first and second Doctors.',
   'yates': 'Captain Mike Yates was a regular character during the UNIT years.',
   'flood': 'Mrs Flood is a mysterious neighbour of the Sundays.',
   'cryon': 'The Cryons were a race in Attack of the Cybermen.',
   'telos': 'Telos is a Cyberman planet that featured in both Tomb of the Cybermen and Attack of the Cybermen.',
   'steel': 'The Age of Steel is a Tenth Doctor story.',
   'shade': 'A Quantum Shade takes the form of a raven and deals out justice in Face the Raven.',
   'siege': 'The Time of the Doctor is about the Siege of Trenzalore.',
   'twice': 'Twice Upon a Time is a Twelfth Doctor story.',
   'penny': 'Susan Twist plays Penny Pepper-Bean in Dot and Bubble.',
   'awsok': 'Awsok was an alias used by Tecteun who considered herself the Doctor\'s mother.',
   'oswin': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'baker': 'Tom Baker played the Fourth Doctor and Colin Baker played the Sixth Doctor.',
   'taran': 'The Taran Wood Beast is a creature in the Androids of Tara.',
   'space': 'Doctor Who adventures in Time and Space.',
   'woman': 'The Woman who Lived and the Woman who Fell to Earth are both Doctor Who stories.',
   'frost': 'Thin Ice takes place at a Frost Fair on the Thames.',
   'trion': 'Home planet of the Doctor\'s companion Turlough.',
   'roman': 'The Romans is a First Doctor story.',
   'azure': 'Azure is one of the villains in Flux.',
   'triad': 'Susan Twist playse Susan Triad in The Legend of Ruby Sunday and The Empire of Death.',
   'brian': 'There have been several Brians associated with Doctor Who included Brian Hayles who created the Ice Warriors and executive producer Brian Minchin.',
   'fires': 'The Fires of Pompei is a Tenth Doctor story.',
   'capel': 'Taren Capel is the villain in The Robots of Death',
   'claws': 'The Claws of Axos is Third Doctor Who story.',
   'smith': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.  Matt Smith played the Eleventh Doctor.',
   'dicks': 'Terrance Dicks was a Doctor Who writer, script editor and prolific noveliser of Doctor Who stories.',
   'thura': 'Zolfa Thura is the home planet of Meglos.',
   'saint': 'The Bells of Saint John is an Eleventh Doctor story.',
   'state': 'State of Decay is a Fourth Doctor story.',
   'bells': 'The Bells of Saint John is an Eleventh Doctor story.',
   'glitz': 'Glitz is a character in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'carol': 'A Christmas Carol is an Eleventh Doctor story.',
   'borad': 'The Borad is the villain in Timelash.',
   'vater': 'Vater is a title in the Anglican Army that appears in Boom.',
   'tyler': 'Rose Tyler was a companion of the Ninth and Tenth Doctors.',
   'segal': 'Philip Segal was Executive Producer for the TV Movie.',
   'saxon': 'Harold Saxon is the alias adopted by the Master in the Tenth Doctor\'s second series.',
   'blood': 'The Stones of Blood, The Family of Blood, and Cold Blood are all Doctor Who stories.',
   'magma': 'The Magma Beast appeared in The Caves of Androzani.',
   'fifth': 'The Fifth Doctor was played by Peter Davison.',
   'astra': 'Princess Astra of Atrios is the sixth segment of the Key to Time.  Romana chooses to look like her when she regenerates.',
   'thorn': 'Leela is initially very keen on killing people with Janis Thorns.',
   'paddy': 'Paddy Russell was the first female director to work on Doctor Who.',
   'trial': 'Trial of a Time Lord is the over-arching title of the Sixth Doctor\'s second season.',
   'flesh': 'Flesh and Stone and The Rebel Flesh are both Eleventh Doctor stories.',
   'whale': 'A Star Whale is carrying Starship UK in the Beast Below.',
   'power': 'The Power of the Daleks, The Power of Kroll and The Power of Three are all Doctor Who stories.',
   'mouri': 'The Mouri are the gatekeepers of the Temple of Atropos.',
   'madge': 'Madge Arwell is the Widow in the Doctor, the Widow and the Wardrobe.',
   'light': 'Light is one of the villains in Ghost Light.',
   'heart': 'The Doctor has two hearts.',
   'storm': 'Robots of Death takes place on a Storm Mine.',
   'logic': 'According to the Second Doctor logic merely allows one to be wrong with authority.',
   'cheem': 'Home of the Forest of Cheem from The End of the World.',
   'lance': 'Lance Bennet is Donna Noble\'s fiance in The Runaway Bride.',
   'claus': 'Santa Claus appears in Last Christmas.',
   'smile': 'Smile is a Twelfth Doctor story.',
   'maaga': 'Maaga was the villainous leader of the Drahvin in Galaxy Four.',
   'taren': 'Taren Capel is the villain in The Robots of Death',
   'clams': 'Giant clams lurk in the sewers of the Kaled City in Genesis of the Daleks.  One of them attacks Harry.',
   'walsh': 'Bradley Walsh played companion Graham O\'Brien.',
   'nimon': 'The Nimon are minotaur like creatures from The Horns of Nimon.',
   'idiot': 'The Idiot\'s Lantern is a Tenth Doctor story.',
   'alaya': 'Alaya is a Silurian in the The Hungry Earth and Cold Blood.',
   'aneth': 'Aneth is a planet in The Horns of Nimon.',
   'danny': 'Danny Pink is Clara Oswald\'s boyfriend.',
   'sigma': 'Theta Sigma was the Doctor\'s nickname at the Time Lord academy.  In the Happiness Patrol all aliens are designated Sigma.  Later Ood Sigma is instramental in freeing the Ood.',
   'varga': 'Varga plants are deadly, but slow-moving, mobile plants from the planet Kembel.  It is also the name of an Ice Warrior.',
   'kraal': 'The Kraals appeared in The Android Invasion.',
   'kalid': 'Kalid is a disguise adopted by the Master in Time-Flight.',
   'flint': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'wales': 'The modern Doctor Who series was bought back by BBC Wales and is made in Cardiff.',
   'dandy': 'The First Doctor described the Second and Third Doctors as a dandy and a clown.',
   'virus': 'The villain in The Invisible Enemy is a sentient virus.',
   'opens': 'The Pandorica Opens is an Eleventh Doctor story.',
   'dyall': 'Valentine Dyall played the Black Guardian.',
   'clara': 'Clara Oswin Oswald was a companion of the Eleventh and Twelfth Doctors.',
   'malus': 'The Malus is the evil beneath the Church in The Awakening.',
   'satan': 'The Satan Pit is a Tenth Doctor story.',
   'erisa': 'Captain Erisa Magambo is a UNIT Captain who appears in Turn Left and Planet of the Dead.',
   'major': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'tegan': 'Tegan Jovanka was a companion of the Fourth and Fifth Doctors.',
   'rodan': 'Rodan was a female Gallifreyan Traffic Controller who helps the Doctor and Leela in the Invasion of Time.',
   'strax': 'Jenny Flint, Madame Vastra and Commander Strax are the Paternoster Gang: allies of the Doctor.',
   'house': 'House is the villain in The Doctor\'s Wife.',
   'grace': 'Grace Holloway was the Doctor\'s companion in the TV Movie.',
   'piers': 'Piers Wenger was an executive producer of Doctor Who.',
   'crime': 'Partners in Crime is a Tenth Doctor story.',
   'curse': 'The Curse of Peladon, The Curse of Fenric, and the Curse of the Black Spot are all Doctor Who stories',
   'maren': 'Maren is leader of the Sisterhood of Karn in The Brain of Morbius.',
   'sixth': 'The Sixth Doctor was played by Colin Baker.',
   'germs': 'Spider Germs menace the characters in Kill the Moon.',
   'stone': 'Flesh and Stone is an Eleventh Doctor episode.',
   'pilot': 'The Pilot is a Twelfth Doctor story.',
   'missy': 'Missy is the Doctor\'s arch enemy.',
   'santa': 'Robot Santas threaten the Doctor in the Christmas Invasion and the Runaway Bride.',
   'carla': 'Carla Sunday is Ruby\'s mother.',
   'marco': 'Marco Polo was the show\'s fourth story.',
   'usher': 'The Gold Usher is a Time Lord ceremonial position.',
   'panda': 'Steven Taylor brings his toy panda with him into the Tardis.  Panda is also Iris Wildthyme\'s companion in Paul Mags\' stories.',
   'earth': 'Lots of stories are set on the planet Earth.',
   'knock': 'Knock Knock is a Twelfth Doctor story.',
   'graff': 'Graff Vynda-K is the villain in the Ribos Operation.',
   'slaar': 'Slaar is an Ice Warrior who appears in The Seeds of Death.',
   'gelth': 'The Gelth are the villians in The Unquiet Dead.',
   'nerva': 'The Nerva Space Station features in both The Ark in Space and Revenge of the Cybermen.',
   'abbey': 'The famous Abbey Road zebra crossing appears in The Devil\'s Chord.',
   'robin': 'Robin Hood appears in Robot of Sherwood.',
   'mercy': 'A Town called Mercy is an Eleventh Doctor story.',
   'papal': 'The Papal Mainframe is the headquarters of the militarised Church.',
   'rills': 'The Rills were aliens in Galaxy Four.',
   'enemy': 'The Enemy of the World and The Invisible Enemy are both Doctor Who stories.',
   'under': 'Under the Lake is a Twelfth Doctor story.',
   'innes': 'Innes Lloyd was a Doctor Who producer.',
   'pearl': 'Pearl Mackie played companion Bill Potts.',
   'xeron': 'The Tardis visits the planet Xeros in The Space Museum and helps the Xerons gain freedom from the oppressive Moroks.',
   'rusty': 'Rusty is a "good" Dalek.',
   'aukon': 'Aukon is one of the Three Who Rule, villains in State of Decay.',
   'venus': 'Presumably where the Doctor learned Venusian Aikido.',
   'tenth': 'Mondas, home of the Cybermen, was once the tenth planet in the Earth\'s solar system (according to Doctor Who).',
   'ianto': 'Ianto Jones was a series regular in the Torchwood Doctor Who spin-off and also appeared in The Stolen Earth and Journey\'s End.',
   'decay': 'State of Decay is a Fourth Doctor story.',
   'vanir': 'The Vanir work on the Terminus in the Fith Doctor episode Terminus.',
   'dregs': 'The Dregs are the remains of humanity in Orphan 55',
   'kemel': 'Kemel is a servant of the Maxfields in The Evil of the Daleks and helps Jamie rescue Victroia.',
   'sacha': 'Sacha Dhawan played The Master during the Thirteenth Doctor series.',
   'cyril': 'Cyril is an evil school boy in The Celestial Toryroom.',
   'gatwa': 'Ncuti Gatwa plays the Fifteenth Doctor.',
   'great': 'The Great Intelligence is a recurring enemy of the Doctor.',
   'sarff': 'Colony Sarff was a servant of Davros in The Magician\'s Apprectice and the Witch\'s Familiar.',
   'paper': 'The Doctor often uses Psychic Paper to get past officials.',
   'rigsy': 'Rigsy appears in Flatline and Face the Raven.',
   'theta': 'The Doctor\'s nickname at the Time Lord academy was Theta Sigma.',
   'susan': 'Susan was is the Doctor\'s Grandaughter.',
   'ching': 'Madam Ching, the famous pirate, appeared in Legend of the Sea Devils.',
   'wings': '"Chap with wings.  Five Rounds Rapid." was said by the Brigadier.',
   'faith': 'Faith can be used to hold back haemovores, but it also feeds the creature in the God Complex.',
   'lived': 'The Woman who Lived is a Twelfth Doctor story.',
   'sweet': 'Mr Sweet is a villain in The Crimson Horror.',
   'banks': 'David Banks played many Cyber Leaders in the 1980s.',
   'segun': 'Segun Akinola currently composes the music for Doctor Who.',
   'sally': 'Sally Sparrow is the protagonist of Blink.',
   'ricky': 'Ricky September is Lindy Pepper-Bean\'s love interest in Dot and Bubble before she kills him.',
   'tigus': 'A volcanic planet visited in The Daleks\' Masterplan.',
   'below': 'The Beast Below was an Eleventh Doctor episode.',
   'leela': 'Leela was a companion to the Fourth Doctor.',
   'chase': 'The Chase is a First Doctor story.',
   'three': 'The Three Doctors, World War Three and the Power of Three are all Doctor Who stories.',
   'world': 'The Enemy of the World, The End of the World, World War Three, The Pyramid at the End of the World and World Enough and Time are all Doctor Who stories.',
   'blitz': 'The Empty Child and the Doctor Dances take place during the London Blitz.',
   'greel': 'Magnus Greel is the villain in The Talons of Weng-Chiang.',
   'altos': 'Altos is an agent of Arbitan in the Keys of Marinus.',
   'avery': 'Pirate Henry Avery appears in The Curse of the Black Spot and is mentioned in The Smugglers.',
   'tenza': 'The boy, George, in Night Terrors is really a Tenza.',
   'betan': 'The Thal woman Betan helps the Doctor in Genesis of the Daleks.',
   'hiker': 'Susan Twist plays a Hiker in 73 Yards.',
   'priam': 'King Priam of Troy appears in The Myth Makers.',
   'chang': 'Chang Lee was the Doctor (or the Master)\'s companion in the TV Movie.',
   'horns': 'The Horns of Nimon is a Fourth Doctor story.',
   'sonic': 'The Doctor often uses the Sonic Screwdriver to get out of scrapes.',
   'wendy': 'Wendy Padbury played Zoe, companion to the Second Doctor.',
   'guard': 'Gel Guards are the servants of Omega in The Three Doctors.',
   'tryst': 'Professor Tryst was the villian in The Nightmare of Eden.',
   'monks': 'The Meddling Monk, the Headless Monks and the Monks have all opposed the Doctor.',
   'solar': 'The villainous Mavic Chen is Guardian of the Solar System.',
   'brave': 'The Fifth Doctor often urged Tegan to have a brave heart.',
   'nixon': 'President Richard Nixon appears in The Impossible Astronaut and Day of the Moon.',
   'death': 'The Seeds of Death, The Ambassadors of Death, The Green Death, Death to the Daleks, The Robots of Death, City of Death, Death in Heaven, and Empire of Death are all Doctor Who stories.',
   'wyatt': 'Wyatt Earp appears in the Doctor Who story The Gunfighters.',
   'jenny': 'Jenny is the Doctor\'s Daughter.',
   'jamie': 'Jamie McCrimmon was a companion of the Second Doctor.',
   'lords': 'Last of the Time Lords is a Tenth Doctor story.',
   'isaac': 'Isaac Newton appears (briefly) in Wild Blue Yonder.',
   'human': 'Human Nature is a Tenth Doctor story.',
   'lindy': 'Lindy Pepper-Bean is the protagonist in Dot and Bubble.',
   'truth': 'Truth or Consequences is a town occupied by Zygons in The Zygon Invasion.',
   'staal': 'General Staal is a Sontaran in The Sontaran Stratagem.',
   'gonds': 'The Gonds live on the Planet of the Gonds in The Krotons.',
   'ribos': 'The planet Ribos appears in the Ribos Operation.',
   'condo': 'Condo was Solon\'s Henchman in The Brain of Morbius.',
   'wotan': 'WOTAN was an evil computer that appeared in The War Machines.',
   'remus': 'Romulus and Remus were the twins in The Twin Dilemma.',
   'clent': 'Leader Clent runs the Britanicus Base in the Ice Warriors.',
   'engin': 'Co-ordinator Engin is in charge of the Matrix in The Deadly Assassin.',
   'tasha': 'Tasha Lem leads the Church of the Papal Mainframe in Time of the Doctor.',
   'devil': 'The Sea Devils are relatives of the Silurians.',
   'green': 'The Green Death is a Third Doctor story.',
   'poppy': 'Poppy is captain of the Space Babies.',
   'dream': 'The Dream Lord is a manifestation of the Doctor\'s subconscious.  Dream Crabs attack the characters in Last Christmas.',
   'solow': 'Ingrid Pitt plays the villainous Doctor Solow in Warriors of the Deep.',
   'terry': 'Terry Nation created the Daleks.',
   'river': 'River Song is the Doctor\'s wife.',
   'clown': 'The Chief Clown is a villian in The Greatest Show in the Galaxy.',
   'pluto': 'The Sun Makers is set on Pluto.',
   'jelly': 'The Fourth Doctor often offered people Jelly Babies.',
   'vasor': 'Vasor is an antagonist in the frozen wastes in The Keys of Marinus.',
   'image': 'Image of the Fendahl is a Fourth Doctor story.',
   'elton': 'Elton is the viewpoint character in Love & Monsters.',
   'vogan': 'The Vogans are the inhabitants of the planet Voga in Revenge of the Cybermen.',
   'third': 'Jon Pertwee played the Third Doctor.',
   'julie': 'Julie Gardner was an executive producer on Docor Who.',
   'robot': 'Robot and Robot of Sherwood are both Doctor Who stories.',
   'varos': 'Varos is the planet in Vengeance on Varos.',
   'solos': 'Solos is an Earth Colony in The Mutants',
   'cybus': 'Cybus Industries creates the Cybermen in Rise of the Cybermen and The Age of Steel.',
   'morok': 'The Moroks are the villains in The Space Museum.',
   'fudge': 'Fudge is a friend of Rose Noble in The Star Beast.  He plays a more prominent role in the comic the story is based on.',
   'vicki': 'Vicki was a companion of the first Doctor.',
   'noble': 'Donna Noble was a companion of the Tenth Doctor.',
   'helix': 'The Mandragora Helix is the enemy in the Masque of Mandragora.',
   'ncuti': 'Ncuti Gatwa plays the Fifteenth Doctor.',
   'plant': 'There are many dangerous plants in Doctor Who, such as the Varga plants and the Krynoids.',
   'quill': 'Mr Quill is a servant of the seaweed in Fury from the Deep.',
   'macra': 'The Macra are giant crab like monsters that appeared in both The Macra Terror and Gridlock.',
   'moths': 'Flesh Moths inhabit the space between universes in It Takes You Away.',
   'munro': 'Rona Munro wrote Survival the final story in the original run of Doctor Who.  She is the only writer to have written for both the classic and the new series.',
   'globe': 'Much of The Shakespeare Code is set at the Globe Theatre in London.',
   'yards': '73 Yards is a Fifteenth Doctor story.',
   'jodie': 'Jodie Whittaker played the Thirteenth Doctor.',
   'widow': 'The Doctor, the Widow and the Wardrobe is an Eleventh Doctor story.',
   'vigil': 'The Vigil were one of the races of the Rings of Akhaten.',
   'mccoy': 'Sylvester McCoy played the Seventh Doctor.',
   'ninth': 'The Ninth Doctor was played by Christopher Eccleston.',
   'alpha': 'Alpha Centauri is a diplomat who appears in The Curse of Peladon',
   'wells': 'H. G. Wells appears in the story Timelash.',
   'ssorg': 'Ssorg is an Ice Warrior who appears in the Curse of Peladon',
   'finch': 'Mr Finch is the villain in School Reunion.',
   'zodin': 'The Terrible Zodin was mentioned but never seen.',
   'colin': 'The Sixth Doctor was played by Colin Baker.',
   'chief': 'The War Chief was one of the villains in The War Games',
   'pting': 'The Pting is the monster in The Tsuranga Conundrum.',
   'shada': 'Shada is an unbroadcast episode of Doctor Who.',
   'adams': 'Douglas Adams was a script editor on Doctor Who.',
   'cyber': 'Humans fought many Cyber wars against the Cybermen.',
   'aztec': 'The Aztecs is a First Doctor story.',
   'blink': 'Blink is a Tenth Doctor episode.',
   'adric': 'Adric was a companion of the Fourth and Fifth Doctors.',
   'myrka': 'The Myrka is a beast controlled by the Silurians and Sea Devils in Warriors of the Deep.',
   'maxil': 'Commander Maxil is a Time Lord played by future Doctor, Colin Baker.',
   'ogros': 'Planet of the Ogri from the Stones of Blood.',
   'gebek': 'Gebek leads the miners in The Monster of Peladon.',
   'rutan': 'The Rutans are the deadly enemies of the Sontarans.',
   'baird': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'hilio': 'Hilio was a Menoptera, played by Martin Jarvis, in The Web Planet.',
   'sleep': 'Sleep No More is a Twelfth Doctor story.',
   'jones': 'Martha Jones was a companion of the Tenth Doctor.',
   'zargo': 'Zargo is one of the Three Who Rule, villains in State of Decay.',
   'marsh': 'Jean Marsh played several roles in Doctor Who, including companion Sara Kingdom.',
   'queen': 'The milk of the Queen Bat is a cure for Spectrox Toxaemia in Tge Caves of Androzani.  The Doctor also married Queen Elizabeth I and was exiled by Queen Victoria.',
   'zanak': 'Zanak is the Pirate Planet.',
   'scarf': 'The Fourth Doctor was famous for his long scarf.',
   'beast': 'The Beast Below is an Eleventh Doctor story and the Star Beast is a Fourteenth Doctor story.',
   'times': 'The regeneration of the Tenth Doctor into the Eleventh is prophesied by He will Knock Four Times.',
   'roger': 'Roger Delgado was the first actor to play The Master.',
   'ashad': 'Ashad is the lone Cyberman.',
   'exile': 'The Third Doctor is exiled to Earth.',
   'axons': 'The Axons are the monsters in The Claws of Axos.',
   'letts': 'Barry Letts was a producer and director of Doctor Who.',
   'caves': 'The Caves of Androzani is a Fifth Doctor story.',
   'lalla': 'Lalla Ward played Romana, companion to the Fourth Doctor.',
   'ergon': 'The Ergon is a monster that appears in Arc of Infinity.',
   'chalk': 'In Battlefield, Ace and Shou Yuing hold off the Destroyer with a chalk circle.',
   'stotz': 'Stotz leads the mercenaries in The Caves of Androzani.',
   'gerry': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'titan': 'Titan Base is taken over by a sentient virus in The Invisible Enemy',
   'hedin': 'Councillor Hedin is a villain in Arc of Infinity.',
   'hines': 'Frazer Hines played Jamie, companion to the Second Doctor.',
   'first': 'William Hartnell played the First Doctor.',
   'stike': 'Stike is a Sontaran in The Two Doctors.',
   'nuton': 'The Nuton Power Complex is blown up by the Axons in the Claws of Axos.',
   'delia': 'Delia Derbyshire composed the theme tune.',
   'linda': 'The London Investigation \'n\' Detective Agency (LINDA) seeks to learn more about the Doctor in Love & Monsters.',
   'benny': 'In the novels, Bernice Summerfield (known as Benny) was a companin to the Seventh Doctor.',
   'davis': 'Gerry Davis was a story editor for Doctor Who, and co-created the Cybermen.',
   'games': 'The War Games is a Third Doctor story.',
   'thals': 'The Thals are the enemy of the Daleks... And I promised Prof. Dresner I would include them.',
   'ghost': 'Ghost Light and The Ghost Monument are both Doctor Who stories.',
   'cilla': 'Cilla Black appears in The Devil\'s Chord.',
   'morax': 'The Morax are the villains in The Witchfinders.',
   'sound': 'The Sound of Drums is a Tenth Doctor story.',
   'vardy': 'The Nano-bot Vardy are the monsters in Smile.',
   'swarm': 'Swarm is one of the villains in Flux.',
   'orion': 'The Fifth Doctor often tried to get to the Eye of Orion, succeeding in The Five Doctors.',
   'snake': 'The Mara takes the form of a giant snake.',
   'reign': 'The Reign of Terror is a First Doctor story.',
   'vault': 'In his final series, the Twelfth Doctor keeps Missy locked in a vault.',
   'poosh': 'The Lost Moon of Poosh, mentioned in Midnight is one of the stolen planets in The Stolen Earth.',
   'giant': 'The Doctor has faced Giant Rats, Giant Crabs and Giant Robots among other menaces.',
   'tosin': 'Tosin Cole played companion Ryan Sinclair.',
   'james': 'King James I of England and VI of Scotland appears in The Witchfinders.',
   'wimey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'jemma': 'Jemma Redgave played Kate Stewart, the head of UNIT.',
   'chord': 'The Devil\'s Chord is a Fifteenth Doctor story.',
   'logie': 'The Giggle starts with John Logie Baird\'s demonstration of television.',
   'build': 'The Kangs in Paradise Towers use the phrase Build High for Happiness.',
   'sense': 'The Sense Sphere is home to the Sensorites.',
   'idris': 'Idris is a personification of the Tardis in The Doctor\'s Wife.',
   'peter': 'There are lots of Peters associated with Doctor Who including, Peter Purves who played companion Steven Taylor, Peter Bryant producer, Peter Davison who played the Fifth Doctor and Peter Capaldi who played the Twelfth Doctor.',
   'nyssa': 'Nyssa was a companion of the Fourth and Fifth Doctors.',
   'kolos': 'The Battle of Ranskoor Av Kolos is a Thirteenth Doctor story.',
   'cheng': 'Suki Cheng was the villain in Praxeus.',
   'bland': 'Terrance Dicks used the pseudonum Robin Bland for The Brain of Morbius because he disliked the changes made to his script by the production team.',
   'crack': 'The Eleventh Doctor\'s first series is plagued by cracks in time and space.',
   'siren': 'The malfunctioning medical system in The Curse of the Black Spot was considered a Siren by the pirates.',
   'above': 'He who to Rassilon\'s Tower would go must choose above, between, below.',
   'wheel': 'The Wheel is a space station where the Doctor met his companion Zoe.',
   'karra': 'Karra is a Cheetah person who befriends Ace in Survival.',
   'alien': 'The Earth is frequently invaded by aliens in Doctor Who.',
   'young': 'Mal Young was an executive producer of Doctor Who.',
   'janet': 'Janet Fielding played Tegan Jovanka, companion to the Fourth and Fifth Doctors.',
   'lewis': 'Dan Lewis is a companion of the Thirteenth Doctor.',
   'villa': 'The Haunting of Villa Diodati is a Thirteenth Doctor story.',
   'flynn': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'frock': 'The First Doctor wore an Edwardian frock coat.',
   'craze': 'Michael Craze played Ben, companion to the First and Second Doctors.',
   'voord': 'The alien Voord were the monsters in the Keys of Marinus.',
   'water': 'Dark Water is a Twelfth Doctor story.',
   'chris': 'Chris Chibnall is the current Doctor Who showrunner.  Christopher Eccleston played the Ninth Doctor.',
   'shura': 'Shura is a rebel time traveller from the Daleks in Day of the Daleks who nearly creates a bootstrap paradox.',
   'hulke': 'Malcolm Hulke wrote many episodes of Doctor Who and co-write The Making of Doctor Who with Terrance Dicks.',
   'wirrn': 'The Wirrn were monsters that appeared in The Ark in Space.',
   'potts': 'Bill Potts was a companion to the Twelfth Doctor.',
   'xeros': 'The Tardis visits the planet Xeros in The Space Museum.',
   'empty': 'The Empty Child is a Ninth Doctor story.',
   'bride': 'The Runaway Bride is a Tenth Doctor story.',
   'styre': 'Styre is the Sontaran in The Sontaran Experiment.',
   'kroll': 'Kroll is a giant squid from The Power of Kroll.',
   'raaga': 'Raaga is the penal planet of the Tereleptils.',
   'rebel': 'The Rebel Flesh is an Eleventh Doctor story.',
   'seeds': 'The Seeds of Death and the Seeds of Doom are both Doctor Who stories.',
   'watch': 'Time Lords seem to frequently hide their memories in pocket watches.',
   'heist': 'Time Heist is a Twelfth Doctor story.',
   'piper': 'Billie Piper played Rose Tyler, companion.',
   'rogue': 'Rogue is a Fifteenth Doctor story.',
   'mundy': 'Mundy Flynn played by Varada Sethu appears in Boom.',
   'auton': 'The Autons are plastic creatures controlled by the Nestene Consciousness.',
   'barry': 'Barry Letts was a producer and director of Doctor Who.',
   'solon': 'Doctor Solon is the villain in The Brain of Morbius.',
   'klieg': 'Eric Klieg is one of the villains in Tomb of the Cybermen.',
   'wills': 'Anneke Wills played Polly, companion to the First and Second Doctors.',
   'tooth': 'Tooth and Claw is a Tenth Doctor episode.',
   'brown': 'Peri Brown was a companion of the Fifth and Sixth Doctors.',
   'binro': 'Binro is a heretic on Ribos because of his belief in life in the stars.',
   'clone': 'The Doctor\'s Daughter is created using a form of cloning technology.',
   'timey': 'In Blink the Doctor builds a timey-wimey detector that goes ding.',
   'parks': 'The Doctor Who story Rosa is about activist Rosa Parks.',
   'karen': 'Karen Gillan played Amy Pond, companion.',
   'twist': 'There is always a twist at the end.',
   'raven': 'Face the Raven is a Twelfth Doctor story.',
   'waris': 'Waris Hussein was Doctor Who\'s first director.',
   'drums': 'The Sound of Drums is a Tenth Doctor story.',
   'grand': 'The Grand Serpent helped found and then disassemble UNIT.',
   'brain': 'The Brain of Morbius is Fourth Doctor story.',
   'doris': 'Doris is the Brigadier\'s wife in Battlefield.',
   'minor': 'Lots of planets are either Major or Minor - for instance Androzani Major and Androzani Minor.',
   'david': 'There are lots of Davids associated with Doctor Who including David Whitaker the show\'s first story editor, David Brierly who voiced K9 and David Tennant who played the Tenth Doctor.',
   'rheum': 'The Sandmen monsters in Sleep No More are made from rheum.',
   'selby': 'Tony Selby played Glitz in The Mysterious Planet, The Ultimate Foe and Dragonfire.',
   'ohila': 'Ohila is the leader of the Sisterhood of Karn in Night of the Doctor, The Magician\'s Apprentice and Hell Bent.',
   'sarah': 'Sarah Jane Smith was a companion of the Third and Fourth Doctors.',
   'lazar': 'Nyssa catches Lazar disease in Terminus and remains behind to help find a cure.',
   'scoop': 'The Time Scoop was created during the Dark Time on Gallifrey.',
   'child': 'The Doctor is the Timeless Child.',
   'swamp': 'When Mistfall comes the Marshmen leave the Swamp in Full Circle.',
   'lucas': 'Matt Lucas played companion Nardole.',
   'night': 'Night Terrors, In the Forest of the Night and Nikola Tesla\'s Night of Terror are all Doctor Who stories.',
   'chula': 'A Chula medical transport causes all the trouble in The Empty Child/The Doctor Dances.',
   'kinda': 'Kinda is a Fifth Doctor story.',
   'razor': 'The Master disguises himself as Razor in World Enough and Time.',
   'venom': 'Venom Grubs are one of the races on the Web Planet, Vortis.',
   'vlinx': 'The Vlinx works for UNIT.',
   'kandy': 'The Kandy Man is a deadly robot in The Happiness Patrol.',
   'wiles': 'John Wiles was the second producer of Doctor Who.',
   'ohica': 'Ohica is a member of the Sisterhood of Karn in The Brain of Morbius.',
   'ringo': 'Johnny Ringo appears in the Doctor Who story The Gunfighters and Ringo Star appears in The Devil\'s Chord.',
   'izlyr': 'Izlyr is an Ice Warrior who appears in The Curse of Peladon',
   'terra': 'Terra Alpha is the planet in The Happiness Patrol.',
   };
